/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Docling bounding box format (bottom-left origin, PDF standard)
 * @export
 * @interface BBox
 */
export interface BBox {
  /**
   *
   * @type {number}
   * @memberof BBox
   */
  l: number;
  /**
   *
   * @type {number}
   * @memberof BBox
   */
  b: number;
  /**
   *
   * @type {number}
   * @memberof BBox
   */
  r: number;
  /**
   *
   * @type {number}
   * @memberof BBox
   */
  t: number;
}

/**
 * Check if a given object implements the BBox interface.
 */
export function instanceOfBBox(value: object): value is BBox {
  if (!('l' in value) || value['l'] === undefined) return false;
  if (!('b' in value) || value['b'] === undefined) return false;
  if (!('r' in value) || value['r'] === undefined) return false;
  if (!('t' in value) || value['t'] === undefined) return false;
  return true;
}

export function BBoxFromJSON(json: any): BBox {
  return BBoxFromJSONTyped(json, false);
}

export function BBoxFromJSONTyped(json: any, ignoreDiscriminator: boolean): BBox {
  if (json == null) {
    return json;
  }
  return {
    l: json['l'],
    b: json['b'],
    r: json['r'],
    t: json['t'],
  };
}

export function BBoxToJSON(json: any): BBox {
  return BBoxToJSONTyped(json, false);
}

export function BBoxToJSONTyped(value?: BBox | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    l: value['l'],
    b: value['b'],
    r: value['r'],
    t: value['t'],
  };
}
