/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CitationResponse } from './CitationResponse';
import {
  CitationResponseFromJSON,
  CitationResponseFromJSONTyped,
  CitationResponseToJSON,
  CitationResponseToJSONTyped,
} from './CitationResponse';
import type { ClaimSubstantiationChunk } from './ClaimSubstantiationChunk';
import {
  ClaimSubstantiationChunkFromJSON,
  ClaimSubstantiationChunkFromJSONTyped,
  ClaimSubstantiationChunkToJSON,
  ClaimSubstantiationChunkToJSONTyped,
} from './ClaimSubstantiationChunk';
import type { ClaimsByChunk } from './ClaimsByChunk';
import {
  ClaimsByChunkFromJSON,
  ClaimsByChunkFromJSONTyped,
  ClaimsByChunkToJSON,
  ClaimsByChunkToJSONTyped,
} from './ClaimsByChunk';

/**
 * Response model for chunk re-evaluation results
 * @export
 * @interface ChunkReevaluationResponse
 */
export interface ChunkReevaluationResponse {
  /**
   * The index of the re-evaluated chunk
   * @type {number}
   * @memberof ChunkReevaluationResponse
   */
  chunkIndex: number;
  /**
   * The content of the re-evaluated chunk
   * @type {string}
   * @memberof ChunkReevaluationResponse
   */
  chunkContent: string;
  /**
   *
   * @type {ClaimsByChunk}
   * @memberof ChunkReevaluationResponse
   */
  claimsByChunk?: ClaimsByChunk | null;
  /**
   *
   * @type {CitationResponse}
   * @memberof ChunkReevaluationResponse
   */
  citationsByChunk?: CitationResponse | null;
  /**
   *
   * @type {ClaimSubstantiationChunk}
   * @memberof ChunkReevaluationResponse
   */
  claimSubstantiationsByChunk?: ClaimSubstantiationChunk | null;
  /**
   * List of agents that were successfully run on the chunk
   * @type {Array<string>}
   * @memberof ChunkReevaluationResponse
   */
  agentsRun: Array<string>;
  /**
   *
   * @type {number}
   * @memberof ChunkReevaluationResponse
   */
  processingTimeMs?: number | null;
}

/**
 * Check if a given object implements the ChunkReevaluationResponse interface.
 */
export function instanceOfChunkReevaluationResponse(value: object): value is ChunkReevaluationResponse {
  if (!('chunkIndex' in value) || value['chunkIndex'] === undefined) return false;
  if (!('chunkContent' in value) || value['chunkContent'] === undefined) return false;
  if (!('agentsRun' in value) || value['agentsRun'] === undefined) return false;
  return true;
}

export function ChunkReevaluationResponseFromJSON(json: any): ChunkReevaluationResponse {
  return ChunkReevaluationResponseFromJSONTyped(json, false);
}

export function ChunkReevaluationResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChunkReevaluationResponse {
  if (json == null) {
    return json;
  }
  return {
    chunkIndex: json['chunk_index'],
    chunkContent: json['chunk_content'],
    claimsByChunk: json['claims_by_chunk'] == null ? undefined : ClaimsByChunkFromJSON(json['claims_by_chunk']),
    citationsByChunk:
      json['citations_by_chunk'] == null ? undefined : CitationResponseFromJSON(json['citations_by_chunk']),
    claimSubstantiationsByChunk:
      json['claim_substantiations_by_chunk'] == null
        ? undefined
        : ClaimSubstantiationChunkFromJSON(json['claim_substantiations_by_chunk']),
    agentsRun: json['agents_run'],
    processingTimeMs: json['processing_time_ms'] == null ? undefined : json['processing_time_ms'],
  };
}

export function ChunkReevaluationResponseToJSON(json: any): ChunkReevaluationResponse {
  return ChunkReevaluationResponseToJSONTyped(json, false);
}

export function ChunkReevaluationResponseToJSONTyped(
  value?: ChunkReevaluationResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    chunk_index: value['chunkIndex'],
    chunk_content: value['chunkContent'],
    claims_by_chunk: ClaimsByChunkToJSON(value['claimsByChunk']),
    citations_by_chunk: CitationResponseToJSON(value['citationsByChunk']),
    claim_substantiations_by_chunk: ClaimSubstantiationChunkToJSON(value['claimSubstantiationsByChunk']),
    agents_run: value['agentsRun'],
    processing_time_ms: value['processingTimeMs'],
  };
}
