/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DoclingRegion } from './DoclingRegion';
import {
  DoclingRegionFromJSON,
  DoclingRegionFromJSONTyped,
  DoclingRegionToJSON,
  DoclingRegionToJSONTyped,
} from './DoclingRegion';

/**
 * Mapping from chunk indices to document items/regions
 *
 * Keys are string chunk indices, values are lists of regions
 * @export
 * @interface ChunkToItemsOutput
 */
export interface ChunkToItemsOutput {
  /**
   * Maps chunk_index (as string) to list of regions
   * @type {{ [key: string]: Array<DoclingRegion>; }}
   * @memberof ChunkToItemsOutput
   */
  mapping?: { [key: string]: Array<DoclingRegion> };
}

/**
 * Check if a given object implements the ChunkToItemsOutput interface.
 */
export function instanceOfChunkToItemsOutput(value: object): value is ChunkToItemsOutput {
  return true;
}

export function ChunkToItemsOutputFromJSON(json: any): ChunkToItemsOutput {
  return ChunkToItemsOutputFromJSONTyped(json, false);
}

export function ChunkToItemsOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChunkToItemsOutput {
  if (json == null) {
    return json;
  }
  return {
    mapping: json['mapping'] == null ? undefined : json['mapping'],
  };
}

export function ChunkToItemsOutputToJSON(json: any): ChunkToItemsOutput {
  return ChunkToItemsOutputToJSONTyped(json, false);
}

export function ChunkToItemsOutputToJSONTyped(
  value?: ChunkToItemsOutput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    mapping: value['mapping'],
  };
}
