/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentChunk } from './DocumentChunk';
import {
  DocumentChunkFromJSON,
  DocumentChunkFromJSONTyped,
  DocumentChunkToJSON,
  DocumentChunkToJSONTyped,
} from './DocumentChunk';

/**
 * Response model for chunk re-evaluation results
 * @export
 * @interface ChunkReevaluationResponse
 */
export interface ChunkReevaluationResponse {
  /**
   * The re-evaluated chunk
   * @type {DocumentChunk}
   * @memberof ChunkReevaluationResponse
   */
  chunk: DocumentChunk;
  /**
   * List of agents that were successfully run on the chunk
   * @type {Array<string>}
   * @memberof ChunkReevaluationResponse
   */
  agentsRun: Array<string>;
  /**
   *
   * @type {number}
   * @memberof ChunkReevaluationResponse
   */
  processingTimeMs?: number | null;
}

/**
 * Check if a given object implements the ChunkReevaluationResponse interface.
 */
export function instanceOfChunkReevaluationResponse(value: object): value is ChunkReevaluationResponse {
  if (!('chunk' in value) || value['chunk'] === undefined) return false;
  if (!('agentsRun' in value) || value['agentsRun'] === undefined) return false;
  return true;
}

export function ChunkReevaluationResponseFromJSON(json: any): ChunkReevaluationResponse {
  return ChunkReevaluationResponseFromJSONTyped(json, false);
}

export function ChunkReevaluationResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChunkReevaluationResponse {
  if (json == null) {
    return json;
  }
  return {
    chunk: DocumentChunkFromJSON(json['chunk']),
    agentsRun: json['agents_run'],
    processingTimeMs: json['processing_time_ms'] == null ? undefined : json['processing_time_ms'],
  };
}

export function ChunkReevaluationResponseToJSON(json: any): ChunkReevaluationResponse {
  return ChunkReevaluationResponseToJSONTyped(json, false);
}

export function ChunkReevaluationResponseToJSONTyped(
  value?: ChunkReevaluationResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    chunk: DocumentChunkToJSON(value['chunk']),
    agents_run: value['agentsRun'],
    processing_time_ms: value['processingTimeMs'],
  };
}
