/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Reference } from './Reference';
import { ReferenceFromJSON, ReferenceFromJSONTyped, ReferenceToJSON, ReferenceToJSONTyped } from './Reference';

/**
 *
 * @export
 * @interface CitationSuggestionResultWithClaimIndexInput
 */
export interface CitationSuggestionResultWithClaimIndexInput {
  /**
   * Ordered list of the most relevant references the author should consider when revising the paragraph
   * @type {Array<Reference>}
   * @memberof CitationSuggestionResultWithClaimIndexInput
   */
  relevantReferences: Array<Reference>;
  /**
   * High-level reasoning summarizing how the recommendations improve the paragraph's literature coverage
   * @type {string}
   * @memberof CitationSuggestionResultWithClaimIndexInput
   */
  rationale: string;
  /**
   *
   * @type {number}
   * @memberof CitationSuggestionResultWithClaimIndexInput
   */
  chunkIndex: number;
  /**
   *
   * @type {number}
   * @memberof CitationSuggestionResultWithClaimIndexInput
   */
  claimIndex: number;
}

/**
 * Check if a given object implements the CitationSuggestionResultWithClaimIndexInput interface.
 */
export function instanceOfCitationSuggestionResultWithClaimIndexInput(
  value: object,
): value is CitationSuggestionResultWithClaimIndexInput {
  if (!('relevantReferences' in value) || value['relevantReferences'] === undefined) return false;
  if (!('rationale' in value) || value['rationale'] === undefined) return false;
  if (!('chunkIndex' in value) || value['chunkIndex'] === undefined) return false;
  if (!('claimIndex' in value) || value['claimIndex'] === undefined) return false;
  return true;
}

export function CitationSuggestionResultWithClaimIndexInputFromJSON(
  json: any,
): CitationSuggestionResultWithClaimIndexInput {
  return CitationSuggestionResultWithClaimIndexInputFromJSONTyped(json, false);
}

export function CitationSuggestionResultWithClaimIndexInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CitationSuggestionResultWithClaimIndexInput {
  if (json == null) {
    return json;
  }
  return {
    relevantReferences:
      json['relevant_references'] == null ? [] : (json['relevant_references'] as Array<any>).map(ReferenceFromJSON),
    rationale: json['rationale'],
    chunkIndex: json['chunk_index'],
    claimIndex: json['claim_index'],
  };
}

export function CitationSuggestionResultWithClaimIndexInputToJSON(
  json: any,
): CitationSuggestionResultWithClaimIndexInput {
  return CitationSuggestionResultWithClaimIndexInputToJSONTyped(json, false);
}

export function CitationSuggestionResultWithClaimIndexInputToJSONTyped(
  value?: CitationSuggestionResultWithClaimIndexInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    relevant_references: (value['relevantReferences'] as Array<any>).map(ReferenceToJSON),
    rationale: value['rationale'],
    chunk_index: value['chunkIndex'],
    claim_index: value['claimIndex'],
  };
}
