/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Reference } from './Reference';
import { ReferenceFromJSON, ReferenceFromJSONTyped, ReferenceToJSON, ReferenceToJSONTyped } from './Reference';

/**
 *
 * @export
 * @interface CitationSuggestionResponseOutput
 */
export interface CitationSuggestionResponseOutput {
  /**
   * Ordered list of the most relevant references the author should consider when revising the paragraph
   * @type {Array<Reference>}
   * @memberof CitationSuggestionResponseOutput
   */
  relevantReferences: Array<Reference>;
  /**
   * High-level reasoning summarizing how the recommendations improve the paragraph's literature coverage
   * @type {string}
   * @memberof CitationSuggestionResponseOutput
   */
  rationale: string;
  /**
   * Index of the chunk this suggestion applies to
   * @type {number}
   * @memberof CitationSuggestionResponseOutput
   */
  chunkIndex?: number;
  /**
   * Index of the claim this suggestion applies to
   * @type {number}
   * @memberof CitationSuggestionResponseOutput
   */
  claimIndex?: number;
}

/**
 * Check if a given object implements the CitationSuggestionResponseOutput interface.
 */
export function instanceOfCitationSuggestionResponseOutput(value: object): value is CitationSuggestionResponseOutput {
  if (!('relevantReferences' in value) || value['relevantReferences'] === undefined) return false;
  if (!('rationale' in value) || value['rationale'] === undefined) return false;
  return true;
}

export function CitationSuggestionResponseOutputFromJSON(json: any): CitationSuggestionResponseOutput {
  return CitationSuggestionResponseOutputFromJSONTyped(json, false);
}

export function CitationSuggestionResponseOutputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CitationSuggestionResponseOutput {
  if (json == null) {
    return json;
  }
  return {
    relevantReferences:
      json['relevant_references'] == null ? [] : (json['relevant_references'] as Array<any>).map(ReferenceFromJSON),
    rationale: json['rationale'] || '',
    chunkIndex: json['chunk_index'],
    claimIndex: json['claim_index'],
  };
}

export function CitationSuggestionResponseOutputToJSON(json: any): CitationSuggestionResponseOutput {
  return CitationSuggestionResponseOutputToJSONTyped(json, false);
}

export function CitationSuggestionResponseOutputToJSONTyped(
  value?: CitationSuggestionResponseOutput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    relevant_references: (value['relevantReferences'] as Array<any>).map(ReferenceToJSON),
    rationale: value['rationale'],
    chunk_index: value['chunkIndex'],
    claim_index: value['claimIndex'],
  };
}
