/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReportOutputOutput } from './ReportOutputOutput';
import {
  ReportOutputOutputFromJSON,
  ReportOutputOutputFromJSONTyped,
  ReportOutputOutputToJSON,
  ReportOutputOutputToJSONTyped,
} from './ReportOutputOutput';
import type { DocumentIssue } from './DocumentIssue';
import {
  DocumentIssueFromJSON,
  DocumentIssueFromJSONTyped,
  DocumentIssueToJSON,
  DocumentIssueToJSONTyped,
} from './DocumentIssue';
import type { FileDocument } from './FileDocument';
import {
  FileDocumentFromJSON,
  FileDocumentFromJSONTyped,
  FileDocumentToJSON,
  FileDocumentToJSONTyped,
} from './FileDocument';
import type { EvidenceWeighterResponseWithClaimIndexOutput } from './EvidenceWeighterResponseWithClaimIndexOutput';
import {
  EvidenceWeighterResponseWithClaimIndexOutputFromJSON,
  EvidenceWeighterResponseWithClaimIndexOutputFromJSONTyped,
  EvidenceWeighterResponseWithClaimIndexOutputToJSON,
  EvidenceWeighterResponseWithClaimIndexOutputToJSONTyped,
} from './EvidenceWeighterResponseWithClaimIndexOutput';
import type { BibliographyItem } from './BibliographyItem';
import {
  BibliographyItemFromJSON,
  BibliographyItemFromJSONTyped,
  BibliographyItemToJSON,
  BibliographyItemToJSONTyped,
} from './BibliographyItem';
import type { WorkflowError } from './WorkflowError';
import {
  WorkflowErrorFromJSON,
  WorkflowErrorFromJSONTyped,
  WorkflowErrorToJSON,
  WorkflowErrorToJSONTyped,
} from './WorkflowError';
import type { LiteratureReviewResponseOutput } from './LiteratureReviewResponseOutput';
import {
  LiteratureReviewResponseOutputFromJSON,
  LiteratureReviewResponseOutputFromJSONTyped,
  LiteratureReviewResponseOutputToJSON,
  LiteratureReviewResponseOutputToJSONTyped,
} from './LiteratureReviewResponseOutput';
import type { DocumentChunkSummary } from './DocumentChunkSummary';
import {
  DocumentChunkSummaryFromJSON,
  DocumentChunkSummaryFromJSONTyped,
  DocumentChunkSummaryToJSON,
  DocumentChunkSummaryToJSONTyped,
} from './DocumentChunkSummary';
import type { SubstantiationWorkflowConfig } from './SubstantiationWorkflowConfig';
import {
  SubstantiationWorkflowConfigFromJSON,
  SubstantiationWorkflowConfigFromJSONTyped,
  SubstantiationWorkflowConfigToJSON,
  SubstantiationWorkflowConfigToJSONTyped,
} from './SubstantiationWorkflowConfig';
import type { DocumentSummary } from './DocumentSummary';
import {
  DocumentSummaryFromJSON,
  DocumentSummaryFromJSONTyped,
  DocumentSummaryToJSON,
  DocumentSummaryToJSONTyped,
} from './DocumentSummary';
import type { BibliographyItemValidation } from './BibliographyItemValidation';
import {
  BibliographyItemValidationFromJSON,
  BibliographyItemValidationFromJSONTyped,
  BibliographyItemValidationToJSON,
  BibliographyItemValidationToJSONTyped,
} from './BibliographyItemValidation';

/**
 * Summary version of ClaimSubstantiatorState with chunk summaries instead of full chunks
 * @export
 * @interface ClaimSubstantiatorStateSummary
 */
export interface ClaimSubstantiatorStateSummary {
  /**
   *
   * @type {FileDocument}
   * @memberof ClaimSubstantiatorStateSummary
   */
  file: FileDocument;
  /**
   *
   * @type {Array<FileDocument>}
   * @memberof ClaimSubstantiatorStateSummary
   */
  supportingFiles?: Array<FileDocument> | null;
  /**
   *
   * @type {SubstantiationWorkflowConfig}
   * @memberof ClaimSubstantiatorStateSummary
   */
  config: SubstantiationWorkflowConfig;
  /**
   *
   * @type {string}
   * @memberof ClaimSubstantiatorStateSummary
   */
  workflowRunId?: string | null;
  /**
   *
   * @type {Array<BibliographyItem>}
   * @memberof ClaimSubstantiatorStateSummary
   */
  references?: Array<BibliographyItem>;
  /**
   *
   * @type {Array<BibliographyItemValidation>}
   * @memberof ClaimSubstantiatorStateSummary
   */
  referencesValidated?: Array<BibliographyItemValidation>;
  /**
   * Lightweight chunk summaries without detailed analysis
   * @type {Array<DocumentChunkSummary>}
   * @memberof ClaimSubstantiatorStateSummary
   */
  chunks?: Array<DocumentChunkSummary>;
  /**
   *
   * @type {Array<WorkflowError>}
   * @memberof ClaimSubstantiatorStateSummary
   */
  errors?: Array<WorkflowError>;
  /**
   *
   * @type {DocumentSummary}
   * @memberof ClaimSubstantiatorStateSummary
   */
  mainDocumentSummary?: DocumentSummary | null;
  /**
   *
   * @type {{ [key: string]: DocumentSummary; }}
   * @memberof ClaimSubstantiatorStateSummary
   */
  supportingDocumentsSummaries?: { [key: string]: DocumentSummary } | null;
  /**
   *
   * @type {Array<EvidenceWeighterResponseWithClaimIndexOutput>}
   * @memberof ClaimSubstantiatorStateSummary
   */
  liveReportsAnalysis?: Array<EvidenceWeighterResponseWithClaimIndexOutput>;
  /**
   *
   * @type {LiteratureReviewResponseOutput}
   * @memberof ClaimSubstantiatorStateSummary
   */
  literatureReview?: LiteratureReviewResponseOutput | null;
  /**
   *
   * @type {ReportOutputOutput}
   * @memberof ClaimSubstantiatorStateSummary
   */
  addendumReport?: ReportOutputOutput | null;
  /**
   *
   * @type {Array<DocumentIssue>}
   * @memberof ClaimSubstantiatorStateSummary
   */
  rankedIssues?: Array<DocumentIssue>;
}

/**
 * Check if a given object implements the ClaimSubstantiatorStateSummary interface.
 */
export function instanceOfClaimSubstantiatorStateSummary(value: object): value is ClaimSubstantiatorStateSummary {
  if (!('file' in value) || value['file'] === undefined) return false;
  if (!('config' in value) || value['config'] === undefined) return false;
  return true;
}

export function ClaimSubstantiatorStateSummaryFromJSON(json: any): ClaimSubstantiatorStateSummary {
  return ClaimSubstantiatorStateSummaryFromJSONTyped(json, false);
}

export function ClaimSubstantiatorStateSummaryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ClaimSubstantiatorStateSummary {
  if (json == null) {
    return json;
  }
  return {
    file: FileDocumentFromJSON(json['file']),
    supportingFiles:
      json['supporting_files'] == null ? undefined : (json['supporting_files'] as Array<any>).map(FileDocumentFromJSON),
    config: SubstantiationWorkflowConfigFromJSON(json['config']),
    workflowRunId: json['workflow_run_id'] == null ? undefined : json['workflow_run_id'],
    references:
      json['references'] == null ? undefined : (json['references'] as Array<any>).map(BibliographyItemFromJSON),
    referencesValidated:
      json['references_validated'] == null
        ? undefined
        : (json['references_validated'] as Array<any>).map(BibliographyItemValidationFromJSON),
    chunks: json['chunks'] == null ? undefined : (json['chunks'] as Array<any>).map(DocumentChunkSummaryFromJSON),
    errors: json['errors'] == null ? undefined : (json['errors'] as Array<any>).map(WorkflowErrorFromJSON),
    mainDocumentSummary:
      json['main_document_summary'] == null ? undefined : DocumentSummaryFromJSON(json['main_document_summary']),
    supportingDocumentsSummaries:
      json['supporting_documents_summaries'] == null
        ? undefined
        : mapValues(json['supporting_documents_summaries'], DocumentSummaryFromJSON),
    liveReportsAnalysis:
      json['live_reports_analysis'] == null
        ? undefined
        : (json['live_reports_analysis'] as Array<any>).map(EvidenceWeighterResponseWithClaimIndexOutputFromJSON),
    literatureReview:
      json['literature_review'] == null ? undefined : LiteratureReviewResponseOutputFromJSON(json['literature_review']),
    addendumReport: json['addendum_report'] == null ? undefined : ReportOutputOutputFromJSON(json['addendum_report']),
    rankedIssues:
      json['ranked_issues'] == null ? undefined : (json['ranked_issues'] as Array<any>).map(DocumentIssueFromJSON),
  };
}

export function ClaimSubstantiatorStateSummaryToJSON(json: any): ClaimSubstantiatorStateSummary {
  return ClaimSubstantiatorStateSummaryToJSONTyped(json, false);
}

export function ClaimSubstantiatorStateSummaryToJSONTyped(
  value?: ClaimSubstantiatorStateSummary | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    file: FileDocumentToJSON(value['file']),
    supporting_files:
      value['supportingFiles'] == null ? undefined : (value['supportingFiles'] as Array<any>).map(FileDocumentToJSON),
    config: SubstantiationWorkflowConfigToJSON(value['config']),
    workflow_run_id: value['workflowRunId'],
    references:
      value['references'] == null ? undefined : (value['references'] as Array<any>).map(BibliographyItemToJSON),
    references_validated:
      value['referencesValidated'] == null
        ? undefined
        : (value['referencesValidated'] as Array<any>).map(BibliographyItemValidationToJSON),
    chunks: value['chunks'] == null ? undefined : (value['chunks'] as Array<any>).map(DocumentChunkSummaryToJSON),
    errors: value['errors'] == null ? undefined : (value['errors'] as Array<any>).map(WorkflowErrorToJSON),
    main_document_summary: DocumentSummaryToJSON(value['mainDocumentSummary']),
    supporting_documents_summaries:
      value['supportingDocumentsSummaries'] == null
        ? undefined
        : mapValues(value['supportingDocumentsSummaries'], DocumentSummaryToJSON),
    live_reports_analysis:
      value['liveReportsAnalysis'] == null
        ? undefined
        : (value['liveReportsAnalysis'] as Array<any>).map(EvidenceWeighterResponseWithClaimIndexOutputToJSON),
    literature_review: LiteratureReviewResponseOutputToJSON(value['literatureReview']),
    addendum_report: ReportOutputOutputToJSON(value['addendumReport']),
    ranked_issues:
      value['rankedIssues'] == null ? undefined : (value['rankedIssues'] as Array<any>).map(DocumentIssueToJSON),
  };
}
