/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentChunkOutput } from './DocumentChunkOutput';
import {
  DocumentChunkOutputFromJSON,
  DocumentChunkOutputFromJSONTyped,
  DocumentChunkOutputToJSON,
  DocumentChunkOutputToJSONTyped,
} from './DocumentChunkOutput';
import type { FileDocument } from './FileDocument';
import {
  FileDocumentFromJSON,
  FileDocumentFromJSONTyped,
  FileDocumentToJSON,
  FileDocumentToJSONTyped,
} from './FileDocument';
import type { BibliographyItem } from './BibliographyItem';
import {
  BibliographyItemFromJSON,
  BibliographyItemFromJSONTyped,
  BibliographyItemToJSON,
  BibliographyItemToJSONTyped,
} from './BibliographyItem';
import type { WorkflowError } from './WorkflowError';
import {
  WorkflowErrorFromJSON,
  WorkflowErrorFromJSONTyped,
  WorkflowErrorToJSON,
  WorkflowErrorToJSONTyped,
} from './WorkflowError';
import type { SubstantiationWorkflowConfig } from './SubstantiationWorkflowConfig';
import {
  SubstantiationWorkflowConfigFromJSON,
  SubstantiationWorkflowConfigFromJSONTyped,
  SubstantiationWorkflowConfigToJSON,
  SubstantiationWorkflowConfigToJSONTyped,
} from './SubstantiationWorkflowConfig';
import type { DocumentSummary } from './DocumentSummary';
import {
  DocumentSummaryFromJSON,
  DocumentSummaryFromJSONTyped,
  DocumentSummaryToJSON,
  DocumentSummaryToJSONTyped,
} from './DocumentSummary';

/**
 *
 * @export
 * @interface ClaimSubstantiatorStateOutput
 */
export interface ClaimSubstantiatorStateOutput {
  /**
   *
   * @type {FileDocument}
   * @memberof ClaimSubstantiatorStateOutput
   */
  file: FileDocument;
  /**
   *
   * @type {Array<FileDocument>}
   * @memberof ClaimSubstantiatorStateOutput
   */
  supportingFiles?: Array<FileDocument> | null;
  /**
   *
   * @type {SubstantiationWorkflowConfig}
   * @memberof ClaimSubstantiatorStateOutput
   */
  config: SubstantiationWorkflowConfig;
  /**
   *
   * @type {Array<BibliographyItem>}
   * @memberof ClaimSubstantiatorStateOutput
   */
  references?: Array<BibliographyItem>;
  /**
   *
   * @type {Array<DocumentChunkOutput>}
   * @memberof ClaimSubstantiatorStateOutput
   */
  chunks?: Array<DocumentChunkOutput>;
  /**
   * Errors that occurred during the processing of the document.
   * @type {Array<WorkflowError>}
   * @memberof ClaimSubstantiatorStateOutput
   */
  errors?: Array<WorkflowError>;
  /**
   *
   * @type {string}
   * @memberof ClaimSubstantiatorStateOutput
   */
  literatureReview?: string | null;
  /**
   *
   * @type {Array<DocumentSummary>}
   * @memberof ClaimSubstantiatorStateOutput
   */
  supportingDocumentsSummaries?: Array<DocumentSummary>;
}

/**
 * Check if a given object implements the ClaimSubstantiatorStateOutput interface.
 */
export function instanceOfClaimSubstantiatorStateOutput(value: object): value is ClaimSubstantiatorStateOutput {
  if (!('file' in value) || value['file'] === undefined) return false;
  if (!('config' in value) || value['config'] === undefined) return false;
  return true;
}

export function ClaimSubstantiatorStateOutputFromJSON(json: any): ClaimSubstantiatorStateOutput {
  return ClaimSubstantiatorStateOutputFromJSONTyped(json, false);
}

export function ClaimSubstantiatorStateOutputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ClaimSubstantiatorStateOutput {
  if (json == null) {
    return json;
  }
  return {
    file: FileDocumentFromJSON(json['file']),
    supportingFiles:
      json['supporting_files'] == null ? undefined : (json['supporting_files'] as Array<any>).map(FileDocumentFromJSON),
    config: SubstantiationWorkflowConfigFromJSON(json['config']),
    references:
      json['references'] == null ? undefined : (json['references'] as Array<any>).map(BibliographyItemFromJSON),
    chunks: json['chunks'] == null ? undefined : (json['chunks'] as Array<any>).map(DocumentChunkOutputFromJSON),
    errors: json['errors'] == null ? undefined : (json['errors'] as Array<any>).map(WorkflowErrorFromJSON),
    literatureReview: json['literature_review'] == null ? undefined : json['literature_review'],
    supportingDocumentsSummaries:
      json['supporting_documents_summaries'] == null
        ? undefined
        : (json['supporting_documents_summaries'] as Array<any>).map(DocumentSummaryFromJSON),
  };
}

export function ClaimSubstantiatorStateOutputToJSON(json: any): ClaimSubstantiatorStateOutput {
  return ClaimSubstantiatorStateOutputToJSONTyped(json, false);
}

export function ClaimSubstantiatorStateOutputToJSONTyped(
  value?: ClaimSubstantiatorStateOutput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    file: FileDocumentToJSON(value['file']),
    supporting_files:
      value['supportingFiles'] == null ? undefined : (value['supportingFiles'] as Array<any>).map(FileDocumentToJSON),
    config: SubstantiationWorkflowConfigToJSON(value['config']),
    references:
      value['references'] == null ? undefined : (value['references'] as Array<any>).map(BibliographyItemToJSON),
    chunks: value['chunks'] == null ? undefined : (value['chunks'] as Array<any>).map(DocumentChunkOutputToJSON),
    errors: value['errors'] == null ? undefined : (value['errors'] as Array<any>).map(WorkflowErrorToJSON),
    literature_review: value['literatureReview'],
    supporting_documents_summaries:
      value['supportingDocumentsSummaries'] == null
        ? undefined
        : (value['supportingDocumentsSummaries'] as Array<any>).map(DocumentSummaryToJSON),
  };
}
