/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClaimSubstantiatorStateSummary } from './ClaimSubstantiatorStateSummary';
import {
  ClaimSubstantiatorStateSummaryFromJSON,
  ClaimSubstantiatorStateSummaryFromJSONTyped,
  ClaimSubstantiatorStateSummaryToJSON,
  ClaimSubstantiatorStateSummaryToJSONTyped,
} from './ClaimSubstantiatorStateSummary';
import type { WorkflowRun } from './WorkflowRun';
import {
  WorkflowRunFromJSON,
  WorkflowRunFromJSONTyped,
  WorkflowRunToJSON,
  WorkflowRunToJSONTyped,
} from './WorkflowRun';

/**
 *
 * @export
 * @interface ClaimSubstantiationWorkflowDetail
 */
export interface ClaimSubstantiationWorkflowDetail {
  /**
   *
   * @type {WorkflowRun}
   * @memberof ClaimSubstantiationWorkflowDetail
   */
  run: WorkflowRun;
  /**
   *
   * @type {ClaimSubstantiatorStateSummary}
   * @memberof ClaimSubstantiationWorkflowDetail
   */
  state: ClaimSubstantiatorStateSummary;
}

/**
 * Check if a given object implements the ClaimSubstantiationWorkflowDetail interface.
 */
export function instanceOfClaimSubstantiationWorkflowDetail(value: object): value is ClaimSubstantiationWorkflowDetail {
  if (!('run' in value) || value['run'] === undefined) return false;
  if (!('state' in value) || value['state'] === undefined) return false;
  return true;
}

export function ClaimSubstantiationWorkflowDetailFromJSON(json: any): ClaimSubstantiationWorkflowDetail {
  return ClaimSubstantiationWorkflowDetailFromJSONTyped(json, false);
}

export function ClaimSubstantiationWorkflowDetailFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ClaimSubstantiationWorkflowDetail {
  if (json == null) {
    return json;
  }
  return {
    run: WorkflowRunFromJSON(json['run']),
    state: ClaimSubstantiatorStateSummaryFromJSON(json['state']),
  };
}

export function ClaimSubstantiationWorkflowDetailToJSON(json: any): ClaimSubstantiationWorkflowDetail {
  return ClaimSubstantiationWorkflowDetailToJSONTyped(json, false);
}

export function ClaimSubstantiationWorkflowDetailToJSONTyped(
  value?: ClaimSubstantiationWorkflowDetail | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    run: WorkflowRunToJSON(value['run']),
    state: ClaimSubstantiatorStateSummaryToJSON(value['state']),
  };
}
