/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToulminClaimResponse } from './ToulminClaimResponse';
import {
  ToulminClaimResponseFromJSON,
  ToulminClaimResponseFromJSONTyped,
  ToulminClaimResponseToJSON,
  ToulminClaimResponseToJSONTyped,
} from './ToulminClaimResponse';
import type { ClaimResponse } from './ClaimResponse';
import {
  ClaimResponseFromJSON,
  ClaimResponseFromJSONTyped,
  ClaimResponseToJSON,
  ClaimResponseToJSONTyped,
} from './ClaimResponse';
import type { ToulminClaim } from './ToulminClaim';
import {
  ToulminClaimFromJSON,
  ToulminClaimFromJSONTyped,
  ToulminClaimToJSON,
  ToulminClaimToJSONTyped,
} from './ToulminClaim';

/**
 * Updated claims for this chunk
 * @export
 * @interface ClaimsByChunk
 */
export interface ClaimsByChunk {
  /**
   * List of extracted claims with Toulmin elements when available
   * @type {Array<ToulminClaim>}
   * @memberof ClaimsByChunk
   */
  claims: Array<ToulminClaim>;
  /**
   * Overall rationale for the extractions and how the Toulmin elements were identified
   * @type {string}
   * @memberof ClaimsByChunk
   */
  rationale: string;
}

/**
 * Check if a given object implements the ClaimsByChunk interface.
 */
export function instanceOfClaimsByChunk(value: object): value is ClaimsByChunk {
  if (!('claims' in value) || value['claims'] === undefined) return false;
  if (!('rationale' in value) || value['rationale'] === undefined) return false;
  return true;
}

export function ClaimsByChunkFromJSON(json: any): ClaimsByChunk {
  return ClaimsByChunkFromJSONTyped(json, false);
}

export function ClaimsByChunkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimsByChunk {
  if (json == null) {
    return json;
  }
  return {
    claims: (json['claims'] as Array<any>).map(ToulminClaimFromJSON),
    rationale: json['rationale'],
  };
}

export function ClaimsByChunkToJSON(json: any): ClaimsByChunk {
  return ClaimsByChunkToJSONTyped(json, false);
}

export function ClaimsByChunkToJSONTyped(value?: ClaimsByChunk | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    claims: (value['claims'] as Array<any>).map(ToulminClaimToJSON),
    rationale: value['rationale'],
  };
}
