/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentChunkInput } from './DocumentChunkInput';
import {
  DocumentChunkInputFromJSON,
  DocumentChunkInputFromJSONTyped,
  DocumentChunkInputToJSON,
  DocumentChunkInputToJSONTyped,
} from './DocumentChunkInput';
import type { FileDocument } from './FileDocument';
import {
  FileDocumentFromJSON,
  FileDocumentFromJSONTyped,
  FileDocumentToJSON,
  FileDocumentToJSONTyped,
} from './FileDocument';
import type { BibliographyItem } from './BibliographyItem';
import {
  BibliographyItemFromJSON,
  BibliographyItemFromJSONTyped,
  BibliographyItemToJSON,
  BibliographyItemToJSONTyped,
} from './BibliographyItem';
import type { SubstantiationWorkflowConfig } from './SubstantiationWorkflowConfig';
import {
  SubstantiationWorkflowConfigFromJSON,
  SubstantiationWorkflowConfigFromJSONTyped,
  SubstantiationWorkflowConfigToJSON,
  SubstantiationWorkflowConfigToJSONTyped,
} from './SubstantiationWorkflowConfig';

/**
 *
 * @export
 * @interface ClaimSubstantiatorStateInput
 */
export interface ClaimSubstantiatorStateInput {
  /**
   *
   * @type {FileDocument}
   * @memberof ClaimSubstantiatorStateInput
   */
  file: FileDocument;
  /**
   *
   * @type {Array<FileDocument>}
   * @memberof ClaimSubstantiatorStateInput
   */
  supportingFiles?: Array<FileDocument> | null;
  /**
   *
   * @type {SubstantiationWorkflowConfig}
   * @memberof ClaimSubstantiatorStateInput
   */
  config?: SubstantiationWorkflowConfig;
  /**
   *
   * @type {Array<BibliographyItem>}
   * @memberof ClaimSubstantiatorStateInput
   */
  references?: Array<BibliographyItem>;
  /**
   *
   * @type {Array<DocumentChunkInput>}
   * @memberof ClaimSubstantiatorStateInput
   */
  chunks?: Array<DocumentChunkInput>;
}

/**
 * Check if a given object implements the ClaimSubstantiatorStateInput interface.
 */
export function instanceOfClaimSubstantiatorStateInput(value: object): value is ClaimSubstantiatorStateInput {
  if (!('file' in value) || value['file'] === undefined) return false;
  return true;
}

export function ClaimSubstantiatorStateInputFromJSON(json: any): ClaimSubstantiatorStateInput {
  return ClaimSubstantiatorStateInputFromJSONTyped(json, false);
}

export function ClaimSubstantiatorStateInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ClaimSubstantiatorStateInput {
  if (json == null) {
    return json;
  }
  return {
    file: FileDocumentFromJSON(json['file']),
    supportingFiles:
      json['supporting_files'] == null ? undefined : (json['supporting_files'] as Array<any>).map(FileDocumentFromJSON),
    config: json['config'] == null ? undefined : SubstantiationWorkflowConfigFromJSON(json['config']),
    references:
      json['references'] == null ? undefined : (json['references'] as Array<any>).map(BibliographyItemFromJSON),
    chunks: json['chunks'] == null ? undefined : (json['chunks'] as Array<any>).map(DocumentChunkInputFromJSON),
  };
}

export function ClaimSubstantiatorStateInputToJSON(json: any): ClaimSubstantiatorStateInput {
  return ClaimSubstantiatorStateInputToJSONTyped(json, false);
}

export function ClaimSubstantiatorStateInputToJSONTyped(
  value?: ClaimSubstantiatorStateInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    file: FileDocumentToJSON(value['file']),
    supporting_files:
      value['supportingFiles'] == null ? undefined : (value['supportingFiles'] as Array<any>).map(FileDocumentToJSON),
    config: SubstantiationWorkflowConfigToJSON(value['config']),
    references:
      value['references'] == null ? undefined : (value['references'] as Array<any>).map(BibliographyItemToJSON),
    chunks: value['chunks'] == null ? undefined : (value['chunks'] as Array<any>).map(DocumentChunkInputToJSON),
  };
}
