/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Severity } from './Severity';
import { SeverityFromJSON, SeverityFromJSONTyped, SeverityToJSON, SeverityToJSONTyped } from './Severity';
import type { HighlightWord } from './HighlightWord';
import {
  HighlightWordFromJSON,
  HighlightWordFromJSONTyped,
  HighlightWordToJSON,
  HighlightWordToJSONTyped,
} from './HighlightWord';

/**
 *
 * @export
 * @interface ClaimSubstantiationResultWithClaimIndex
 */
export interface ClaimSubstantiationResultWithClaimIndex {
  /**
   * A boolean value indicating whether the claim is substantiated by the supporting document(s) or not
   * @type {boolean}
   * @memberof ClaimSubstantiationResultWithClaimIndex
   */
  isSubstantiated: boolean;
  /**
   * Whether this claim represents common knowledge in the domain that typically doesn't require substantiation
   * @type {boolean}
   * @memberof ClaimSubstantiationResultWithClaimIndex
   */
  isCommonKnowledge?: boolean;
  /**
   * A brief explanation for why this claim is or is not considered common knowledge in the specified domain and context
   * @type {string}
   * @memberof ClaimSubstantiationResultWithClaimIndex
   */
  commonKnowledgeRationale?: string;
  /**
   * A brief rationale for why you think the claim is substantiated or not substantiated by the cited supporting document(s)
   * @type {string}
   * @memberof ClaimSubstantiationResultWithClaimIndex
   */
  rationale: string;
  /**
   * A brief suggestion on how the issue can be resolved, e.g., by adding more supporting documents or by rephrasing the original chunk, etc.
   * @type {string}
   * @memberof ClaimSubstantiationResultWithClaimIndex
   */
  feedback: string;
  /**
   * The severity of the substantiation issue with increasing numeric levels: 0 = no issue, 1 = not enough data to know for sure, 2 = may be ok, 3 = should be fixed, 4 = must be fixed
   * @type {Severity}
   * @memberof ClaimSubstantiationResultWithClaimIndex
   */
  severity: Severity;
  /**
   *
   * @type {Array<HighlightWord>}
   * @memberof ClaimSubstantiationResultWithClaimIndex
   */
  highlightWords?: Array<HighlightWord> | null;
  /**
   *
   * @type {number}
   * @memberof ClaimSubstantiationResultWithClaimIndex
   */
  chunkIndex: number;
  /**
   *
   * @type {number}
   * @memberof ClaimSubstantiationResultWithClaimIndex
   */
  claimIndex: number;
}

/**
 * Check if a given object implements the ClaimSubstantiationResultWithClaimIndex interface.
 */
export function instanceOfClaimSubstantiationResultWithClaimIndex(
  value: object,
): value is ClaimSubstantiationResultWithClaimIndex {
  if (!('isSubstantiated' in value) || value['isSubstantiated'] === undefined) return false;
  if (!('rationale' in value) || value['rationale'] === undefined) return false;
  if (!('feedback' in value) || value['feedback'] === undefined) return false;
  if (!('severity' in value) || value['severity'] === undefined) return false;
  if (!('chunkIndex' in value) || value['chunkIndex'] === undefined) return false;
  if (!('claimIndex' in value) || value['claimIndex'] === undefined) return false;
  return true;
}

export function ClaimSubstantiationResultWithClaimIndexFromJSON(json: any): ClaimSubstantiationResultWithClaimIndex {
  return ClaimSubstantiationResultWithClaimIndexFromJSONTyped(json, false);
}

export function ClaimSubstantiationResultWithClaimIndexFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ClaimSubstantiationResultWithClaimIndex {
  if (json == null) {
    return json;
  }
  return {
    isSubstantiated: json['is_substantiated'],
    isCommonKnowledge: json['is_common_knowledge'] == null ? undefined : json['is_common_knowledge'],
    commonKnowledgeRationale:
      json['common_knowledge_rationale'] == null ? undefined : json['common_knowledge_rationale'],
    rationale: json['rationale'],
    feedback: json['feedback'],
    severity: SeverityFromJSON(json['severity']),
    highlightWords:
      json['highlight_words'] == null ? undefined : (json['highlight_words'] as Array<any>).map(HighlightWordFromJSON),
    chunkIndex: json['chunk_index'],
    claimIndex: json['claim_index'],
  };
}

export function ClaimSubstantiationResultWithClaimIndexToJSON(json: any): ClaimSubstantiationResultWithClaimIndex {
  return ClaimSubstantiationResultWithClaimIndexToJSONTyped(json, false);
}

export function ClaimSubstantiationResultWithClaimIndexToJSONTyped(
  value?: ClaimSubstantiationResultWithClaimIndex | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    is_substantiated: value['isSubstantiated'],
    is_common_knowledge: value['isCommonKnowledge'],
    common_knowledge_rationale: value['commonKnowledgeRationale'],
    rationale: value['rationale'],
    feedback: value['feedback'],
    severity: SeverityToJSON(value['severity']),
    highlight_words:
      value['highlightWords'] == null ? undefined : (value['highlightWords'] as Array<any>).map(HighlightWordToJSON),
    chunk_index: value['chunkIndex'],
    claim_index: value['claimIndex'],
  };
}
