/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const CommonKnowledgeType = {
  WellEstablishedFacts: 'well_established_facts',
  BasicHistoricalDatesAndEvents: 'basic_historical_dates_and_events',
  FundamentalPrinciplesAndTheories: 'fundamental_principles_and_theories',
  GeneralStatisticalTrends: 'general_statistical_trends',
  StandardDefinitionsAndTerminology: 'standard_definitions_and_terminology',
  BasicGeographicDemographicOrInstitutionalFacts: 'basic_geographic_demographic_or_institutional_facts',
  Other: 'other',
} as const;
export type CommonKnowledgeType = (typeof CommonKnowledgeType)[keyof typeof CommonKnowledgeType];

export function instanceOfCommonKnowledgeType(value: any): boolean {
  for (const key in CommonKnowledgeType) {
    if (Object.prototype.hasOwnProperty.call(CommonKnowledgeType, key)) {
      if (CommonKnowledgeType[key as keyof typeof CommonKnowledgeType] === value) {
        return true;
      }
    }
  }
  return false;
}

export function CommonKnowledgeTypeFromJSON(json: any): CommonKnowledgeType {
  return CommonKnowledgeTypeFromJSONTyped(json, false);
}

export function CommonKnowledgeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonKnowledgeType {
  return json as CommonKnowledgeType;
}

export function CommonKnowledgeTypeToJSON(value?: CommonKnowledgeType | null): any {
  return value as any;
}

export function CommonKnowledgeTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CommonKnowledgeType {
  return value as CommonKnowledgeType;
}
