/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Page image with embedded base64 data
 * @export
 * @interface DoclingPageImage
 */
export interface DoclingPageImage {
  /**
   * Page number (0-indexed)
   * @type {number}
   * @memberof DoclingPageImage
   */
  page: number;
  /**
   * Page width in points
   * @type {number}
   * @memberof DoclingPageImage
   */
  width: number;
  /**
   * Page height in points
   * @type {number}
   * @memberof DoclingPageImage
   */
  height: number;
  /**
   * Base64-encoded PNG image data
   * @type {string}
   * @memberof DoclingPageImage
   */
  imageBase64: string;
  /**
   * Image format
   * @type {string}
   * @memberof DoclingPageImage
   */
  imageFormat?: string;
}

/**
 * Check if a given object implements the DoclingPageImage interface.
 */
export function instanceOfDoclingPageImage(value: object): value is DoclingPageImage {
  if (!('page' in value) || value['page'] === undefined) return false;
  if (!('width' in value) || value['width'] === undefined) return false;
  if (!('height' in value) || value['height'] === undefined) return false;
  if (!('imageBase64' in value) || value['imageBase64'] === undefined) return false;
  return true;
}

export function DoclingPageImageFromJSON(json: any): DoclingPageImage {
  return DoclingPageImageFromJSONTyped(json, false);
}

export function DoclingPageImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoclingPageImage {
  if (json == null) {
    return json;
  }
  return {
    page: json['page'],
    width: json['width'],
    height: json['height'],
    imageBase64: json['image_base64'],
    imageFormat: json['image_format'] == null ? undefined : json['image_format'],
  };
}

export function DoclingPageImageToJSON(json: any): DoclingPageImage {
  return DoclingPageImageToJSONTyped(json, false);
}

export function DoclingPageImageToJSONTyped(
  value?: DoclingPageImage | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    page: value['page'],
    width: value['width'],
    height: value['height'],
    image_base64: value['imageBase64'],
    image_format: value['imageFormat'],
  };
}
