/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DoclingPageImage } from './DoclingPageImage';
import {
  DoclingPageImageFromJSON,
  DoclingPageImageFromJSONTyped,
  DoclingPageImageToJSON,
  DoclingPageImageToJSONTyped,
} from './DoclingPageImage';
import type { DoclingItem } from './DoclingItem';
import {
  DoclingItemFromJSON,
  DoclingItemFromJSONTyped,
  DoclingItemToJSON,
  DoclingItemToJSONTyped,
} from './DoclingItem';

/**
 * Docling document structure for frontend rendering
 *
 * This is a simplified/flattened version of Docling's output,
 * optimized for our rendering needs.
 * @export
 * @interface DoclingDocumentOutput
 */
export interface DoclingDocumentOutput {
  /**
   *
   * @type {Array<DoclingPageImage>}
   * @memberof DoclingDocumentOutput
   */
  pages?: Array<DoclingPageImage>;
  /**
   *
   * @type {Array<DoclingItem>}
   * @memberof DoclingDocumentOutput
   */
  texts?: Array<DoclingItem>;
  /**
   *
   * @type {Array<DoclingItem>}
   * @memberof DoclingDocumentOutput
   */
  tables?: Array<DoclingItem>;
  /**
   *
   * @type {Array<DoclingItem>}
   * @memberof DoclingDocumentOutput
   */
  pictures?: Array<DoclingItem>;
  /**
   *
   * @type {Array<DoclingItem>}
   * @memberof DoclingDocumentOutput
   */
  keyValueItems?: Array<DoclingItem>;
}

/**
 * Check if a given object implements the DoclingDocumentOutput interface.
 */
export function instanceOfDoclingDocumentOutput(value: object): value is DoclingDocumentOutput {
  return true;
}

export function DoclingDocumentOutputFromJSON(json: any): DoclingDocumentOutput {
  return DoclingDocumentOutputFromJSONTyped(json, false);
}

export function DoclingDocumentOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoclingDocumentOutput {
  if (json == null) {
    return json;
  }
  return {
    pages: json['pages'] == null ? undefined : (json['pages'] as Array<any>).map(DoclingPageImageFromJSON),
    texts: json['texts'] == null ? undefined : (json['texts'] as Array<any>).map(DoclingItemFromJSON),
    tables: json['tables'] == null ? undefined : (json['tables'] as Array<any>).map(DoclingItemFromJSON),
    pictures: json['pictures'] == null ? undefined : (json['pictures'] as Array<any>).map(DoclingItemFromJSON),
    keyValueItems:
      json['key_value_items'] == null ? undefined : (json['key_value_items'] as Array<any>).map(DoclingItemFromJSON),
  };
}

export function DoclingDocumentOutputToJSON(json: any): DoclingDocumentOutput {
  return DoclingDocumentOutputToJSONTyped(json, false);
}

export function DoclingDocumentOutputToJSONTyped(
  value?: DoclingDocumentOutput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    pages: value['pages'] == null ? undefined : (value['pages'] as Array<any>).map(DoclingPageImageToJSON),
    texts: value['texts'] == null ? undefined : (value['texts'] as Array<any>).map(DoclingItemToJSON),
    tables: value['tables'] == null ? undefined : (value['tables'] as Array<any>).map(DoclingItemToJSON),
    pictures: value['pictures'] == null ? undefined : (value['pictures'] as Array<any>).map(DoclingItemToJSON),
    key_value_items:
      value['keyValueItems'] == null ? undefined : (value['keyValueItems'] as Array<any>).map(DoclingItemToJSON),
  };
}
