/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SeverityEnum } from './SeverityEnum';
import {
  SeverityEnumFromJSON,
  SeverityEnumFromJSONTyped,
  SeverityEnumToJSON,
  SeverityEnumToJSONTyped,
} from './SeverityEnum';
import type { ClaimCategory } from './ClaimCategory';
import {
  ClaimCategoryFromJSON,
  ClaimCategoryFromJSONTyped,
  ClaimCategoryToJSON,
  ClaimCategoryToJSONTyped,
} from './ClaimCategory';

/**
 *
 * @export
 * @interface DocumentIssue
 */
export interface DocumentIssue {
  /**
   * The title of the issue
   * @type {string}
   * @memberof DocumentIssue
   */
  title: string;
  /**
   * The description of the issue
   * @type {string}
   * @memberof DocumentIssue
   */
  description: string;
  /**
   * The severity of the issue
   * @type {SeverityEnum}
   * @memberof DocumentIssue
   */
  severity: SeverityEnum;
  /**
   *
   * @type {string}
   * @memberof DocumentIssue
   */
  additionalContext?: string | null;
  /**
   *
   * @type {number}
   * @memberof DocumentIssue
   */
  chunkIndex?: number | null;
  /**
   *
   * @type {number}
   * @memberof DocumentIssue
   */
  claimIndex?: number | null;
  /**
   *
   * @type {ClaimCategory}
   * @memberof DocumentIssue
   */
  claimCategory?: ClaimCategory | null;
}

/**
 * Check if a given object implements the DocumentIssue interface.
 */
export function instanceOfDocumentIssue(value: object): value is DocumentIssue {
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined) return false;
  if (!('severity' in value) || value['severity'] === undefined) return false;
  return true;
}

export function DocumentIssueFromJSON(json: any): DocumentIssue {
  return DocumentIssueFromJSONTyped(json, false);
}

export function DocumentIssueFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentIssue {
  if (json == null) {
    return json;
  }
  return {
    title: json['title'],
    description: json['description'],
    severity: SeverityEnumFromJSON(json['severity']),
    additionalContext: json['additional_context'] == null ? undefined : json['additional_context'],
    chunkIndex: json['chunk_index'] == null ? undefined : json['chunk_index'],
    claimIndex: json['claim_index'] == null ? undefined : json['claim_index'],
    claimCategory: json['claim_category'] == null ? undefined : ClaimCategoryFromJSON(json['claim_category']),
  };
}

export function DocumentIssueToJSON(json: any): DocumentIssue {
  return DocumentIssueToJSONTyped(json, false);
}

export function DocumentIssueToJSONTyped(value?: DocumentIssue | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    title: value['title'],
    description: value['description'],
    severity: SeverityEnumToJSON(value['severity']),
    additional_context: value['additionalContext'],
    chunk_index: value['chunkIndex'],
    claim_index: value['claimIndex'],
    claim_category: ClaimCategoryToJSON(value['claimCategory']),
  };
}
