/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DocumentSummary
 */
export interface DocumentSummary {
  /**
   * The title of the document
   * @type {string}
   * @memberof DocumentSummary
   */
  title: string;
  /**
   * The authors of the document (if available, otherwise empty string)
   * @type {string}
   * @memberof DocumentSummary
   */
  authors: string;
  /**
   * The publication date of the document, or 'Unknown' if not available
   * @type {string}
   * @memberof DocumentSummary
   */
  publicationDate: string;
  /**
   * The abstract of the document, or 'Unknown' if not available
   * @type {string}
   * @memberof DocumentSummary
   */
  _abstract: string;
  /**
   * A brief summary of the document in less than 2000 words. Make sure to include the main takeaways of the document.
   * @type {string}
   * @memberof DocumentSummary
   */
  summary: string;
}

/**
 * Check if a given object implements the DocumentSummary interface.
 */
export function instanceOfDocumentSummary(value: object): value is DocumentSummary {
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('authors' in value) || value['authors'] === undefined) return false;
  if (!('publicationDate' in value) || value['publicationDate'] === undefined) return false;
  if (!('_abstract' in value) || value['_abstract'] === undefined) return false;
  if (!('summary' in value) || value['summary'] === undefined) return false;
  return true;
}

export function DocumentSummaryFromJSON(json: any): DocumentSummary {
  return DocumentSummaryFromJSONTyped(json, false);
}

export function DocumentSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentSummary {
  if (json == null) {
    return json;
  }
  return {
    title: json['title'],
    authors: json['authors'],
    publicationDate: json['publication_date'],
    _abstract: json['abstract'],
    summary: json['summary'],
  };
}

export function DocumentSummaryToJSON(json: any): DocumentSummary {
  return DocumentSummaryToJSONTyped(json, false);
}

export function DocumentSummaryToJSONTyped(value?: DocumentSummary | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    title: value['title'],
    authors: value['authors'],
    publication_date: value['publicationDate'],
    abstract: value['_abstract'],
    summary: value['summary'],
  };
}
