/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClaimCommonKnowledgeResultWithClaimIndex } from './ClaimCommonKnowledgeResultWithClaimIndex';
import {
  ClaimCommonKnowledgeResultWithClaimIndexFromJSON,
  ClaimCommonKnowledgeResultWithClaimIndexFromJSONTyped,
  ClaimCommonKnowledgeResultWithClaimIndexToJSON,
  ClaimCommonKnowledgeResultWithClaimIndexToJSONTyped,
} from './ClaimCommonKnowledgeResultWithClaimIndex';
import type { Claims } from './Claims';
import { ClaimsFromJSON, ClaimsFromJSONTyped, ClaimsToJSON, ClaimsToJSONTyped } from './Claims';
import type { CitationSuggestionResultWithClaimIndexInput } from './CitationSuggestionResultWithClaimIndexInput';
import {
  CitationSuggestionResultWithClaimIndexInputFromJSON,
  CitationSuggestionResultWithClaimIndexInputFromJSONTyped,
  CitationSuggestionResultWithClaimIndexInputToJSON,
  CitationSuggestionResultWithClaimIndexInputToJSONTyped,
} from './CitationSuggestionResultWithClaimIndexInput';
import type { ClaimCategorizationResponseWithClaimIndex } from './ClaimCategorizationResponseWithClaimIndex';
import {
  ClaimCategorizationResponseWithClaimIndexFromJSON,
  ClaimCategorizationResponseWithClaimIndexFromJSONTyped,
  ClaimCategorizationResponseWithClaimIndexToJSON,
  ClaimCategorizationResponseWithClaimIndexToJSONTyped,
} from './ClaimCategorizationResponseWithClaimIndex';
import type { ClaimSubstantiationResultWithClaimIndex } from './ClaimSubstantiationResultWithClaimIndex';
import {
  ClaimSubstantiationResultWithClaimIndexFromJSON,
  ClaimSubstantiationResultWithClaimIndexFromJSONTyped,
  ClaimSubstantiationResultWithClaimIndexToJSON,
  ClaimSubstantiationResultWithClaimIndexToJSONTyped,
} from './ClaimSubstantiationResultWithClaimIndex';
import type { CitationResponseInput } from './CitationResponseInput';
import {
  CitationResponseInputFromJSON,
  CitationResponseInputFromJSONTyped,
  CitationResponseInputToJSON,
  CitationResponseInputToJSONTyped,
} from './CitationResponseInput';
import type { EvidenceWeighterResponseWithClaimIndexInput } from './EvidenceWeighterResponseWithClaimIndexInput';
import {
  EvidenceWeighterResponseWithClaimIndexInputFromJSON,
  EvidenceWeighterResponseWithClaimIndexInputFromJSONTyped,
  EvidenceWeighterResponseWithClaimIndexInputToJSON,
  EvidenceWeighterResponseWithClaimIndexInputToJSONTyped,
} from './EvidenceWeighterResponseWithClaimIndexInput';

/**
 * Independent chunk response object with all processing results
 * @export
 * @interface DocumentChunkInput
 */
export interface DocumentChunkInput {
  /**
   *
   * @type {string}
   * @memberof DocumentChunkInput
   */
  content: string;
  /**
   *
   * @type {number}
   * @memberof DocumentChunkInput
   */
  chunkIndex: number;
  /**
   *
   * @type {number}
   * @memberof DocumentChunkInput
   */
  paragraphIndex: number;
  /**
   *
   * @type {Claims}
   * @memberof DocumentChunkInput
   */
  claims?: Claims | null;
  /**
   *
   * @type {Array<ClaimCategorizationResponseWithClaimIndex>}
   * @memberof DocumentChunkInput
   */
  claimCategories?: Array<ClaimCategorizationResponseWithClaimIndex> | null;
  /**
   *
   * @type {CitationResponseInput}
   * @memberof DocumentChunkInput
   */
  citations?: CitationResponseInput | null;
  /**
   *
   * @type {Array<ClaimCommonKnowledgeResultWithClaimIndex>}
   * @memberof DocumentChunkInput
   */
  claimCommonKnowledgeResults?: Array<ClaimCommonKnowledgeResultWithClaimIndex>;
  /**
   *
   * @type {Array<ClaimSubstantiationResultWithClaimIndex>}
   * @memberof DocumentChunkInput
   */
  substantiations?: Array<ClaimSubstantiationResultWithClaimIndex>;
  /**
   *
   * @type {Array<CitationSuggestionResultWithClaimIndexInput>}
   * @memberof DocumentChunkInput
   */
  citationSuggestions?: Array<CitationSuggestionResultWithClaimIndexInput>;
  /**
   *
   * @type {Array<EvidenceWeighterResponseWithClaimIndexInput>}
   * @memberof DocumentChunkInput
   */
  liveReportsAnalysis?: Array<EvidenceWeighterResponseWithClaimIndexInput>;
}

/**
 * Check if a given object implements the DocumentChunkInput interface.
 */
export function instanceOfDocumentChunkInput(value: object): value is DocumentChunkInput {
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('chunkIndex' in value) || value['chunkIndex'] === undefined) return false;
  if (!('paragraphIndex' in value) || value['paragraphIndex'] === undefined) return false;
  return true;
}

export function DocumentChunkInputFromJSON(json: any): DocumentChunkInput {
  return DocumentChunkInputFromJSONTyped(json, false);
}

export function DocumentChunkInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentChunkInput {
  if (json == null) {
    return json;
  }
  return {
    content: json['content'],
    chunkIndex: json['chunk_index'],
    paragraphIndex: json['paragraph_index'],
    claims: json['claims'] == null ? undefined : ClaimsFromJSON(json['claims']),
    claimCategories:
      json['claim_categories'] == null
        ? undefined
        : (json['claim_categories'] as Array<any>).map(ClaimCategorizationResponseWithClaimIndexFromJSON),
    citations: json['citations'] == null ? undefined : CitationResponseInputFromJSON(json['citations']),
    claimCommonKnowledgeResults:
      json['claim_common_knowledge_results'] == null
        ? undefined
        : (json['claim_common_knowledge_results'] as Array<any>).map(ClaimCommonKnowledgeResultWithClaimIndexFromJSON),
    substantiations:
      json['substantiations'] == null
        ? undefined
        : (json['substantiations'] as Array<any>).map(ClaimSubstantiationResultWithClaimIndexFromJSON),
    citationSuggestions:
      json['citation_suggestions'] == null
        ? undefined
        : (json['citation_suggestions'] as Array<any>).map(CitationSuggestionResultWithClaimIndexInputFromJSON),
    liveReportsAnalysis:
      json['live_reports_analysis'] == null
        ? undefined
        : (json['live_reports_analysis'] as Array<any>).map(EvidenceWeighterResponseWithClaimIndexInputFromJSON),
  };
}

export function DocumentChunkInputToJSON(json: any): DocumentChunkInput {
  return DocumentChunkInputToJSONTyped(json, false);
}

export function DocumentChunkInputToJSONTyped(
  value?: DocumentChunkInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    content: value['content'],
    chunk_index: value['chunkIndex'],
    paragraph_index: value['paragraphIndex'],
    claims: ClaimsToJSON(value['claims']),
    claim_categories:
      value['claimCategories'] == null
        ? undefined
        : (value['claimCategories'] as Array<any>).map(ClaimCategorizationResponseWithClaimIndexToJSON),
    citations: CitationResponseInputToJSON(value['citations']),
    claim_common_knowledge_results:
      value['claimCommonKnowledgeResults'] == null
        ? undefined
        : (value['claimCommonKnowledgeResults'] as Array<any>).map(ClaimCommonKnowledgeResultWithClaimIndexToJSON),
    substantiations:
      value['substantiations'] == null
        ? undefined
        : (value['substantiations'] as Array<any>).map(ClaimSubstantiationResultWithClaimIndexToJSON),
    citation_suggestions:
      value['citationSuggestions'] == null
        ? undefined
        : (value['citationSuggestions'] as Array<any>).map(CitationSuggestionResultWithClaimIndexInputToJSON),
    live_reports_analysis:
      value['liveReportsAnalysis'] == null
        ? undefined
        : (value['liveReportsAnalysis'] as Array<any>).map(EvidenceWeighterResponseWithClaimIndexInputToJSON),
  };
}
