/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CitationResponseOutput } from './CitationResponseOutput';
import {
  CitationResponseOutputFromJSON,
  CitationResponseOutputFromJSONTyped,
  CitationResponseOutputToJSON,
  CitationResponseOutputToJSONTyped,
} from './CitationResponseOutput';
import type { ClaimCommonKnowledgeResultWithClaimIndex } from './ClaimCommonKnowledgeResultWithClaimIndex';
import {
  ClaimCommonKnowledgeResultWithClaimIndexFromJSON,
  ClaimCommonKnowledgeResultWithClaimIndexFromJSONTyped,
  ClaimCommonKnowledgeResultWithClaimIndexToJSON,
  ClaimCommonKnowledgeResultWithClaimIndexToJSONTyped,
} from './ClaimCommonKnowledgeResultWithClaimIndex';
import type { Claims } from './Claims';
import { ClaimsFromJSON, ClaimsFromJSONTyped, ClaimsToJSON, ClaimsToJSONTyped } from './Claims';
import type { EvidenceWeighterResponseWithClaimIndexOutput } from './EvidenceWeighterResponseWithClaimIndexOutput';
import {
  EvidenceWeighterResponseWithClaimIndexOutputFromJSON,
  EvidenceWeighterResponseWithClaimIndexOutputFromJSONTyped,
  EvidenceWeighterResponseWithClaimIndexOutputToJSON,
  EvidenceWeighterResponseWithClaimIndexOutputToJSONTyped,
} from './EvidenceWeighterResponseWithClaimIndexOutput';
import type { CitationSuggestionResultWithClaimIndexOutput } from './CitationSuggestionResultWithClaimIndexOutput';
import {
  CitationSuggestionResultWithClaimIndexOutputFromJSON,
  CitationSuggestionResultWithClaimIndexOutputFromJSONTyped,
  CitationSuggestionResultWithClaimIndexOutputToJSON,
  CitationSuggestionResultWithClaimIndexOutputToJSONTyped,
} from './CitationSuggestionResultWithClaimIndexOutput';
import type { ClaimCategorizationResponseWithClaimIndex } from './ClaimCategorizationResponseWithClaimIndex';
import {
  ClaimCategorizationResponseWithClaimIndexFromJSON,
  ClaimCategorizationResponseWithClaimIndexFromJSONTyped,
  ClaimCategorizationResponseWithClaimIndexToJSON,
  ClaimCategorizationResponseWithClaimIndexToJSONTyped,
} from './ClaimCategorizationResponseWithClaimIndex';
import type { ClaimSubstantiationResultWithClaimIndex } from './ClaimSubstantiationResultWithClaimIndex';
import {
  ClaimSubstantiationResultWithClaimIndexFromJSON,
  ClaimSubstantiationResultWithClaimIndexFromJSONTyped,
  ClaimSubstantiationResultWithClaimIndexToJSON,
  ClaimSubstantiationResultWithClaimIndexToJSONTyped,
} from './ClaimSubstantiationResultWithClaimIndex';

/**
 * Independent chunk response object with all processing results
 * @export
 * @interface DocumentChunkOutput
 */
export interface DocumentChunkOutput {
  /**
   *
   * @type {string}
   * @memberof DocumentChunkOutput
   */
  content: string;
  /**
   *
   * @type {number}
   * @memberof DocumentChunkOutput
   */
  chunkIndex: number;
  /**
   *
   * @type {number}
   * @memberof DocumentChunkOutput
   */
  paragraphIndex: number;
  /**
   *
   * @type {Claims}
   * @memberof DocumentChunkOutput
   */
  claims?: Claims | null;
  /**
   *
   * @type {CitationResponseOutput}
   * @memberof DocumentChunkOutput
   */
  citations?: CitationResponseOutput | null;
  /**
   *
   * @type {Array<ClaimCategorizationResponseWithClaimIndex>}
   * @memberof DocumentChunkOutput
   */
  claimCategories?: Array<ClaimCategorizationResponseWithClaimIndex>;
  /**
   *
   * @type {Array<ClaimCommonKnowledgeResultWithClaimIndex>}
   * @memberof DocumentChunkOutput
   */
  claimCommonKnowledgeResults?: Array<ClaimCommonKnowledgeResultWithClaimIndex>;
  /**
   *
   * @type {Array<ClaimSubstantiationResultWithClaimIndex>}
   * @memberof DocumentChunkOutput
   */
  substantiations?: Array<ClaimSubstantiationResultWithClaimIndex>;
  /**
   *
   * @type {Array<CitationSuggestionResultWithClaimIndexOutput>}
   * @memberof DocumentChunkOutput
   */
  citationSuggestions?: Array<CitationSuggestionResultWithClaimIndexOutput>;
  /**
   *
   * @type {Array<EvidenceWeighterResponseWithClaimIndexOutput>}
   * @memberof DocumentChunkOutput
   */
  liveReportsAnalysis?: Array<EvidenceWeighterResponseWithClaimIndexOutput>;
}

/**
 * Check if a given object implements the DocumentChunkOutput interface.
 */
export function instanceOfDocumentChunkOutput(value: object): value is DocumentChunkOutput {
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('chunkIndex' in value) || value['chunkIndex'] === undefined) return false;
  if (!('paragraphIndex' in value) || value['paragraphIndex'] === undefined) return false;
  return true;
}

export function DocumentChunkOutputFromJSON(json: any): DocumentChunkOutput {
  return DocumentChunkOutputFromJSONTyped(json, false);
}

export function DocumentChunkOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentChunkOutput {
  if (json == null) {
    return json;
  }
  return {
    content: json['content'],
    chunkIndex: json['chunk_index'],
    paragraphIndex: json['paragraph_index'],
    claims: json['claims'] == null ? undefined : ClaimsFromJSON(json['claims']),
    citations: json['citations'] == null ? undefined : CitationResponseOutputFromJSON(json['citations']),
    claimCategories:
      json['claim_categories'] == null
        ? undefined
        : (json['claim_categories'] as Array<any>).map(ClaimCategorizationResponseWithClaimIndexFromJSON),
    claimCommonKnowledgeResults:
      json['claim_common_knowledge_results'] == null
        ? undefined
        : (json['claim_common_knowledge_results'] as Array<any>).map(ClaimCommonKnowledgeResultWithClaimIndexFromJSON),
    substantiations:
      json['substantiations'] == null
        ? undefined
        : (json['substantiations'] as Array<any>).map(ClaimSubstantiationResultWithClaimIndexFromJSON),
    citationSuggestions:
      json['citation_suggestions'] == null
        ? undefined
        : (json['citation_suggestions'] as Array<any>).map(CitationSuggestionResultWithClaimIndexOutputFromJSON),
    liveReportsAnalysis:
      json['live_reports_analysis'] == null
        ? undefined
        : (json['live_reports_analysis'] as Array<any>).map(EvidenceWeighterResponseWithClaimIndexOutputFromJSON),
  };
}

export function DocumentChunkOutputToJSON(json: any): DocumentChunkOutput {
  return DocumentChunkOutputToJSONTyped(json, false);
}

export function DocumentChunkOutputToJSONTyped(
  value?: DocumentChunkOutput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    content: value['content'],
    chunk_index: value['chunkIndex'],
    paragraph_index: value['paragraphIndex'],
    claims: ClaimsToJSON(value['claims']),
    citations: CitationResponseOutputToJSON(value['citations']),
    claim_categories:
      value['claimCategories'] == null
        ? undefined
        : (value['claimCategories'] as Array<any>).map(ClaimCategorizationResponseWithClaimIndexToJSON),
    claim_common_knowledge_results:
      value['claimCommonKnowledgeResults'] == null
        ? undefined
        : (value['claimCommonKnowledgeResults'] as Array<any>).map(ClaimCommonKnowledgeResultWithClaimIndexToJSON),
    substantiations:
      value['substantiations'] == null
        ? undefined
        : (value['substantiations'] as Array<any>).map(ClaimSubstantiationResultWithClaimIndexToJSON),
    citation_suggestions:
      value['citationSuggestions'] == null
        ? undefined
        : (value['citationSuggestions'] as Array<any>).map(CitationSuggestionResultWithClaimIndexOutputToJSON),
    live_reports_analysis:
      value['liveReportsAnalysis'] == null
        ? undefined
        : (value['liveReportsAnalysis'] as Array<any>).map(EvidenceWeighterResponseWithClaimIndexOutputToJSON),
  };
}
