/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Summary chunk info without detailed analysis (for API responses)
 * @export
 * @interface DocumentChunkSummary
 */
export interface DocumentChunkSummary {
  /**
   *
   * @type {string}
   * @memberof DocumentChunkSummary
   */
  content: string;
  /**
   *
   * @type {number}
   * @memberof DocumentChunkSummary
   */
  chunkIndex: number;
  /**
   *
   * @type {number}
   * @memberof DocumentChunkSummary
   */
  paragraphIndex: number;
  /**
   * Whether this chunk has claims
   * @type {boolean}
   * @memberof DocumentChunkSummary
   */
  hasClaims?: boolean;
  /**
   * Number of claims in this chunk
   * @type {number}
   * @memberof DocumentChunkSummary
   */
  claimsCount?: number;
  /**
   * Whether this chunk has citations
   * @type {boolean}
   * @memberof DocumentChunkSummary
   */
  hasCitations?: boolean;
  /**
   * Number of citations in this chunk
   * @type {number}
   * @memberof DocumentChunkSummary
   */
  citationsCount?: number;
}

/**
 * Check if a given object implements the DocumentChunkSummary interface.
 */
export function instanceOfDocumentChunkSummary(value: object): value is DocumentChunkSummary {
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('chunkIndex' in value) || value['chunkIndex'] === undefined) return false;
  if (!('paragraphIndex' in value) || value['paragraphIndex'] === undefined) return false;
  return true;
}

export function DocumentChunkSummaryFromJSON(json: any): DocumentChunkSummary {
  return DocumentChunkSummaryFromJSONTyped(json, false);
}

export function DocumentChunkSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentChunkSummary {
  if (json == null) {
    return json;
  }
  return {
    content: json['content'],
    chunkIndex: json['chunk_index'],
    paragraphIndex: json['paragraph_index'],
    hasClaims: json['has_claims'] == null ? undefined : json['has_claims'],
    claimsCount: json['claims_count'] == null ? undefined : json['claims_count'],
    hasCitations: json['has_citations'] == null ? undefined : json['has_citations'],
    citationsCount: json['citations_count'] == null ? undefined : json['citations_count'],
  };
}

export function DocumentChunkSummaryToJSON(json: any): DocumentChunkSummary {
  return DocumentChunkSummaryToJSONTyped(json, false);
}

export function DocumentChunkSummaryToJSONTyped(
  value?: DocumentChunkSummary | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    content: value['content'],
    chunk_index: value['chunkIndex'],
    paragraph_index: value['paragraphIndex'],
    has_claims: value['hasClaims'],
    claims_count: value['claimsCount'],
    has_citations: value['hasCitations'],
    citations_count: value['citationsCount'],
  };
}
