/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Direct URL to the downloadable version of the located source, or null if no match was found
 * @export
 * @interface DownloadUrl
 */
export interface DownloadUrl {}

/**
 * Check if a given object implements the DownloadUrl interface.
 */
export function instanceOfDownloadUrl(value: object): value is DownloadUrl {
  return true;
}

export function DownloadUrlFromJSON(json: any): DownloadUrl {
  return DownloadUrlFromJSONTyped(json, false);
}

export function DownloadUrlFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadUrl {
  return json;
}

export function DownloadUrlToJSON(json: any): DownloadUrl {
  return DownloadUrlToJSONTyped(json, false);
}

export function DownloadUrlToJSONTyped(value?: DownloadUrl | null, ignoreDiscriminator: boolean = false): any {
  return value;
}
