/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const EvidenceAlignmentLevel = {
  Unverifiable: 'unverifiable',
  Supported: 'supported',
  PartiallySupported: 'partially_supported',
  Unsupported: 'unsupported',
} as const;
export type EvidenceAlignmentLevel = (typeof EvidenceAlignmentLevel)[keyof typeof EvidenceAlignmentLevel];

export function instanceOfEvidenceAlignmentLevel(value: any): boolean {
  for (const key in EvidenceAlignmentLevel) {
    if (Object.prototype.hasOwnProperty.call(EvidenceAlignmentLevel, key)) {
      if (EvidenceAlignmentLevel[key as keyof typeof EvidenceAlignmentLevel] === value) {
        return true;
      }
    }
  }
  return false;
}

export function EvidenceAlignmentLevelFromJSON(json: any): EvidenceAlignmentLevel {
  return EvidenceAlignmentLevelFromJSONTyped(json, false);
}

export function EvidenceAlignmentLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvidenceAlignmentLevel {
  return json as EvidenceAlignmentLevel;
}

export function EvidenceAlignmentLevelToJSON(value?: EvidenceAlignmentLevel | null): any {
  return value as any;
}

export function EvidenceAlignmentLevelToJSONTyped(value: any, ignoreDiscriminator: boolean): EvidenceAlignmentLevel {
  return value as EvidenceAlignmentLevel;
}
