/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DoclingDocumentOutput } from './DoclingDocumentOutput';
import {
  DoclingDocumentOutputFromJSON,
  DoclingDocumentOutputFromJSONTyped,
  DoclingDocumentOutputToJSON,
  DoclingDocumentOutputToJSONTyped,
} from './DoclingDocumentOutput';

/**
 *
 * @export
 * @interface FileDocumentOutput
 */
export interface FileDocumentOutput {
  /**
   * The original name of the uploaded file, as saved in the user file system
   * @type {string}
   * @memberof FileDocumentOutput
   */
  fileName: string;
  /**
   * The path to the uploaded file, as saved in the file system
   * @type {string}
   * @memberof FileDocumentOutput
   */
  filePath: string;
  /**
   * The MIME type of the uploaded file
   * @type {string}
   * @memberof FileDocumentOutput
   */
  fileType: string;
  /**
   * The uploaded file content converted to markdown
   * @type {string}
   * @memberof FileDocumentOutput
   */
  markdown: string;
  /**
   * The approximate number of tokens in the markdown content
   * @type {number}
   * @memberof FileDocumentOutput
   */
  markdownTokenCount: number;
  /**
   *
   * @type {DoclingDocumentOutput}
   * @memberof FileDocumentOutput
   */
  doclingDocument?: DoclingDocumentOutput | null;
}

/**
 * Check if a given object implements the FileDocumentOutput interface.
 */
export function instanceOfFileDocumentOutput(value: object): value is FileDocumentOutput {
  if (!('fileName' in value) || value['fileName'] === undefined) return false;
  if (!('filePath' in value) || value['filePath'] === undefined) return false;
  if (!('fileType' in value) || value['fileType'] === undefined) return false;
  if (!('markdown' in value) || value['markdown'] === undefined) return false;
  if (!('markdownTokenCount' in value) || value['markdownTokenCount'] === undefined) return false;
  return true;
}

export function FileDocumentOutputFromJSON(json: any): FileDocumentOutput {
  return FileDocumentOutputFromJSONTyped(json, false);
}

export function FileDocumentOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileDocumentOutput {
  if (json == null) {
    return json;
  }
  return {
    fileName: json['file_name'],
    filePath: json['file_path'],
    fileType: json['file_type'],
    markdown: json['markdown'],
    markdownTokenCount: json['markdown_token_count'],
    doclingDocument:
      json['docling_document'] == null ? undefined : DoclingDocumentOutputFromJSON(json['docling_document']),
  };
}

export function FileDocumentOutputToJSON(json: any): FileDocumentOutput {
  return FileDocumentOutputToJSONTyped(json, false);
}

export function FileDocumentOutputToJSONTyped(
  value?: FileDocumentOutput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    file_name: value['fileName'],
    file_path: value['filePath'],
    file_type: value['fileType'],
    markdown: value['markdown'],
    markdown_token_count: value['markdownTokenCount'],
    docling_document: DoclingDocumentOutputToJSON(value['doclingDocument']),
  };
}
