/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FileDocument
 */
export interface FileDocument {
  /**
   *
   * @type {string}
   * @memberof FileDocument
   */
  fileName?: string;
  /**
   *
   * @type {string}
   * @memberof FileDocument
   */
  filePath?: string;
  /**
   *
   * @type {string}
   * @memberof FileDocument
   */
  fileType?: string;
  /**
   *
   * @type {string}
   * @memberof FileDocument
   */
  markdown: string;
}

/**
 * Check if a given object implements the FileDocument interface.
 */
export function instanceOfFileDocument(value: object): value is FileDocument {
  if (!('markdown' in value) || value['markdown'] === undefined) return false;
  return true;
}

export function FileDocumentFromJSON(json: any): FileDocument {
  return FileDocumentFromJSONTyped(json, false);
}

export function FileDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileDocument {
  if (json == null) {
    return json;
  }
  return {
    fileName: json['fileName'] == null ? undefined : json['fileName'],
    filePath: json['filePath'] == null ? undefined : json['filePath'],
    fileType: json['fileType'] == null ? undefined : json['fileType'],
    markdown: json['markdown'],
  };
}

export function FileDocumentToJSON(json: any): FileDocument {
  return FileDocumentToJSONTyped(json, false);
}

export function FileDocumentToJSONTyped(value?: FileDocument | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    fileName: value['fileName'],
    filePath: value['filePath'],
    fileType: value['fileType'],
    markdown: value['markdown'],
  };
}
