/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface HighlightWord
 */
export interface HighlightWord {
  /**
   * The specific word or phrase to highlight
   * @type {string}
   * @memberof HighlightWord
   */
  word: string;
  /**
   * Brief explanation of why this word is important for the claim
   * @type {string}
   * @memberof HighlightWord
   */
  rationale: string;
}

/**
 * Check if a given object implements the HighlightWord interface.
 */
export function instanceOfHighlightWord(value: object): value is HighlightWord {
  if (!('word' in value) || value['word'] === undefined) return false;
  if (!('rationale' in value) || value['rationale'] === undefined) return false;
  return true;
}

export function HighlightWordFromJSON(json: any): HighlightWord {
  return HighlightWordFromJSONTyped(json, false);
}

export function HighlightWordFromJSONTyped(json: any, ignoreDiscriminator: boolean): HighlightWord {
  if (json == null) {
    return json;
  }
  return {
    word: json['word'],
    rationale: json['rationale'],
  };
}

export function HighlightWordToJSON(json: any): HighlightWord {
  return HighlightWordToJSONTyped(json, false);
}

export function HighlightWordToJSONTyped(value?: HighlightWord | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    word: value['word'],
    rationale: value['rationale'],
  };
}
