/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const LibAgentsLiteratureReviewRecommendedAction = {
  AddNewCitation: 'add_new_citation',
  CiteExistingReferenceInNewPlace: 'cite_existing_reference_in_new_place',
  ReplaceExistingReference: 'replace_existing_reference',
  DiscussReference: 'discuss_reference',
  NoAction: 'no_action',
  Other: 'other',
} as const;
export type LibAgentsLiteratureReviewRecommendedAction =
  (typeof LibAgentsLiteratureReviewRecommendedAction)[keyof typeof LibAgentsLiteratureReviewRecommendedAction];

export function instanceOfLibAgentsLiteratureReviewRecommendedAction(value: any): boolean {
  for (const key in LibAgentsLiteratureReviewRecommendedAction) {
    if (Object.prototype.hasOwnProperty.call(LibAgentsLiteratureReviewRecommendedAction, key)) {
      if (
        LibAgentsLiteratureReviewRecommendedAction[key as keyof typeof LibAgentsLiteratureReviewRecommendedAction] ===
        value
      ) {
        return true;
      }
    }
  }
  return false;
}

export function LibAgentsLiteratureReviewRecommendedActionFromJSON(
  json: any,
): LibAgentsLiteratureReviewRecommendedAction {
  return LibAgentsLiteratureReviewRecommendedActionFromJSONTyped(json, false);
}

export function LibAgentsLiteratureReviewRecommendedActionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LibAgentsLiteratureReviewRecommendedAction {
  return json as LibAgentsLiteratureReviewRecommendedAction;
}

export function LibAgentsLiteratureReviewRecommendedActionToJSON(
  value?: LibAgentsLiteratureReviewRecommendedAction | null,
): any {
  return value as any;
}

export function LibAgentsLiteratureReviewRecommendedActionToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): LibAgentsLiteratureReviewRecommendedAction {
  return value as LibAgentsLiteratureReviewRecommendedAction;
}
