/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MethodologicalAlignmentState } from './MethodologicalAlignmentState';
import {
  MethodologicalAlignmentStateFromJSON,
  MethodologicalAlignmentStateFromJSONTyped,
  MethodologicalAlignmentStateToJSON,
  MethodologicalAlignmentStateToJSONTyped,
} from './MethodologicalAlignmentState';
import type { WorkflowRun } from './WorkflowRun';
import {
  WorkflowRunFromJSON,
  WorkflowRunFromJSONTyped,
  WorkflowRunToJSON,
  WorkflowRunToJSONTyped,
} from './WorkflowRun';

/**
 *
 * @export
 * @interface MethodologicalAlignmentWorkflowDetail
 */
export interface MethodologicalAlignmentWorkflowDetail {
  /**
   *
   * @type {WorkflowRun}
   * @memberof MethodologicalAlignmentWorkflowDetail
   */
  run: WorkflowRun;
  /**
   *
   * @type {MethodologicalAlignmentState}
   * @memberof MethodologicalAlignmentWorkflowDetail
   */
  state: MethodologicalAlignmentState;
}

/**
 * Check if a given object implements the MethodologicalAlignmentWorkflowDetail interface.
 */
export function instanceOfMethodologicalAlignmentWorkflowDetail(
  value: object,
): value is MethodologicalAlignmentWorkflowDetail {
  if (!('run' in value) || value['run'] === undefined) return false;
  if (!('state' in value) || value['state'] === undefined) return false;
  return true;
}

export function MethodologicalAlignmentWorkflowDetailFromJSON(json: any): MethodologicalAlignmentWorkflowDetail {
  return MethodologicalAlignmentWorkflowDetailFromJSONTyped(json, false);
}

export function MethodologicalAlignmentWorkflowDetailFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MethodologicalAlignmentWorkflowDetail {
  if (json == null) {
    return json;
  }
  return {
    run: WorkflowRunFromJSON(json['run']),
    state: MethodologicalAlignmentStateFromJSON(json['state']),
  };
}

export function MethodologicalAlignmentWorkflowDetailToJSON(json: any): MethodologicalAlignmentWorkflowDetail {
  return MethodologicalAlignmentWorkflowDetailToJSONTyped(json, false);
}

export function MethodologicalAlignmentWorkflowDetailToJSONTyped(
  value?: MethodologicalAlignmentWorkflowDetail | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    run: WorkflowRunToJSON(value['run']),
    state: MethodologicalAlignmentStateToJSON(value['state']),
  };
}
