/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileDocumentOutput } from './FileDocumentOutput';
import {
  FileDocumentOutputFromJSON,
  FileDocumentOutputFromJSONTyped,
  FileDocumentOutputToJSON,
  FileDocumentOutputToJSONTyped,
} from './FileDocumentOutput';
import type { WorkflowError } from './WorkflowError';
import {
  WorkflowErrorFromJSON,
  WorkflowErrorFromJSONTyped,
  WorkflowErrorToJSON,
  WorkflowErrorToJSONTyped,
} from './WorkflowError';
import type { MethodologyComparisonResponseOutput } from './MethodologyComparisonResponseOutput';
import {
  MethodologyComparisonResponseOutputFromJSON,
  MethodologyComparisonResponseOutputFromJSONTyped,
  MethodologyComparisonResponseOutputToJSON,
  MethodologyComparisonResponseOutputToJSONTyped,
} from './MethodologyComparisonResponseOutput';

/**
 * State for the methodological alignment workflow
 * @export
 * @interface MethodologicalAlignmentState
 */
export interface MethodologicalAlignmentState {
  /**
   * Errors that occurred during the workflow execution.
   * @type {Array<WorkflowError>}
   * @memberof MethodologicalAlignmentState
   */
  errors?: Array<WorkflowError>;
  /**
   *
   * @type {string}
   * @memberof MethodologicalAlignmentState
   */
  type?: MethodologicalAlignmentStateTypeEnum;
  /**
   * The main source document
   * @type {FileDocumentOutput}
   * @memberof MethodologicalAlignmentState
   */
  file: FileDocumentOutput;
  /**
   *
   * @type {MethodologyComparisonResponseOutput}
   * @memberof MethodologicalAlignmentState
   */
  methodologyComparison?: MethodologyComparisonResponseOutput | null;
}

/**
 * @export
 */
export const MethodologicalAlignmentStateTypeEnum = {
  MethodologicalAlignment: 'methodological_alignment',
} as const;
export type MethodologicalAlignmentStateTypeEnum =
  (typeof MethodologicalAlignmentStateTypeEnum)[keyof typeof MethodologicalAlignmentStateTypeEnum];

/**
 * Check if a given object implements the MethodologicalAlignmentState interface.
 */
export function instanceOfMethodologicalAlignmentState(value: object): value is MethodologicalAlignmentState {
  if (!('file' in value) || value['file'] === undefined) return false;
  return true;
}

export function MethodologicalAlignmentStateFromJSON(json: any): MethodologicalAlignmentState {
  return MethodologicalAlignmentStateFromJSONTyped(json, false);
}

export function MethodologicalAlignmentStateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MethodologicalAlignmentState {
  if (json == null) {
    return json;
  }
  return {
    errors: json['errors'] == null ? undefined : (json['errors'] as Array<any>).map(WorkflowErrorFromJSON),
    type: json['type'] == null ? undefined : json['type'],
    file: FileDocumentOutputFromJSON(json['file']),
    methodologyComparison:
      json['methodology_comparison'] == null
        ? undefined
        : MethodologyComparisonResponseOutputFromJSON(json['methodology_comparison']),
  };
}

export function MethodologicalAlignmentStateToJSON(json: any): MethodologicalAlignmentState {
  return MethodologicalAlignmentStateToJSONTyped(json, false);
}

export function MethodologicalAlignmentStateToJSONTyped(
  value?: MethodologicalAlignmentState | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    errors: value['errors'] == null ? undefined : (value['errors'] as Array<any>).map(WorkflowErrorToJSON),
    type: value['type'],
    file: FileDocumentOutputToJSON(value['file']),
    methodology_comparison: MethodologyComparisonResponseOutputToJSON(value['methodologyComparison']),
  };
}
