/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Project } from './Project';
import { ProjectFromJSON, ProjectFromJSONTyped, ProjectToJSON, ProjectToJSONTyped } from './Project';
import type { WorkflowRun } from './WorkflowRun';
import {
  WorkflowRunFromJSON,
  WorkflowRunFromJSONTyped,
  WorkflowRunToJSON,
  WorkflowRunToJSONTyped,
} from './WorkflowRun';

/**
 *
 * @export
 * @interface ProjectListItem
 */
export interface ProjectListItem {
  /**
   * The project
   * @type {Project}
   * @memberof ProjectListItem
   */
  project: Project;
  /**
   * The workflow runs for the project
   * @type {Array<WorkflowRun>}
   * @memberof ProjectListItem
   */
  workflowRuns?: Array<WorkflowRun>;
}

/**
 * Check if a given object implements the ProjectListItem interface.
 */
export function instanceOfProjectListItem(value: object): value is ProjectListItem {
  if (!('project' in value) || value['project'] === undefined) return false;
  return true;
}

export function ProjectListItemFromJSON(json: any): ProjectListItem {
  return ProjectListItemFromJSONTyped(json, false);
}

export function ProjectListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectListItem {
  if (json == null) {
    return json;
  }
  return {
    project: ProjectFromJSON(json['project']),
    workflowRuns:
      json['workflow_runs'] == null ? undefined : (json['workflow_runs'] as Array<any>).map(WorkflowRunFromJSON),
  };
}

export function ProjectListItemToJSON(json: any): ProjectListItem {
  return ProjectListItemToJSONTyped(json, false);
}

export function ProjectListItemToJSONTyped(value?: ProjectListItem | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    project: ProjectToJSON(value['project']),
    workflow_runs:
      value['workflowRuns'] == null ? undefined : (value['workflowRuns'] as Array<any>).map(WorkflowRunToJSON),
  };
}
