/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const QualityLevel = {
  High: 'high',
  Medium: 'medium',
  Low: 'low',
} as const;
export type QualityLevel = (typeof QualityLevel)[keyof typeof QualityLevel];

export function instanceOfQualityLevel(value: any): boolean {
  for (const key in QualityLevel) {
    if (Object.prototype.hasOwnProperty.call(QualityLevel, key)) {
      if (QualityLevel[key as keyof typeof QualityLevel] === value) {
        return true;
      }
    }
  }
  return false;
}

export function QualityLevelFromJSON(json: any): QualityLevel {
  return QualityLevelFromJSONTyped(json, false);
}

export function QualityLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): QualityLevel {
  return json as QualityLevel;
}

export function QualityLevelToJSON(value?: QualityLevel | null): any {
  return value as any;
}

export function QualityLevelToJSONTyped(value: any, ignoreDiscriminator: boolean): QualityLevel {
  return value as QualityLevel;
}
