/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ReferenceType = {
  PeerReviewedPublication: 'peer_reviewed_publication',
  Preprint: 'preprint',
  Book: 'book',
  GovernmentNgoReport: 'government_ngo_report',
  DataSoftware: 'data_software',
  NewsMedia: 'news_media',
  Reference: 'reference',
  Webpage: 'webpage',
} as const;
export type ReferenceType = (typeof ReferenceType)[keyof typeof ReferenceType];

export function instanceOfReferenceType(value: any): boolean {
  for (const key in ReferenceType) {
    if (Object.prototype.hasOwnProperty.call(ReferenceType, key)) {
      if (ReferenceType[key as keyof typeof ReferenceType] === value) {
        return true;
      }
    }
  }
  return false;
}

export function ReferenceTypeFromJSON(json: any): ReferenceType {
  return ReferenceTypeFromJSONTyped(json, false);
}

export function ReferenceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceType {
  return json as ReferenceType;
}

export function ReferenceTypeToJSON(value?: ReferenceType | null): any {
  return value as any;
}

export function ReferenceTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ReferenceType {
  return value as ReferenceType;
}
