/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ReferenceAlignmentLevel = {
  Unverifiable: 'unverifiable',
  Supported: 'supported',
  PartiallySupported: 'partially_supported',
  Unsupported: 'unsupported',
} as const;
export type ReferenceAlignmentLevel = (typeof ReferenceAlignmentLevel)[keyof typeof ReferenceAlignmentLevel];

export function instanceOfReferenceAlignmentLevel(value: any): boolean {
  for (const key in ReferenceAlignmentLevel) {
    if (Object.prototype.hasOwnProperty.call(ReferenceAlignmentLevel, key)) {
      if (ReferenceAlignmentLevel[key as keyof typeof ReferenceAlignmentLevel] === value) {
        return true;
      }
    }
  }
  return false;
}

export function ReferenceAlignmentLevelFromJSON(json: any): ReferenceAlignmentLevel {
  return ReferenceAlignmentLevelFromJSONTyped(json, false);
}

export function ReferenceAlignmentLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceAlignmentLevel {
  return json as ReferenceAlignmentLevel;
}

export function ReferenceAlignmentLevelToJSON(value?: ReferenceAlignmentLevel | null): any {
  return value as any;
}

export function ReferenceAlignmentLevelToJSONTyped(value: any, ignoreDiscriminator: boolean): ReferenceAlignmentLevel {
  return value as ReferenceAlignmentLevel;
}
