/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferenceFetchItem } from './ReferenceFetchItem';
import {
  ReferenceFetchItemFromJSON,
  ReferenceFetchItemFromJSONTyped,
  ReferenceFetchItemToJSON,
  ReferenceFetchItemToJSONTyped,
} from './ReferenceFetchItem';

/**
 *
 * @export
 * @interface ReferenceFetcherAgentResponse
 */
export interface ReferenceFetcherAgentResponse {
  [key: string]: any | any;
  /**
   *
   * @type {ReferenceFetchItem}
   * @memberof ReferenceFetcherAgentResponse
   */
  reference: ReferenceFetchItem;
}

/**
 * Check if a given object implements the ReferenceFetcherAgentResponse interface.
 */
export function instanceOfReferenceFetcherAgentResponse(value: object): value is ReferenceFetcherAgentResponse {
  if (!('reference' in value) || value['reference'] === undefined) return false;
  return true;
}

export function ReferenceFetcherAgentResponseFromJSON(json: any): ReferenceFetcherAgentResponse {
  return ReferenceFetcherAgentResponseFromJSONTyped(json, false);
}

export function ReferenceFetcherAgentResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ReferenceFetcherAgentResponse {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    reference: ReferenceFetchItemFromJSON(json['reference']),
  };
}

export function ReferenceFetcherAgentResponseToJSON(json: any): ReferenceFetcherAgentResponse {
  return ReferenceFetcherAgentResponseToJSONTyped(json, false);
}

export function ReferenceFetcherAgentResponseToJSONTyped(
  value?: ReferenceFetcherAgentResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    ...value,
    reference: ReferenceFetchItemToJSON(value['reference']),
  };
}
