/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ReferenceDirection = {
  Supporting: 'supporting',
  Conflicting: 'conflicting',
  Mixed: 'mixed',
  Contextual: 'contextual',
} as const;
export type ReferenceDirection = (typeof ReferenceDirection)[keyof typeof ReferenceDirection];

export function instanceOfReferenceDirection(value: any): boolean {
  for (const key in ReferenceDirection) {
    if (Object.prototype.hasOwnProperty.call(ReferenceDirection, key)) {
      if (ReferenceDirection[key as keyof typeof ReferenceDirection] === value) {
        return true;
      }
    }
  }
  return false;
}

export function ReferenceDirectionFromJSON(json: any): ReferenceDirection {
  return ReferenceDirectionFromJSONTyped(json, false);
}

export function ReferenceDirectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceDirection {
  return json as ReferenceDirection;
}

export function ReferenceDirectionToJSON(value?: ReferenceDirection | null): any {
  return value as any;
}

export function ReferenceDirectionToJSONTyped(value: any, ignoreDiscriminator: boolean): ReferenceDirection {
  return value as ReferenceDirection;
}
