/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferenceDownloaderState } from './ReferenceDownloaderState';
import {
  ReferenceDownloaderStateFromJSON,
  ReferenceDownloaderStateFromJSONTyped,
  ReferenceDownloaderStateToJSON,
  ReferenceDownloaderStateToJSONTyped,
} from './ReferenceDownloaderState';
import type { WorkflowRun } from './WorkflowRun';
import {
  WorkflowRunFromJSON,
  WorkflowRunFromJSONTyped,
  WorkflowRunToJSON,
  WorkflowRunToJSONTyped,
} from './WorkflowRun';

/**
 *
 * @export
 * @interface ReferenceDownloaderWorkflowDetail
 */
export interface ReferenceDownloaderWorkflowDetail {
  /**
   *
   * @type {WorkflowRun}
   * @memberof ReferenceDownloaderWorkflowDetail
   */
  run: WorkflowRun;
  /**
   *
   * @type {ReferenceDownloaderState}
   * @memberof ReferenceDownloaderWorkflowDetail
   */
  state: ReferenceDownloaderState;
}

/**
 * Check if a given object implements the ReferenceDownloaderWorkflowDetail interface.
 */
export function instanceOfReferenceDownloaderWorkflowDetail(value: object): value is ReferenceDownloaderWorkflowDetail {
  if (!('run' in value) || value['run'] === undefined) return false;
  if (!('state' in value) || value['state'] === undefined) return false;
  return true;
}

export function ReferenceDownloaderWorkflowDetailFromJSON(json: any): ReferenceDownloaderWorkflowDetail {
  return ReferenceDownloaderWorkflowDetailFromJSONTyped(json, false);
}

export function ReferenceDownloaderWorkflowDetailFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ReferenceDownloaderWorkflowDetail {
  if (json == null) {
    return json;
  }
  return {
    run: WorkflowRunFromJSON(json['run']),
    state: ReferenceDownloaderStateFromJSON(json['state']),
  };
}

export function ReferenceDownloaderWorkflowDetailToJSON(json: any): ReferenceDownloaderWorkflowDetail {
  return ReferenceDownloaderWorkflowDetailToJSONTyped(json, false);
}

export function ReferenceDownloaderWorkflowDetailToJSONTyped(
  value?: ReferenceDownloaderWorkflowDetail | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    run: WorkflowRunToJSON(value['run']),
    state: ReferenceDownloaderStateToJSON(value['state']),
  };
}
