/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReferenceDownloaderWorkflowConfig } from './ReferenceDownloaderWorkflowConfig';
import {
  ReferenceDownloaderWorkflowConfigFromJSON,
  ReferenceDownloaderWorkflowConfigFromJSONTyped,
  ReferenceDownloaderWorkflowConfigToJSON,
  ReferenceDownloaderWorkflowConfigToJSONTyped,
} from './ReferenceDownloaderWorkflowConfig';
import type { WorkflowError } from './WorkflowError';
import {
  WorkflowErrorFromJSON,
  WorkflowErrorFromJSONTyped,
  WorkflowErrorToJSON,
  WorkflowErrorToJSONTyped,
} from './WorkflowError';
import type { ReferenceFetchItem } from './ReferenceFetchItem';
import {
  ReferenceFetchItemFromJSON,
  ReferenceFetchItemFromJSONTyped,
  ReferenceFetchItemToJSON,
  ReferenceFetchItemToJSONTyped,
} from './ReferenceFetchItem';

/**
 * State for the reference downloader workflow
 * @export
 * @interface ReferenceDownloaderState
 */
export interface ReferenceDownloaderState {
  /**
   * Errors that occurred during the workflow execution.
   * @type {Array<WorkflowError>}
   * @memberof ReferenceDownloaderState
   */
  errors?: Array<WorkflowError>;
  /**
   *
   * @type {string}
   * @memberof ReferenceDownloaderState
   */
  type?: ReferenceDownloaderStateTypeEnum;
  /**
   * The configuration for the workflow
   * @type {ReferenceDownloaderWorkflowConfig}
   * @memberof ReferenceDownloaderState
   */
  config: ReferenceDownloaderWorkflowConfig;
  /**
   *
   * @type {Array<ReferenceFetchItem>}
   * @memberof ReferenceDownloaderState
   */
  fetchedReferences?: Array<ReferenceFetchItem> | null;
  /**
   *
   * @type {Array<string | null>}
   * @memberof ReferenceDownloaderState
   */
  downloadedReferences?: Array<string | null> | null;
}

/**
 * @export
 */
export const ReferenceDownloaderStateTypeEnum = {
  ReferenceDownloader: 'reference_downloader',
} as const;
export type ReferenceDownloaderStateTypeEnum =
  (typeof ReferenceDownloaderStateTypeEnum)[keyof typeof ReferenceDownloaderStateTypeEnum];

/**
 * Check if a given object implements the ReferenceDownloaderState interface.
 */
export function instanceOfReferenceDownloaderState(value: object): value is ReferenceDownloaderState {
  if (!('config' in value) || value['config'] === undefined) return false;
  return true;
}

export function ReferenceDownloaderStateFromJSON(json: any): ReferenceDownloaderState {
  return ReferenceDownloaderStateFromJSONTyped(json, false);
}

export function ReferenceDownloaderStateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ReferenceDownloaderState {
  if (json == null) {
    return json;
  }
  return {
    errors: json['errors'] == null ? undefined : (json['errors'] as Array<any>).map(WorkflowErrorFromJSON),
    type: json['type'] == null ? undefined : json['type'],
    config: ReferenceDownloaderWorkflowConfigFromJSON(json['config']),
    fetchedReferences:
      json['fetched_references'] == null
        ? undefined
        : (json['fetched_references'] as Array<any>).map(ReferenceFetchItemFromJSON),
    downloadedReferences: json['downloaded_references'] == null ? undefined : json['downloaded_references'],
  };
}

export function ReferenceDownloaderStateToJSON(json: any): ReferenceDownloaderState {
  return ReferenceDownloaderStateToJSONTyped(json, false);
}

export function ReferenceDownloaderStateToJSONTyped(
  value?: ReferenceDownloaderState | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    errors: value['errors'] == null ? undefined : (value['errors'] as Array<any>).map(WorkflowErrorToJSON),
    type: value['type'],
    config: ReferenceDownloaderWorkflowConfigToJSON(value['config']),
    fetched_references:
      value['fetchedReferences'] == null
        ? undefined
        : (value['fetchedReferences'] as Array<any>).map(ReferenceFetchItemToJSON),
    downloaded_references: value['downloadedReferences'],
  };
}
