/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReportMetadata } from './ReportMetadata';
import {
  ReportMetadataFromJSON,
  ReportMetadataFromJSONTyped,
  ReportMetadataToJSON,
  ReportMetadataToJSONTyped,
} from './ReportMetadata';

/**
 *
 * @export
 * @interface ReportOutputInput
 */
export interface ReportOutputInput {
  /**
   * The markdown formatted report
   * @type {string}
   * @memberof ReportOutputInput
   */
  reportMarkdown: string;
  /**
   *
   * @type {ReportMetadata}
   * @memberof ReportOutputInput
   */
  reportMetadata: ReportMetadata;
}

/**
 * Check if a given object implements the ReportOutputInput interface.
 */
export function instanceOfReportOutputInput(value: object): value is ReportOutputInput {
  if (!('reportMarkdown' in value) || value['reportMarkdown'] === undefined) return false;
  if (!('reportMetadata' in value) || value['reportMetadata'] === undefined) return false;
  return true;
}

export function ReportOutputInputFromJSON(json: any): ReportOutputInput {
  return ReportOutputInputFromJSONTyped(json, false);
}

export function ReportOutputInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportOutputInput {
  if (json == null) {
    return json;
  }
  return {
    reportMarkdown: json['report_markdown'],
    reportMetadata: ReportMetadataFromJSON(json['report_metadata']),
  };
}

export function ReportOutputInputToJSON(json: any): ReportOutputInput {
  return ReportOutputInputToJSONTyped(json, false);
}

export function ReportOutputInputToJSONTyped(
  value?: ReportOutputInput | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    report_markdown: value['reportMarkdown'],
    report_metadata: ReportMetadataToJSON(value['reportMetadata']),
  };
}
