/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateType } from './UpdateType';
import { UpdateTypeFromJSON, UpdateTypeFromJSONTyped, UpdateTypeToJSON, UpdateTypeToJSONTyped } from './UpdateType';

/**
 *
 * @export
 * @interface ReportMetadata
 */
export interface ReportMetadata {
  /**
   * The type of update
   * @type {UpdateType}
   * @memberof ReportMetadata
   */
  updateType: UpdateType;
  /**
   * Newspaper-style title summarizing the changes (or lack of changes) suggested by the report
   * @type {string}
   * @memberof ReportMetadata
   */
  title: string;
  /**
   * A single sentence summary of the addendum report
   * @type {string}
   * @memberof ReportMetadata
   */
  sentenceSummary: string;
  /**
   * The date the report was generated in YYYY-MM-DD format
   * @type {string}
   * @memberof ReportMetadata
   */
  dateGenerated: string;
}

/**
 * Check if a given object implements the ReportMetadata interface.
 */
export function instanceOfReportMetadata(value: object): value is ReportMetadata {
  if (!('updateType' in value) || value['updateType'] === undefined) return false;
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('sentenceSummary' in value) || value['sentenceSummary'] === undefined) return false;
  if (!('dateGenerated' in value) || value['dateGenerated'] === undefined) return false;
  return true;
}

export function ReportMetadataFromJSON(json: any): ReportMetadata {
  return ReportMetadataFromJSONTyped(json, false);
}

export function ReportMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportMetadata {
  if (json == null) {
    return json;
  }
  return {
    updateType: UpdateTypeFromJSON(json['update_type']),
    title: json['title'],
    sentenceSummary: json['sentence_summary'],
    dateGenerated: json['date_generated'],
  };
}

export function ReportMetadataToJSON(json: any): ReportMetadata {
  return ReportMetadataToJSONTyped(json, false);
}

export function ReportMetadataToJSONTyped(value?: ReportMetadata | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    update_type: UpdateTypeToJSON(value['updateType']),
    title: value['title'],
    sentence_summary: value['sentenceSummary'],
    date_generated: value['dateGenerated'],
  };
}
