/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubstantiationWorkflowConfig } from './SubstantiationWorkflowConfig';
import {
  SubstantiationWorkflowConfigFromJSON,
  SubstantiationWorkflowConfigFromJSONTyped,
  SubstantiationWorkflowConfigToJSON,
  SubstantiationWorkflowConfigToJSONTyped,
} from './SubstantiationWorkflowConfig';

/**
 * Request model for re-running the analysis. Can be used to re-run a specific chunk or the entire analysis.
 * @export
 * @interface RerunAnalysisRequest
 */
export interface RerunAnalysisRequest {
  /**
   * The ID of the project to re-run
   * @type {string}
   * @memberof RerunAnalysisRequest
   */
  projectId: string;
  /**
   * Configuration for the re-run. Should include all the original configuration options, plus any overrides.
   * @type {SubstantiationWorkflowConfig}
   * @memberof RerunAnalysisRequest
   */
  config: SubstantiationWorkflowConfig;
}

/**
 * Check if a given object implements the RerunAnalysisRequest interface.
 */
export function instanceOfRerunAnalysisRequest(value: object): value is RerunAnalysisRequest {
  if (!('projectId' in value) || value['projectId'] === undefined) return false;
  if (!('config' in value) || value['config'] === undefined) return false;
  return true;
}

export function RerunAnalysisRequestFromJSON(json: any): RerunAnalysisRequest {
  return RerunAnalysisRequestFromJSONTyped(json, false);
}

export function RerunAnalysisRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RerunAnalysisRequest {
  if (json == null) {
    return json;
  }
  return {
    projectId: json['project_id'],
    config: SubstantiationWorkflowConfigFromJSON(json['config']),
  };
}

export function RerunAnalysisRequestToJSON(json: any): RerunAnalysisRequest {
  return RerunAnalysisRequestToJSONTyped(json, false);
}

export function RerunAnalysisRequestToJSONTyped(
  value?: RerunAnalysisRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    project_id: value['projectId'],
    config: SubstantiationWorkflowConfigToJSON(value['config']),
  };
}
