/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Information about a passage retrieved via RAG.
 * @export
 * @interface RetrievedPassageInfo
 */
export interface RetrievedPassageInfo {
  /**
   * The text content of the retrieved passage
   * @type {string}
   * @memberof RetrievedPassageInfo
   */
  content: string;
  /**
   * Name of the source file
   * @type {string}
   * @memberof RetrievedPassageInfo
   */
  sourceFile: string;
  /**
   * Cosine similarity score (0-1)
   * @type {number}
   * @memberof RetrievedPassageInfo
   */
  similarityScore: number;
  /**
   * Index of the chunk within the source
   * @type {number}
   * @memberof RetrievedPassageInfo
   */
  chunkIndex: number;
}

/**
 * Check if a given object implements the RetrievedPassageInfo interface.
 */
export function instanceOfRetrievedPassageInfo(value: object): value is RetrievedPassageInfo {
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('sourceFile' in value) || value['sourceFile'] === undefined) return false;
  if (!('similarityScore' in value) || value['similarityScore'] === undefined) return false;
  if (!('chunkIndex' in value) || value['chunkIndex'] === undefined) return false;
  return true;
}

export function RetrievedPassageInfoFromJSON(json: any): RetrievedPassageInfo {
  return RetrievedPassageInfoFromJSONTyped(json, false);
}

export function RetrievedPassageInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrievedPassageInfo {
  if (json == null) {
    return json;
  }
  return {
    content: json['content'],
    sourceFile: json['source_file'],
    similarityScore: json['similarity_score'],
    chunkIndex: json['chunk_index'],
  };
}

export function RetrievedPassageInfoToJSON(json: any): RetrievedPassageInfo {
  return RetrievedPassageInfoToJSONTyped(json, false);
}

export function RetrievedPassageInfoToJSONTyped(
  value?: RetrievedPassageInfo | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    content: value['content'],
    source_file: value['sourceFile'],
    similarity_score: value['similarityScore'],
    chunk_index: value['chunkIndex'],
  };
}
