/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for share link operations.
 * @export
 * @interface ShareLinkResponse
 */
export interface ShareLinkResponse {
  /**
   * The share token
   * @type {string}
   * @memberof ShareLinkResponse
   */
  token: string;
  /**
   * The full shareable URL
   * @type {string}
   * @memberof ShareLinkResponse
   */
  url: string;
  /**
   * Whether the share link is active
   * @type {boolean}
   * @memberof ShareLinkResponse
   */
  isActive: boolean;
}

/**
 * Check if a given object implements the ShareLinkResponse interface.
 */
export function instanceOfShareLinkResponse(value: object): value is ShareLinkResponse {
  if (!('token' in value) || value['token'] === undefined) return false;
  if (!('url' in value) || value['url'] === undefined) return false;
  if (!('isActive' in value) || value['isActive'] === undefined) return false;
  return true;
}

export function ShareLinkResponseFromJSON(json: any): ShareLinkResponse {
  return ShareLinkResponseFromJSONTyped(json, false);
}

export function ShareLinkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareLinkResponse {
  if (json == null) {
    return json;
  }
  return {
    token: json['token'],
    url: json['url'],
    isActive: json['is_active'],
  };
}

export function ShareLinkResponseToJSON(json: any): ShareLinkResponse {
  return ShareLinkResponseToJSONTyped(json, false);
}

export function ShareLinkResponseToJSONTyped(
  value?: ShareLinkResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    token: value['token'],
    url: value['url'],
    is_active: value['isActive'],
  };
}
