/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShareLinkResponse } from './ShareLinkResponse';
import {
  ShareLinkResponseFromJSON,
  ShareLinkResponseFromJSONTyped,
  ShareLinkResponseToJSON,
  ShareLinkResponseToJSONTyped,
} from './ShareLinkResponse';

/**
 * Response model for share status check.
 * @export
 * @interface ShareStatusResponse
 */
export interface ShareStatusResponse {
  /**
   * Whether sharing is enabled
   * @type {boolean}
   * @memberof ShareStatusResponse
   */
  enabled: boolean;
  /**
   *
   * @type {ShareLinkResponse}
   * @memberof ShareStatusResponse
   */
  shareLink?: ShareLinkResponse | null;
}

/**
 * Check if a given object implements the ShareStatusResponse interface.
 */
export function instanceOfShareStatusResponse(value: object): value is ShareStatusResponse {
  if (!('enabled' in value) || value['enabled'] === undefined) return false;
  return true;
}

export function ShareStatusResponseFromJSON(json: any): ShareStatusResponse {
  return ShareStatusResponseFromJSONTyped(json, false);
}

export function ShareStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareStatusResponse {
  if (json == null) {
    return json;
  }
  return {
    enabled: json['enabled'],
    shareLink: json['share_link'] == null ? undefined : ShareLinkResponseFromJSON(json['share_link']),
  };
}

export function ShareStatusResponseToJSON(json: any): ShareStatusResponse {
  return ShareStatusResponseToJSONTyped(json, false);
}

export function ShareStatusResponseToJSONTyped(
  value?: ShareStatusResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    enabled: value['enabled'],
    share_link: ShareLinkResponseToJSON(value['shareLink']),
  };
}
