/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SharedProjectInfo } from './SharedProjectInfo';
import {
  SharedProjectInfoFromJSON,
  SharedProjectInfoFromJSONTyped,
  SharedProjectInfoToJSON,
  SharedProjectInfoToJSONTyped,
} from './SharedProjectInfo';
import type { SharedWorkflowRun } from './SharedWorkflowRun';
import {
  SharedWorkflowRunFromJSON,
  SharedWorkflowRunFromJSONTyped,
  SharedWorkflowRunToJSON,
  SharedWorkflowRunToJSONTyped,
} from './SharedWorkflowRun';
import type { ClaimSubstantiatorStateSummary } from './ClaimSubstantiatorStateSummary';
import {
  ClaimSubstantiatorStateSummaryFromJSON,
  ClaimSubstantiatorStateSummaryFromJSONTyped,
  ClaimSubstantiatorStateSummaryToJSON,
  ClaimSubstantiatorStateSummaryToJSONTyped,
} from './ClaimSubstantiatorStateSummary';

/**
 * Response for a shared project with all necessary data.
 * @export
 * @interface SharedProjectResponse
 */
export interface SharedProjectResponse {
  /**
   *
   * @type {SharedProjectInfo}
   * @memberof SharedProjectResponse
   */
  project: SharedProjectInfo;
  /**
   *
   * @type {SharedWorkflowRun}
   * @memberof SharedProjectResponse
   */
  workflowRun?: SharedWorkflowRun | null;
  /**
   *
   * @type {ClaimSubstantiatorStateSummary}
   * @memberof SharedProjectResponse
   */
  state?: ClaimSubstantiatorStateSummary | null;
}

/**
 * Check if a given object implements the SharedProjectResponse interface.
 */
export function instanceOfSharedProjectResponse(value: object): value is SharedProjectResponse {
  if (!('project' in value) || value['project'] === undefined) return false;
  return true;
}

export function SharedProjectResponseFromJSON(json: any): SharedProjectResponse {
  return SharedProjectResponseFromJSONTyped(json, false);
}

export function SharedProjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharedProjectResponse {
  if (json == null) {
    return json;
  }
  return {
    project: SharedProjectInfoFromJSON(json['project']),
    workflowRun: json['workflow_run'] == null ? undefined : SharedWorkflowRunFromJSON(json['workflow_run']),
    state: json['state'] == null ? undefined : ClaimSubstantiatorStateSummaryFromJSON(json['state']),
  };
}

export function SharedProjectResponseToJSON(json: any): SharedProjectResponse {
  return SharedProjectResponseToJSONTyped(json, false);
}

export function SharedProjectResponseToJSONTyped(
  value?: SharedProjectResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    project: SharedProjectInfoToJSON(value['project']),
    workflow_run: SharedWorkflowRunToJSON(value['workflowRun']),
    state: ClaimSubstantiatorStateSummaryToJSON(value['state']),
  };
}
