/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Minimal workflow run info for shared view.
 * @export
 * @interface SharedWorkflowRun
 */
export interface SharedWorkflowRun {
  /**
   *
   * @type {string}
   * @memberof SharedWorkflowRun
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof SharedWorkflowRun
   */
  type: string;
  /**
   *
   * @type {string}
   * @memberof SharedWorkflowRun
   */
  status: string;
}

/**
 * Check if a given object implements the SharedWorkflowRun interface.
 */
export function instanceOfSharedWorkflowRun(value: object): value is SharedWorkflowRun {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('status' in value) || value['status'] === undefined) return false;
  return true;
}

export function SharedWorkflowRunFromJSON(json: any): SharedWorkflowRun {
  return SharedWorkflowRunFromJSONTyped(json, false);
}

export function SharedWorkflowRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharedWorkflowRun {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    type: json['type'],
    status: json['status'],
  };
}

export function SharedWorkflowRunToJSON(json: any): SharedWorkflowRun {
  return SharedWorkflowRunToJSONTyped(json, false);
}

export function SharedWorkflowRunToJSONTyped(
  value?: SharedWorkflowRun | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    type: value['type'],
    status: value['status'],
  };
}
