/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Direct URL to the located source, or null if no match was found
 * @export
 * @interface SourceUrl
 */
export interface SourceUrl {}

/**
 * Check if a given object implements the SourceUrl interface.
 */
export function instanceOfSourceUrl(value: object): value is SourceUrl {
  return true;
}

export function SourceUrlFromJSON(json: any): SourceUrl {
  return SourceUrlFromJSONTyped(json, false);
}

export function SourceUrlFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceUrl {
  return json;
}

export function SourceUrlToJSON(json: any): SourceUrl {
  return SourceUrlToJSONTyped(json, false);
}

export function SourceUrlToJSONTyped(value?: SourceUrl | null, ignoreDiscriminator: boolean = false): any {
  return value;
}
