/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response model for starting an async analysis workflow
 * @export
 * @interface StartAnalysisResponse
 */
export interface StartAnalysisResponse {
  /**
   *
   * @type {string}
   * @memberof StartAnalysisResponse
   */
  projectId: string;
  /**
   *
   * @type {string}
   * @memberof StartAnalysisResponse
   */
  message: string;
}

/**
 * Check if a given object implements the StartAnalysisResponse interface.
 */
export function instanceOfStartAnalysisResponse(value: object): value is StartAnalysisResponse {
  if (!('projectId' in value) || value['projectId'] === undefined) return false;
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function StartAnalysisResponseFromJSON(json: any): StartAnalysisResponse {
  return StartAnalysisResponseFromJSONTyped(json, false);
}

export function StartAnalysisResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartAnalysisResponse {
  if (json == null) {
    return json;
  }
  return {
    projectId: json['project_id'],
    message: json['message'],
  };
}

export function StartAnalysisResponseToJSON(json: any): StartAnalysisResponse {
  return StartAnalysisResponseToJSONTyped(json, false);
}

export function StartAnalysisResponseToJSONTyped(
  value?: StartAnalysisResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    project_id: value['projectId'],
    message: value['message'],
  };
}
