/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Defines the classification and metadata for a report update.
 * @export
 */
export const UpdateType = {
  NoUpdateNeeded: 'no_update_needed',
  MinorFactualUpdate: 'minor_factual_update',
  ModerateUpdate: 'moderate_update',
  MajorUpdateRequired: 'major_update_required',
  OutdatedOrInvalidated: 'outdated_or_invalidated',
} as const;
export type UpdateType = (typeof UpdateType)[keyof typeof UpdateType];

export function instanceOfUpdateType(value: any): boolean {
  for (const key in UpdateType) {
    if (Object.prototype.hasOwnProperty.call(UpdateType, key)) {
      if (UpdateType[key as keyof typeof UpdateType] === value) {
        return true;
      }
    }
  }
  return false;
}

export function UpdateTypeFromJSON(json: any): UpdateType {
  return UpdateTypeFromJSONTyped(json, false);
}

export function UpdateTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateType {
  return json as UpdateType;
}

export function UpdateTypeToJSON(value?: UpdateType | null): any {
  return value as any;
}

export function UpdateTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): UpdateType {
  return value as UpdateType;
}
