/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const WorkflowRunType = {
  ClaimSubstantiation: 'claim_substantiation',
  MethodologicalAlignment: 'methodological_alignment',
} as const;
export type WorkflowRunType = (typeof WorkflowRunType)[keyof typeof WorkflowRunType];

export function instanceOfWorkflowRunType(value: any): boolean {
  for (const key in WorkflowRunType) {
    if (Object.prototype.hasOwnProperty.call(WorkflowRunType, key)) {
      if (WorkflowRunType[key as keyof typeof WorkflowRunType] === value) {
        return true;
      }
    }
  }
  return false;
}

export function WorkflowRunTypeFromJSON(json: any): WorkflowRunType {
  return WorkflowRunTypeFromJSONTyped(json, false);
}

export function WorkflowRunTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowRunType {
  return json as WorkflowRunType;
}

export function WorkflowRunTypeToJSON(value?: WorkflowRunType | null): any {
  return value as any;
}

export function WorkflowRunTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): WorkflowRunType {
  return value as WorkflowRunType;
}
