/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error object for the overall workflow or specific chunks.
 * @export
 * @interface WorkflowError
 */
export interface WorkflowError {
  /**
   *
   * @type {number}
   * @memberof WorkflowError
   */
  chunkIndex: number | null;
  /**
   * The name of the task that caused the error.
   * @type {string}
   * @memberof WorkflowError
   */
  taskName: string;
  /**
   * The error message.
   * @type {string}
   * @memberof WorkflowError
   */
  error: string;
}

/**
 * Check if a given object implements the WorkflowError interface.
 */
export function instanceOfWorkflowError(value: object): value is WorkflowError {
  if (!('chunkIndex' in value) || value['chunkIndex'] === undefined) return false;
  if (!('taskName' in value) || value['taskName'] === undefined) return false;
  if (!('error' in value) || value['error'] === undefined) return false;
  return true;
}

export function WorkflowErrorFromJSON(json: any): WorkflowError {
  return WorkflowErrorFromJSONTyped(json, false);
}

export function WorkflowErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowError {
  if (json == null) {
    return json;
  }
  return {
    chunkIndex: json['chunk_index'],
    taskName: json['task_name'],
    error: json['error'],
  };
}

export function WorkflowErrorToJSON(json: any): WorkflowError {
  return WorkflowErrorToJSONTyped(json, false);
}

export function WorkflowErrorToJSONTyped(value?: WorkflowError | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    chunk_index: value['chunkIndex'],
    task_name: value['taskName'],
    error: value['error'],
  };
}
