/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClaimSubstantiatorStateSummary } from './ClaimSubstantiatorStateSummary';
import {
  ClaimSubstantiatorStateSummaryFromJSON,
  ClaimSubstantiatorStateSummaryFromJSONTyped,
  ClaimSubstantiatorStateSummaryToJSON,
  ClaimSubstantiatorStateSummaryToJSONTyped,
} from './ClaimSubstantiatorStateSummary';
import type { WorkflowRun } from './WorkflowRun';
import {
  WorkflowRunFromJSON,
  WorkflowRunFromJSONTyped,
  WorkflowRunToJSON,
  WorkflowRunToJSONTyped,
} from './WorkflowRun';

/**
 *
 * @export
 * @interface WorkflowRunDetailed
 */
export interface WorkflowRunDetailed {
  /**
   *
   * @type {WorkflowRun}
   * @memberof WorkflowRunDetailed
   */
  run: WorkflowRun;
  /**
   *
   * @type {ClaimSubstantiatorStateSummary}
   * @memberof WorkflowRunDetailed
   */
  state?: ClaimSubstantiatorStateSummary | null;
}

/**
 * Check if a given object implements the WorkflowRunDetailed interface.
 */
export function instanceOfWorkflowRunDetailed(value: object): value is WorkflowRunDetailed {
  if (!('run' in value) || value['run'] === undefined) return false;
  return true;
}

export function WorkflowRunDetailedFromJSON(json: any): WorkflowRunDetailed {
  return WorkflowRunDetailedFromJSONTyped(json, false);
}

export function WorkflowRunDetailedFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowRunDetailed {
  if (json == null) {
    return json;
  }
  return {
    run: WorkflowRunFromJSON(json['run']),
    state: json['state'] == null ? undefined : ClaimSubstantiatorStateSummaryFromJSON(json['state']),
  };
}

export function WorkflowRunDetailedToJSON(json: any): WorkflowRunDetailed {
  return WorkflowRunDetailedToJSONTyped(json, false);
}

export function WorkflowRunDetailedToJSONTyped(
  value?: WorkflowRunDetailed | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    run: WorkflowRunToJSON(value['run']),
    state: ClaimSubstantiatorStateSummaryToJSON(value['state']),
  };
}
