/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const WorkflowRunStatus = {
  Pending: 'pending',
  Running: 'running',
  Completed: 'completed',
} as const;
export type WorkflowRunStatus = (typeof WorkflowRunStatus)[keyof typeof WorkflowRunStatus];

export function instanceOfWorkflowRunStatus(value: any): boolean {
  for (const key in WorkflowRunStatus) {
    if (Object.prototype.hasOwnProperty.call(WorkflowRunStatus, key)) {
      if (WorkflowRunStatus[key as keyof typeof WorkflowRunStatus] === value) {
        return true;
      }
    }
  }
  return false;
}

export function WorkflowRunStatusFromJSON(json: any): WorkflowRunStatus {
  return WorkflowRunStatusFromJSONTyped(json, false);
}

export function WorkflowRunStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowRunStatus {
  return json as WorkflowRunStatus;
}

export function WorkflowRunStatusToJSON(value?: WorkflowRunStatus | null): any {
  return value as any;
}

export function WorkflowRunStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): WorkflowRunStatus {
  return value as WorkflowRunStatus;
}
