"""switches to explicitely listing tools

Revision ID: 79eb938381a8
Revises: e8cd4f1f7766
Create Date: 2025-09-18 01:06:10.833732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79eb938381a8'
down_revision: Union[str, None] = 'e8cd4f1f7766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('tools', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('agents', 'disallowed_tools')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('disallowed_tools', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=True))
    op.drop_column('agents', 'tools')
    # ### end Alembic commands ###
