"""add_user_connections

Revision ID: c6b3cc257d3c
Revises: 1e1b703e2340
Create Date: 2025-11-10 14:25:59.590419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c6b3cc257d3c'
down_revision: Union[str, None] = '1e1b703e2340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_feedback_entity_path'), table_name='feedback', postgresql_using='gin')
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_foreign_key(None, 'feedback', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('workflow_runs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'workflow_runs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_runs', type_='foreignkey')
    op.drop_column('workflow_runs', 'user_id')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.create_index(op.f('ix_feedback_entity_path'), 'feedback', ['entity_path'], unique=False, postgresql_using='gin')
    op.drop_column('feedback', 'user_id')
    # ### end Alembic commands ###
