// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type {
  DeleteFeedbackApiFeedbackFeedbackIdDeleteData,
  DeleteFeedbackApiFeedbackFeedbackIdDeleteErrors,
  DeleteFeedbackApiFeedbackFeedbackIdDeleteResponses,
  DeleteProjectEndpointApiProjectProjectIdDeleteData,
  DeleteProjectEndpointApiProjectProjectIdDeleteErrors,
  DeleteProjectEndpointApiProjectProjectIdDeleteResponses,
  DisableProjectSharingApiProjectsProjectIdShareDisablePostData,
  DisableProjectSharingApiProjectsProjectIdShareDisablePostErrors,
  DisableProjectSharingApiProjectsProjectIdShareDisablePostResponses,
  DownloadFileApiFilesDownloadFileIdGetData,
  DownloadFileApiFilesDownloadFileIdGetErrors,
  DownloadFileApiFilesDownloadFileIdGetResponses,
  DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetData,
  DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetErrors,
  DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetResponses,
  EnableProjectSharingApiProjectsProjectIdShareEnablePostData,
  EnableProjectSharingApiProjectsProjectIdShareEnablePostErrors,
  EnableProjectSharingApiProjectsProjectIdShareEnablePostResponses,
  GenerateChunkEvalPackageApiGenerateChunkEvalPackagePostData,
  GenerateChunkEvalPackageApiGenerateChunkEvalPackagePostErrors,
  GenerateChunkEvalPackageApiGenerateChunkEvalPackagePostResponses,
  GenerateEvalPackageApiGenerateEvalPackagePostData,
  GenerateEvalPackageApiGenerateEvalPackagePostErrors,
  GenerateEvalPackageApiGenerateEvalPackagePostResponses,
  GetChunkDetailsEndpointApiWorkflowRunWorkflowRunIdChunkChunkIndexGetData,
  GetChunkDetailsEndpointApiWorkflowRunWorkflowRunIdChunkChunkIndexGetErrors,
  GetChunkDetailsEndpointApiWorkflowRunWorkflowRunIdChunkChunkIndexGetResponses,
  GetFeedbackApiFeedbackGetData,
  GetFeedbackApiFeedbackGetErrors,
  GetFeedbackApiFeedbackGetResponses,
  GetPageImageApiWorkflowRunsWorkflowRunIdPagesPageNumGetData,
  GetPageImageApiWorkflowRunsWorkflowRunIdPagesPageNumGetErrors,
  GetPageImageApiWorkflowRunsWorkflowRunIdPagesPageNumGetResponses,
  GetProjectEndpointApiProjectProjectIdGetData,
  GetProjectEndpointApiProjectProjectIdGetErrors,
  GetProjectEndpointApiProjectProjectIdGetResponses,
  GetProjectShareStatusApiProjectsProjectIdShareGetData,
  GetProjectShareStatusApiProjectsProjectIdShareGetErrors,
  GetProjectShareStatusApiProjectsProjectIdShareGetResponses,
  GetSharedResourceApiPublicShareTokenGetData,
  GetSharedResourceApiPublicShareTokenGetErrors,
  GetSharedResourceApiPublicShareTokenGetResponses,
  GetSupportedAgentsApiSupportedAgentsGetData,
  GetSupportedAgentsApiSupportedAgentsGetResponses,
  GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetData,
  GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetErrors,
  GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetResponses,
  GetWorkflowStateApiWorkflowsWorkflowRunIdGetData,
  GetWorkflowStateApiWorkflowsWorkflowRunIdGetErrors,
  GetWorkflowStateApiWorkflowsWorkflowRunIdGetResponses,
  ListProjectsEndpointApiProjectsGetData,
  ListProjectsEndpointApiProjectsGetResponses,
  ReadHealthApiHealthGetData,
  ReadHealthApiHealthGetResponses,
  RerunAnalysisEndpointApiRerunAnalysisPostData,
  RerunAnalysisEndpointApiRerunAnalysisPostErrors,
  RerunAnalysisEndpointApiRerunAnalysisPostResponses,
  StartAnalysisApiStartAnalysisPostData,
  StartAnalysisApiStartAnalysisPostErrors,
  StartAnalysisApiStartAnalysisPostResponses,
  StartWorkflowApiWorkflowsStartPostData,
  StartWorkflowApiWorkflowsStartPostErrors,
  StartWorkflowApiWorkflowsStartPostResponses,
  SubmitFeedbackApiFeedbackPostData,
  SubmitFeedbackApiFeedbackPostErrors,
  SubmitFeedbackApiFeedbackPostResponses,
  UpdateProjectEndpointApiProjectProjectIdPatchData,
  UpdateProjectEndpointApiProjectProjectIdPatchErrors,
  UpdateProjectEndpointApiProjectProjectIdPatchResponses,
} from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Read Health
 *
 * Health check endpoint
 */
export const readHealthApiHealthGet = <ThrowOnError extends boolean = true>(
  options?: Options<ReadHealthApiHealthGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ReadHealthApiHealthGetResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/health',
    ...options,
  });

/**
 * Get Supported Agents
 *
 * Get list of supported agent types for chunk re-evaluation.
 *
 * Returns:
 * List of AgentInfo objects
 */
export const getSupportedAgentsApiSupportedAgentsGet = <ThrowOnError extends boolean = true>(
  options?: Options<GetSupportedAgentsApiSupportedAgentsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetSupportedAgentsApiSupportedAgentsGetResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/supported-agents',
    ...options,
  });

/**
 * Start Analysis
 *
 * Start claim substantiation analysis - returns workflow_run_id immediately.
 *
 * This endpoint:
 * 1. Creates a project for the analysis
 * 2. Saves uploaded files to database with file metadata
 * 3. Creates file document references (without markdown conversion)
 * 4. Returns immediately with project_id
 * 5. Starts the analysis workflow in the background (markdown conversion happens here)
 *
 * The client can poll /api/project/{project_id} to check progress.
 *
 * Args:
 * background_tasks: FastAPI background tasks
 * main_document: The main document to analyze for claims
 * supporting_documents: Optional supporting documents for substantiation
 * config: Workflow configuration built from form fields
 *
 * Returns:
 * project_id to track the analysis
 */
export const startAnalysisApiStartAnalysisPost = <ThrowOnError extends boolean = true>(
  options: Options<StartAnalysisApiStartAnalysisPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    StartAnalysisApiStartAnalysisPostResponses,
    StartAnalysisApiStartAnalysisPostErrors,
    ThrowOnError,
    'data'
  >({
    ...formDataBodySerializer,
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/start-analysis',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Rerun Analysis Endpoint
 *
 * Re-evaluate a specific chunk with selected agents using unified LangGraph workflow.
 *
 * Args:
 * request: Contains chunk index, agents to run, and original state
 *
 * Returns:
 * Updated results for the specified chunk
 */
export const rerunAnalysisEndpointApiRerunAnalysisPost = <ThrowOnError extends boolean = true>(
  options: Options<RerunAnalysisEndpointApiRerunAnalysisPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RerunAnalysisEndpointApiRerunAnalysisPostResponses,
    RerunAnalysisEndpointApiRerunAnalysisPostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/rerun-analysis',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Generate Eval Package
 *
 * Generate complete eval test package as downloadable zip.
 *
 * Args:
 * request: Contains analysis results and metadata for test generation
 *
 * Returns:
 * Zip file containing YAML test files and data files
 */
export const generateEvalPackageApiGenerateEvalPackagePost = <ThrowOnError extends boolean = true>(
  options: Options<GenerateEvalPackageApiGenerateEvalPackagePostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    GenerateEvalPackageApiGenerateEvalPackagePostResponses,
    GenerateEvalPackageApiGenerateEvalPackagePostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    url: '/api/generate-eval-package',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Generate Chunk Eval Package
 *
 * Generate eval test package for a specific chunk with selected agents.
 * Only includes files required by the selected agents.
 *
 * Args:
 * request: Contains analysis results, chunk index, selected agents, and metadata
 *
 * Returns:
 * Optimized zip file containing only necessary YAML test files and data files
 */
export const generateChunkEvalPackageApiGenerateChunkEvalPackagePost = <ThrowOnError extends boolean = true>(
  options: Options<GenerateChunkEvalPackageApiGenerateChunkEvalPackagePostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    GenerateChunkEvalPackageApiGenerateChunkEvalPackagePostResponses,
    GenerateChunkEvalPackageApiGenerateChunkEvalPackagePostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    url: '/api/generate-chunk-eval-package',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Start Workflow
 *
 * Start a workflow
 */
export const startWorkflowApiWorkflowsStartPost = <ThrowOnError extends boolean = true>(
  options: Options<StartWorkflowApiWorkflowsStartPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    StartWorkflowApiWorkflowsStartPostResponses,
    StartWorkflowApiWorkflowsStartPostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/workflows/start',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Workflow State
 *
 * Get the state of a workflow
 */
export const getWorkflowStateApiWorkflowsWorkflowRunIdGet = <ThrowOnError extends boolean = true>(
  options: Options<GetWorkflowStateApiWorkflowsWorkflowRunIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetWorkflowStateApiWorkflowsWorkflowRunIdGetResponses,
    GetWorkflowStateApiWorkflowsWorkflowRunIdGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/workflows/{workflow_run_id}',
    ...options,
  });

/**
 * Get Chunk Details Endpoint
 *
 * Get detailed analysis for a specific chunk (lazy loading)
 */
export const getChunkDetailsEndpointApiWorkflowRunWorkflowRunIdChunkChunkIndexGet = <
  ThrowOnError extends boolean = true,
>(
  options: Options<GetChunkDetailsEndpointApiWorkflowRunWorkflowRunIdChunkChunkIndexGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetChunkDetailsEndpointApiWorkflowRunWorkflowRunIdChunkChunkIndexGetResponses,
    GetChunkDetailsEndpointApiWorkflowRunWorkflowRunIdChunkChunkIndexGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    url: '/api/workflow-run/{workflow_run_id}/chunk/{chunk_index}',
    ...options,
  });

/**
 * Get Page Image
 *
 * Serve Docling page images for a workflow run.
 *
 * Allows access if user is authenticated OR if the project has sharing enabled.
 *
 * Args:
 * workflow_run_id: The workflow run ID
 * page_num: The page number (e.g., 0, 1, 2, etc.)
 *
 * Returns:
 * The image file for the specified page (PNG, JPEG, WEBP, etc.)
 */
export const getPageImageApiWorkflowRunsWorkflowRunIdPagesPageNumGet = <ThrowOnError extends boolean = true>(
  options: Options<GetPageImageApiWorkflowRunsWorkflowRunIdPagesPageNumGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetPageImageApiWorkflowRunsWorkflowRunIdPagesPageNumGetResponses,
    GetPageImageApiWorkflowRunsWorkflowRunIdPagesPageNumGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/workflow-runs/{workflow_run_id}/pages/{page_num}',
    ...options,
  });

/**
 * Download File
 *
 * Download a file by ID with access control.
 *
 * This endpoint verifies that the authenticated user has access to the file
 * by checking if they own the project that the file belongs to.
 *
 * Args:
 * file_id: UUID of the file to download
 * current_user: Authenticated user from JWT token
 *
 * Returns:
 * FileResponse with the file contents
 *
 * Raises:
 * HTTPException: 400 for invalid file ID, 404 if file not found, 403 if access denied
 */
export const downloadFileApiFilesDownloadFileIdGet = <ThrowOnError extends boolean = true>(
  options: Options<DownloadFileApiFilesDownloadFileIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    DownloadFileApiFilesDownloadFileIdGetResponses,
    DownloadFileApiFilesDownloadFileIdGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/files/download/{file_id}',
    ...options,
  });

/**
 * Get Feedback
 *
 * Get feedback for a specific entity
 *
 * Example: GET /api/feedback?workflow_run_id=xxx&entity_path={"chunk_index":0,"claim_index":1}
 */
export const getFeedbackApiFeedbackGet = <ThrowOnError extends boolean = true>(
  options: Options<GetFeedbackApiFeedbackGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetFeedbackApiFeedbackGetResponses,
    GetFeedbackApiFeedbackGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/feedback',
    ...options,
  });

/**
 * Submit Feedback
 *
 * Submit or update feedback for any entity
 */
export const submitFeedbackApiFeedbackPost = <ThrowOnError extends boolean = true>(
  options: Options<SubmitFeedbackApiFeedbackPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    SubmitFeedbackApiFeedbackPostResponses,
    SubmitFeedbackApiFeedbackPostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/feedback',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Workflow Feedback
 *
 * Get all feedback for a workflow run
 */
export const getWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGet = <ThrowOnError extends boolean = true>(
  options: Options<GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetResponses,
    GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/feedback/workflow/{workflow_run_id}',
    ...options,
  });

/**
 * Delete Feedback
 *
 * Delete feedback by ID
 */
export const deleteFeedbackApiFeedbackFeedbackIdDelete = <ThrowOnError extends boolean = true>(
  options: Options<DeleteFeedbackApiFeedbackFeedbackIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteFeedbackApiFeedbackFeedbackIdDeleteResponses,
    DeleteFeedbackApiFeedbackFeedbackIdDeleteErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/feedback/{feedback_id}',
    ...options,
  });

/**
 * List Projects Endpoint
 *
 * List all projects for the current user
 */
export const listProjectsEndpointApiProjectsGet = <ThrowOnError extends boolean = true>(
  options?: Options<ListProjectsEndpointApiProjectsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListProjectsEndpointApiProjectsGetResponses, unknown, ThrowOnError, 'data'>({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/projects',
    ...options,
  });

/**
 * Delete Project Endpoint
 *
 * Delete a project and all associated results
 */
export const deleteProjectEndpointApiProjectProjectIdDelete = <ThrowOnError extends boolean = true>(
  options: Options<DeleteProjectEndpointApiProjectProjectIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteProjectEndpointApiProjectProjectIdDeleteResponses,
    DeleteProjectEndpointApiProjectProjectIdDeleteErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/project/{project_id}',
    ...options,
  });

/**
 * Get Project Endpoint
 *
 * Get a project by ID
 */
export const getProjectEndpointApiProjectProjectIdGet = <ThrowOnError extends boolean = true>(
  options: Options<GetProjectEndpointApiProjectProjectIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetProjectEndpointApiProjectProjectIdGetResponses,
    GetProjectEndpointApiProjectProjectIdGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/project/{project_id}',
    ...options,
  });

/**
 * Update Project Endpoint
 *
 * Update a project with the provided fields
 */
export const updateProjectEndpointApiProjectProjectIdPatch = <ThrowOnError extends boolean = true>(
  options: Options<UpdateProjectEndpointApiProjectProjectIdPatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateProjectEndpointApiProjectProjectIdPatchResponses,
    UpdateProjectEndpointApiProjectProjectIdPatchErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/project/{project_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Download Project Docx
 *
 * Download DOCX file for project - reviewed version if available, otherwise original
 */
export const downloadProjectDocxApiProjectsProjectIdDocxDownloadGet = <ThrowOnError extends boolean = true>(
  options: Options<DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetResponses,
    DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/projects/{project_id}/docx/download',
    ...options,
  });

/**
 * Get Project Share Status
 *
 * Get the sharing status for a project.
 */
export const getProjectShareStatusApiProjectsProjectIdShareGet = <ThrowOnError extends boolean = true>(
  options: Options<GetProjectShareStatusApiProjectsProjectIdShareGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetProjectShareStatusApiProjectsProjectIdShareGetResponses,
    GetProjectShareStatusApiProjectsProjectIdShareGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/projects/{project_id}/share',
    ...options,
  });

/**
 * Enable Project Sharing
 *
 * Enable sharing for a project (creates a share link if none exists).
 */
export const enableProjectSharingApiProjectsProjectIdShareEnablePost = <ThrowOnError extends boolean = true>(
  options: Options<EnableProjectSharingApiProjectsProjectIdShareEnablePostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    EnableProjectSharingApiProjectsProjectIdShareEnablePostResponses,
    EnableProjectSharingApiProjectsProjectIdShareEnablePostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/projects/{project_id}/share/enable',
    ...options,
  });

/**
 * Disable Project Sharing
 *
 * Disable sharing for a project (deactivates the share link).
 */
export const disableProjectSharingApiProjectsProjectIdShareDisablePost = <ThrowOnError extends boolean = true>(
  options: Options<DisableProjectSharingApiProjectsProjectIdShareDisablePostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    DisableProjectSharingApiProjectsProjectIdShareDisablePostResponses,
    DisableProjectSharingApiProjectsProjectIdShareDisablePostErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/projects/{project_id}/share/disable',
    ...options,
  });

/**
 * Get Shared Resource
 *
 * Access a shared resource by token.
 *
 * This endpoint does not require authentication - the token IS the auth.
 * Returns project info and workflow state in a single call.
 */
export const getSharedResourceApiPublicShareTokenGet = <ThrowOnError extends boolean = true>(
  options: Options<GetSharedResourceApiPublicShareTokenGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSharedResourceApiPublicShareTokenGetResponses,
    GetSharedResourceApiPublicShareTokenGetErrors,
    ThrowOnError,
    'data'
  >({
    responseStyle: 'data',
    url: '/api/public/share/{token}',
    ...options,
  });
