// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetProjectEndpointApiProjectProjectIdGetResponse,
  GetSharedResourceApiPublicShareTokenGetResponse,
  GetWorkflowStateApiWorkflowsWorkflowRunIdGetResponse,
  ListProjectsEndpointApiProjectsGetResponse,
  UpdateProjectEndpointApiProjectProjectIdPatchResponse,
} from './types.gen';

const workflowRunDetailSchemaResponseTransformer = (data: any) => {
  data.run = workflowRunSchemaResponseTransformer(data.run);
  return data;
};

const workflowRunSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.last_updated_at = new Date(data.last_updated_at);
  return data;
};

export const getWorkflowStateApiWorkflowsWorkflowRunIdGetResponseTransformer = async (
  data: any,
): Promise<GetWorkflowStateApiWorkflowsWorkflowRunIdGetResponse> => {
  data = workflowRunDetailSchemaResponseTransformer(data);
  return data;
};

const projectListItemSchemaResponseTransformer = (data: any) => {
  data.project = projectSchemaResponseTransformer(data.project);
  if (data.workflow_runs) {
    data.workflow_runs = data.workflow_runs.map((item: any) => workflowRunSchemaResponseTransformer(item));
  }
  return data;
};

const projectSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.last_updated_at = new Date(data.last_updated_at);
  return data;
};

export const listProjectsEndpointApiProjectsGetResponseTransformer = async (
  data: any,
): Promise<ListProjectsEndpointApiProjectsGetResponse> => {
  data = data.map((item: any) => projectListItemSchemaResponseTransformer(item));
  return data;
};

const projectDetailedSchemaResponseTransformer = (data: any) => {
  data.project = projectSchemaResponseTransformer(data.project);
  if (data.workflow_runs) {
    data.workflow_runs = data.workflow_runs.map((item: any) => workflowRunSchemaResponseTransformer(item));
  }
  return data;
};

export const getProjectEndpointApiProjectProjectIdGetResponseTransformer = async (
  data: any,
): Promise<GetProjectEndpointApiProjectProjectIdGetResponse> => {
  data = projectDetailedSchemaResponseTransformer(data);
  return data;
};

export const updateProjectEndpointApiProjectProjectIdPatchResponseTransformer = async (
  data: any,
): Promise<UpdateProjectEndpointApiProjectProjectIdPatchResponse> => {
  data = projectSchemaResponseTransformer(data);
  return data;
};

const sharedProjectResponseSchemaResponseTransformer = (data: any) => {
  data.project = sharedProjectInfoSchemaResponseTransformer(data.project);
  if (data.state) {
    data.state = claimSubstantiatorStateSummarySchemaResponseTransformer(data.state);
  }
  return data;
};

const sharedProjectInfoSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

const claimSubstantiatorStateSummarySchemaResponseTransformer = (data: any) => {
  data.config = substantiationWorkflowConfigSchemaResponseTransformer(data.config);
  return data;
};

const substantiationWorkflowConfigSchemaResponseTransformer = (data: any) => {
  if (data.document_publication_date) {
    data.document_publication_date = new Date(data.document_publication_date);
  }
  return data;
};

export const getSharedResourceApiPublicShareTokenGetResponseTransformer = async (
  data: any,
): Promise<GetSharedResourceApiPublicShareTokenGetResponse> => {
  data = sharedProjectResponseSchemaResponseTransformer(data);
  return data;
};
