// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AgentInfo
 *
 * Information about a registered agent
 */
export type AgentInfo = {
  /**
   * Function Name
   */
  function_name: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
};

/**
 * BBox
 *
 * Docling bounding box format (bottom-left origin, PDF standard)
 */
export type BBox = {
  /**
   * L
   */
  l: number;
  /**
   * B
   */
  b: number;
  /**
   * R
   */
  r: number;
  /**
   * T
   */
  t: number;
};

/**
 * BibliographyFieldValidation
 */
export type BibliographyFieldValidation = {
  /**
   * Category of the reference.
   */
  category: FieldCategory;
  /**
   * Current Value
   *
   * Current value of the reference.
   */
  current_value: string;
  /**
   * Suggested Value
   *
   * Suggested value of the reference.
   */
  suggested_value: string;
  /**
   * Problem type of the reference.
   */
  problem_type: FieldProblemType;
};

/**
 * BibliographyItem
 */
export type BibliographyItem = {
  /**
   * Text
   *
   * The text of the bibliographic item
   */
  text: string;
  /**
   * Has Associated Supporting Document
   *
   * A boolean value indicating whether the bibliographic item has an associated supporting document provided by the user
   */
  has_associated_supporting_document: boolean;
  /**
   * Index Of Associated Supporting Document
   *
   * If the bibliographic item has an associated supporting document, this will be the index of the supporting document in the list of supporting documents provided by the user (index starts at 1), otherwise it will be -1.
   */
  index_of_associated_supporting_document: number;
  /**
   * Name Of Associated Supporting Document
   *
   * If the bibliographic item has an associated supporting document, this will be the name of the supporting document, otherwise it will be an empty string.
   */
  name_of_associated_supporting_document: string;
};

/**
 * BibliographyItemValidation
 */
export type BibliographyItemValidationInput = {
  /**
   * Original bibliographic item text.
   */
  original_reference: BibliographyItem;
  /**
   * Valid Reference
   *
   * Whether the original reference is valid.
   */
  valid_reference: boolean;
  /**
   * Bibliography Field Validations
   *
   * List of reference field validations.
   */
  bibliography_field_validations: Array<BibliographyFieldValidation>;
  /**
   * Suggested Action
   *
   * Suggested action to take if the reference is not valid. A summary of the suggested changes to make the reference valid. If the reference is valid, return 'No changes needed'.
   */
  suggested_action: string;
  /**
   * Url
   *
   * Found URL for the reference.
   */
  url: string;
};

/**
 * BibliographyItemValidation
 */
export type BibliographyItemValidationOutput = {
  /**
   * Original bibliographic item text.
   */
  original_reference: BibliographyItem;
  /**
   * Valid Reference
   *
   * Whether the original reference is valid.
   */
  valid_reference: boolean;
  /**
   * Bibliography Field Validations
   *
   * List of reference field validations.
   */
  bibliography_field_validations: Array<BibliographyFieldValidation>;
  /**
   * Suggested Action
   *
   * Suggested action to take if the reference is not valid. A summary of the suggested changes to make the reference valid. If the reference is valid, return 'No changes needed'.
   */
  suggested_action: string;
  /**
   * Url
   *
   * Found URL for the reference.
   */
  url: string;
};

/**
 * Body_create_project_endpoint_api_projects_post
 */
export type BodyCreateProjectEndpointApiProjectsPost = {
  /**
   * Title
   */
  title: string;
  /**
   * Main Document
   */
  main_document: Blob | File;
};

/**
 * Body_start_analysis_api_start_analysis_post
 */
export type BodyStartAnalysisApiStartAnalysisPost = {
  /**
   * Main Document
   */
  main_document: Blob | File;
  /**
   * Supporting Documents
   */
  supporting_documents?: Array<Blob | File> | null;
  /**
   * Use Toulmin
   */
  use_toulmin?: boolean;
  /**
   * Run Literature Review
   */
  run_literature_review?: boolean;
  /**
   * Run Suggest Citations
   */
  run_suggest_citations?: boolean;
  /**
   * Use Rag
   */
  use_rag?: boolean;
  /**
   * Run Live Reports
   */
  run_live_reports?: boolean;
  /**
   * Run Reference Validation
   */
  run_reference_validation?: boolean;
  /**
   * Domain
   */
  domain?: string | null;
  /**
   * Target Audience
   */
  target_audience?: string | null;
  /**
   * Target Chunk Indices
   */
  target_chunk_indices?: string | null;
  /**
   * Document Publication Date
   */
  document_publication_date?: string | null;
  /**
   * Agents To Run
   */
  agents_to_run?: string | null;
  /**
   * Session Id
   */
  session_id?: string | null;
  /**
   * Openai Api Key
   */
  openai_api_key?: string | null;
};

/**
 * ChunkEvalPackageRequest
 */
export type ChunkEvalPackageRequest = {
  results: ClaimSubstantiatorStateInput;
  /**
   * Chunk Index
   */
  chunk_index: number;
  /**
   * Selected Agents
   */
  selected_agents: Array<string>;
  /**
   * Test Name
   */
  test_name?: string;
  /**
   * Description
   */
  description?: string;
};

/**
 * ChunkToItems
 *
 * Mapping from chunk indices to document items/regions
 *
 * Keys are string chunk indices, values are lists of regions
 */
export type ChunkToItemsInput = {
  /**
   * Mapping
   *
   * Maps chunk_index (as string) to list of regions
   */
  mapping?: {
    [key: string]: Array<DoclingRegion>;
  };
};

/**
 * ChunkToItems
 *
 * Mapping from chunk indices to document items/regions
 *
 * Keys are string chunk indices, values are lists of regions
 */
export type ChunkToItemsOutput = {
  /**
   * Mapping
   *
   * Maps chunk_index (as string) to list of regions
   */
  mapping?: {
    [key: string]: Array<DoclingRegion>;
  };
};

/**
 * Citation
 */
export type Citation = {
  /**
   * Text
   *
   * The text of the citation or footnote mark, e.g., [1] or (Doe, et al., 2025), a url, etc. The bibliography/footnote itself is not a citation.
   */
  text: string;
  /**
   * The type of the citation. This should be a value from the CitationType enum.
   */
  type: CitationType;
  /**
   * Format
   *
   * The format of the citation or footnote mark, e.g., [number] or (Name, et al., Year), url, etc.
   */
  format: string;
  /**
   * Needs Bibliography
   *
   * A boolean value indicating whether the citation refers to a bibliography entry or footnote in the document so it expected to have an associated bibliography entry or footnote
   */
  needs_bibliography: boolean;
  /**
   * Associated Bibliography
   *
   * If the document includes a bibliography entry related to this citation, this will be an exact copy of that bibliography entry (do not include the entry number if there is one, just the full context of the bibliography entry), otherwise it will be an empty string.
   */
  associated_bibliography: string;
  /**
   * Index Of Associated Bibliography
   *
   * The index of the bibliography entry that this citation refers to, if any. Indices start at 1. If the citation does not refer to a bibliography entry, this should be -1.
   */
  index_of_associated_bibliography: number;
  /**
   * Rationale
   *
   * A very brief rationale for why you think this text is a citation
   */
  rationale: string;
};

/**
 * CitationResponse
 */
export type CitationResponseInput = {
  /**
   * Citations
   *
   * A list of citations found in the chunk of text
   */
  citations: Array<Citation>;
  /**
   * Rationale
   *
   * Very brief rationale for why you think the chunk of text includes these citations, if any
   */
  rationale: string;
  /**
   * The quality control result for the citation response
   */
  qc_result?: QcResult | null;
};

/**
 * CitationResponse
 */
export type CitationResponseOutput = {
  /**
   * Citations
   *
   * A list of citations found in the chunk of text
   */
  citations: Array<Citation>;
  /**
   * Rationale
   *
   * Very brief rationale for why you think the chunk of text includes these citations, if any
   */
  rationale: string;
  /**
   * The quality control result for the citation response
   */
  qc_result?: QcResult | null;
};

/**
 * CitationSuggestionResultWithClaimIndex
 */
export type CitationSuggestionResultWithClaimIndexInput = {
  /**
   * Relevant References
   *
   * Ordered list of the most relevant references the author should consider when revising the paragraph
   */
  relevant_references: Array<Reference>;
  /**
   * Rationale
   *
   * High-level reasoning summarizing how the recommendations improve the paragraph's literature coverage
   */
  rationale: string;
  /**
   * Chunk Index
   */
  chunk_index: number;
  /**
   * Claim Index
   */
  claim_index: number;
};

/**
 * CitationSuggestionResultWithClaimIndex
 */
export type CitationSuggestionResultWithClaimIndexOutput = {
  /**
   * Relevant References
   *
   * Ordered list of the most relevant references the author should consider when revising the paragraph
   */
  relevant_references: Array<Reference>;
  /**
   * Rationale
   *
   * High-level reasoning summarizing how the recommendations improve the paragraph's literature coverage
   */
  rationale: string;
  /**
   * Chunk Index
   */
  chunk_index: number;
  /**
   * Claim Index
   */
  claim_index: number;
};

/**
 * CitationType
 */
export const CitationType = {
  Bibliography: 'bibliography',
  Url: 'url',
  Footnote: 'footnote',
  Other: 'other',
} as const;

/**
 * CitationType
 */
export type CitationType = (typeof CitationType)[keyof typeof CitationType];

/**
 * Claim
 *
 * A single factual claim with verification properties.
 */
export type Claim = {
  /**
   * Text
   *
   * The relevant part of the text within the chunk of text that is being decomposed into claims.
   */
  text: string;
  /**
   * Claim
   *
   * The claim made in the text
   */
  claim: string;
  /**
   * Rationale
   *
   * The rationale for why you think the chunk of text implies this claim
   */
  rationale: string;
  /**
   * Central
   *
   * Whether the claim is central to the argument of the document
   */
  central: boolean;
};

/**
 * ClaimCategorizationResponseWithClaimIndex
 */
export type ClaimCategorizationResponseWithClaimIndex = {
  /**
   * Claim
   *
   * Exact claim text as analyzed.
   */
  claim: string;
  /**
   * Assigned category.
   */
  claim_category: ClaimCategory;
  /**
   * Rationale
   *
   * One-line reason for the category assignment.
   */
  rationale: string;
  /**
   * Needs External Verification
   *
   * True if: (a) the sentence contains a citation, OR (b) it asserts reported/established knowledge that originates outside the current document/analysis and would typically require an external source. False for purely internal methods/results/structure.
   */
  needs_external_verification: boolean;
  /**
   * Chunk Index
   */
  chunk_index: number;
  /**
   * Claim Index
   */
  claim_index: number;
};

/**
 * ClaimCategory
 */
export const ClaimCategory = {
  EstablishedReportedKnowledge: 'established_reported_knowledge',
  MethodologyProcedural: 'methodology_procedural',
  EmpiricalAnalyticalResults: 'empirical_analytical_results',
  InferentialInterpretiveClaims: 'inferential_interpretive_claims',
  MetaStructuralEvaluative: 'meta_structural_evaluative',
  Other: 'other',
} as const;

/**
 * ClaimCategory
 */
export type ClaimCategory = (typeof ClaimCategory)[keyof typeof ClaimCategory];

/**
 * ClaimCommonKnowledgeResultWithClaimIndex
 */
export type ClaimCommonKnowledgeResultWithClaimIndex = {
  /**
   * Needs Substantiation
   *
   * A boolean value indicating whether the claim needs to be substantiated.
   */
  needs_substantiation: boolean;
  /**
   * Rationale
   *
   * A brief explanation for why this claim needs to or does not need to be substantiated by references/evidence
   */
  rationale: string;
  /**
   * Guiding Rules
   *
   * Which rule(s) from the instructions most strongly guided your judgment and why
   */
  guiding_rules?: string;
  /**
   * Chunk Index
   */
  chunk_index: number;
  /**
   * Claim Index
   */
  claim_index: number;
};

/**
 * ClaimEvidenceSource
 */
export type ClaimEvidenceSource = {
  /**
   * Quote
   *
   * A quote from the document that contains the evidence for the claim
   */
  quote: string;
  /**
   * Location
   *
   * The location of the quote in the document, e.g., 'page 3', 'section 2', 'figure 3', etc. Be as specific as possible
   */
  location: string;
  /**
   * Reference File Name
   *
   * The name of the reference file that contains the evidence for the claim, as provided in the 'list of references cited' section of the input
   */
  reference_file_name: string;
};

/**
 * ClaimReferenceFactors
 *
 * A newer source that provides evidence for or against a claim
 */
export type ClaimReferenceFactors = {
  /**
   * Title
   *
   * Title of the source
   */
  title: string;
  /**
   * Authors
   *
   * Authors of the source
   */
  authors: string;
  /**
   * Publication Year
   *
   * Year of publication
   */
  publication_year: number;
  /**
   * Bibliography Info
   *
   * Bibliography entry formatted in the article's style
   */
  bibliography_info: string;
  /**
   * Link
   *
   * URL or DOI link to the source
   */
  link: string;
  /**
   * Reference Excerpt
   *
   * Relevant excerpt from the source
   */
  reference_excerpt: string;
  /**
   * Publication type of the source
   */
  reference_type: ReferenceType;
  /**
   * Type of source: supporting, conflicting, or contextual
   */
  reference_direction: ReferenceDirection;
  /**
   * Source quality level: high, medium, or low
   */
  quality: QualityLevel;
  /**
   * Political bias of the evidence
   */
  political_bias: PoliticalBias;
  /**
   * Rationale
   *
   * Why this source is relevant to the claim and the claim's evidence alignment and why does it have this quality level. In a maximum of THREE sentences.
   */
  rationale: string;
  /**
   * Methodology
   *
   * Notes about study methodology or data quality
   */
  methodology: string;
};

/**
 * ClaimResponse
 */
export type ClaimResponse = {
  /**
   * Claims
   *
   * A list of claims made in the chunk of text
   */
  claims: Array<Claim>;
  /**
   * Rationale
   *
   * Overall rationale for why you think the chunk of text implies these claims
   */
  rationale: string;
};

/**
 * ClaimSubstantiationResultWithClaimIndex
 */
export type ClaimSubstantiationResultWithClaimIndex = {
  /**
   * The degree of evidence that the supporting document(s) provides to support the claim. Possible values: ['unverifiable', 'supported', 'partially_supported', 'unsupported']
   */
  evidence_alignment: EvidenceAlignmentLevel;
  /**
   * Rationale
   *
   * A brief rationale for why you think the claim is substantiated or not substantiated by the cited supporting document(s)
   */
  rationale: string;
  /**
   * Feedback
   *
   * A brief suggestion on how the issue can be resolved, e.g., by adding more supporting documents or by rephrasing the original chunk, etc. Return 'No changes needed' if there are no significant issues with the substantiation of the claim.
   */
  feedback: string;
  /**
   * Evidence Sources
   *
   * The sources that provide the evidence for the claim. If there are multiple sources, include all of them.
   */
  evidence_sources: Array<ClaimEvidenceSource>;
  /**
   * Retrieved Passages
   *
   * Passages retrieved via RAG that were used for verification
   */
  retrieved_passages?: Array<RetrievedPassageInfo> | null;
  /**
   * Chunk Index
   */
  chunk_index: number;
  /**
   * Claim Index
   */
  claim_index: number;
};

/**
 * ClaimSubstantiatorState
 */
export type ClaimSubstantiatorStateInput = {
  /**
   * Errors
   *
   * Errors that occurred during the workflow execution.
   */
  errors?: Array<WorkflowError>;
  /**
   * Type
   */
  type?: 'claim_substantiation';
  file: FileDocumentInput;
  /**
   * Supporting Files
   */
  supporting_files?: Array<FileDocumentInput> | null;
  config: SubstantiationWorkflowConfig;
  /**
   * References
   */
  references?: Array<BibliographyItem>;
  /**
   * References Validated
   */
  references_validated?: Array<BibliographyItemValidationInput>;
  /**
   * Chunks
   */
  chunks?: Array<DocumentChunkInput>;
  /**
   * The summary of the main document
   */
  main_document_summary?: DocumentSummary | null;
  /**
   * Supporting Documents Summaries
   *
   * Dictionary mapping supporting file indices to their summaries
   */
  supporting_documents_summaries?: {
    [key: string]: DocumentSummary;
  } | null;
  /**
   * Live Reports Analysis
   *
   * Live reports analysis results by chunk index
   */
  live_reports_analysis?: Array<EvidenceWeighterResponseWithClaimIndexInput>;
  literature_review?: LiteratureReviewResponseInput | null;
  /**
   * Methodology comparison result comparing the paper's methodology to field standards
   */
  methodology_comparison?: MethodologyComparisonResponseInput | null;
  /**
   * Report output from the addendum report generator
   */
  addendum_report?: ReportOutputInput | null;
  /**
   * Ranked Issues
   *
   * Ranked list of document issues with severity levels
   */
  ranked_issues?: Array<DocumentIssue>;
  /**
   * Mapping from chunk indices to Docling items/regions for rendering
   */
  chunk_to_items?: ChunkToItemsInput | null;
};

/**
 * ClaimSubstantiatorState
 */
export type ClaimSubstantiatorStateOutput = {
  /**
   * Errors
   *
   * Errors that occurred during the workflow execution.
   */
  errors?: Array<WorkflowError>;
  /**
   * Type
   */
  type?: 'claim_substantiation';
  file: FileDocumentOutput;
  /**
   * Supporting Files
   */
  supporting_files?: Array<FileDocumentOutput> | null;
  config: SubstantiationWorkflowConfig;
  /**
   * References
   */
  references?: Array<BibliographyItem>;
  /**
   * References Validated
   */
  references_validated?: Array<BibliographyItemValidationOutput>;
  /**
   * Chunks
   */
  chunks?: Array<DocumentChunkOutput>;
  /**
   * The summary of the main document
   */
  main_document_summary?: DocumentSummary | null;
  /**
   * Supporting Documents Summaries
   *
   * Dictionary mapping supporting file indices to their summaries
   */
  supporting_documents_summaries?: {
    [key: string]: DocumentSummary;
  } | null;
  /**
   * Live Reports Analysis
   *
   * Live reports analysis results by chunk index
   */
  live_reports_analysis?: Array<EvidenceWeighterResponseWithClaimIndexOutput>;
  literature_review?: LiteratureReviewResponseOutput | null;
  /**
   * Methodology comparison result comparing the paper's methodology to field standards
   */
  methodology_comparison?: MethodologyComparisonResponseOutput | null;
  /**
   * Report output from the addendum report generator
   */
  addendum_report?: ReportOutputOutput | null;
  /**
   * Ranked Issues
   *
   * Ranked list of document issues with severity levels
   */
  ranked_issues?: Array<DocumentIssue>;
  /**
   * Mapping from chunk indices to Docling items/regions for rendering
   */
  chunk_to_items?: ChunkToItemsOutput | null;
};

/**
 * ClaimSubstantiatorStateSummary
 *
 * Summary version of ClaimSubstantiatorState with chunk summaries instead of full chunks
 */
export type ClaimSubstantiatorStateSummary = {
  /**
   * Errors
   */
  errors?: Array<WorkflowError>;
  /**
   * Type
   */
  type?: 'claim_substantiation';
  file: FileDocumentOutput;
  /**
   * Supporting Files
   */
  supporting_files?: Array<FileDocumentOutput> | null;
  config: SubstantiationWorkflowConfig;
  /**
   * References
   */
  references?: Array<BibliographyItem>;
  /**
   * References Validated
   */
  references_validated?: Array<BibliographyItemValidationOutput>;
  /**
   * Chunks
   *
   * Lightweight chunk summaries without detailed analysis
   */
  chunks?: Array<DocumentChunkSummary>;
  main_document_summary?: DocumentSummary | null;
  /**
   * Supporting Documents Summaries
   */
  supporting_documents_summaries?: {
    [key: string]: DocumentSummary;
  } | null;
  /**
   * Live Reports Analysis
   */
  live_reports_analysis?: Array<EvidenceWeighterResponseWithClaimIndexOutput>;
  literature_review?: LiteratureReviewResponseOutput | null;
  methodology_comparison?: MethodologyComparisonResponseOutput | null;
  addendum_report?: ReportOutputOutput | null;
  /**
   * Ranked Issues
   */
  ranked_issues?: Array<DocumentIssue>;
  chunk_to_items?: ChunkToItemsOutput | null;
};

/**
 * CommentSeverity
 *
 * Severity levels for DOCX comments.
 */
export const CommentSeverity = {
  None: 'none',
  Low: 'low',
  Medium: 'medium',
  High: 'high',
} as const;

/**
 * CommentSeverity
 *
 * Severity levels for DOCX comments.
 */
export type CommentSeverity = (typeof CommentSeverity)[keyof typeof CommentSeverity];

/**
 * ConfidenceInRecommendation
 */
export const ConfidenceInRecommendation = {
  High: 'high',
  Medium: 'medium',
  Low: 'low',
} as const;

/**
 * ConfidenceInRecommendation
 */
export type ConfidenceInRecommendation = (typeof ConfidenceInRecommendation)[keyof typeof ConfidenceInRecommendation];

/**
 * DoclingDocument
 *
 * Raw Docling json_content passed through to frontend
 *
 * We don't parse/transform - just pass the structure as-is.
 * Frontend will handle the Docling format directly.
 *
 * All fields from Docling's json_content are stored in __pydantic_extra__
 * and serialized properly.
 */
export type DoclingDocument = {
  [key: string]: unknown;
};

/**
 * DoclingPageInfo
 *
 * Minimal page info for frontend rendering
 *
 * Only includes the fields actually used by the frontend.
 * Note: Docling documents may use either 'page' or 'page_no' field.
 */
export type DoclingPageInfo = {
  /**
   * Page
   */
  page?: number | null;
  /**
   * Page No
   */
  page_no?: number | null;
  /**
   * Width
   */
  width?: number | null;
  /**
   * Height
   */
  height?: number | null;
};

/**
 * DoclingRegion
 *
 * Region mapping for frontend overlay
 */
export type DoclingRegion = {
  /**
   * Id
   */
  id: string;
  /**
   * Page
   */
  page: number;
  bbox: BBox;
};

/**
 * DocumentChunk
 *
 * Independent chunk response object with all processing results
 */
export type DocumentChunkInput = {
  /**
   * Content
   */
  content: string;
  /**
   * Chunk Index
   */
  chunk_index: number;
  /**
   * Paragraph Index
   */
  paragraph_index: number;
  /**
   * Claims
   */
  claims?: ClaimResponse | ToulminClaimResponse | null;
  citations?: CitationResponseInput | null;
  /**
   * Claim Categories
   */
  claim_categories?: Array<ClaimCategorizationResponseWithClaimIndex>;
  /**
   * Claim Common Knowledge Results
   */
  claim_common_knowledge_results?: Array<ClaimCommonKnowledgeResultWithClaimIndex>;
  /**
   * Substantiations
   */
  substantiations?: Array<ClaimSubstantiationResultWithClaimIndex>;
  /**
   * Citation Suggestions
   */
  citation_suggestions?: Array<CitationSuggestionResultWithClaimIndexInput>;
  /**
   * Live Reports Analysis
   */
  live_reports_analysis?: Array<EvidenceWeighterResponseWithClaimIndexInput>;
  /**
   * Inference Validations
   */
  inference_validations?: Array<InferenceValidationResponseWithClaimIndex>;
};

/**
 * DocumentChunk
 *
 * Independent chunk response object with all processing results
 */
export type DocumentChunkOutput = {
  /**
   * Content
   */
  content: string;
  /**
   * Chunk Index
   */
  chunk_index: number;
  /**
   * Paragraph Index
   */
  paragraph_index: number;
  /**
   * Claims
   */
  claims?: ClaimResponse | ToulminClaimResponse | null;
  citations?: CitationResponseOutput | null;
  /**
   * Claim Categories
   */
  claim_categories?: Array<ClaimCategorizationResponseWithClaimIndex>;
  /**
   * Claim Common Knowledge Results
   */
  claim_common_knowledge_results?: Array<ClaimCommonKnowledgeResultWithClaimIndex>;
  /**
   * Substantiations
   */
  substantiations?: Array<ClaimSubstantiationResultWithClaimIndex>;
  /**
   * Citation Suggestions
   */
  citation_suggestions?: Array<CitationSuggestionResultWithClaimIndexOutput>;
  /**
   * Live Reports Analysis
   */
  live_reports_analysis?: Array<EvidenceWeighterResponseWithClaimIndexOutput>;
  /**
   * Inference Validations
   */
  inference_validations?: Array<InferenceValidationResponseWithClaimIndex>;
};

/**
 * DocumentChunkSummary
 *
 * Summary chunk info without detailed analysis (for API responses)
 */
export type DocumentChunkSummary = {
  /**
   * Content
   */
  content: string;
  /**
   * Chunk Index
   */
  chunk_index: number;
  /**
   * Paragraph Index
   */
  paragraph_index: number;
  /**
   * Has Claims
   *
   * Whether this chunk has claims
   */
  has_claims?: boolean;
  /**
   * Claims Count
   *
   * Number of claims in this chunk
   */
  claims_count?: number;
  /**
   * Has Citations
   *
   * Whether this chunk has citations
   */
  has_citations?: boolean;
  /**
   * Citations Count
   *
   * Number of citations in this chunk
   */
  citations_count?: number;
};

/**
 * DocumentIssue
 */
export type DocumentIssue = {
  /**
   * Title
   *
   * The title of the issue
   */
  title: string;
  /**
   * Description
   *
   * The description of the issue
   */
  description: string;
  /**
   * The severity of the issue
   */
  severity: SeverityEnum;
  /**
   * Chunk Index
   *
   * The index of the chunk that contains the issue
   */
  chunk_index?: number | null;
  /**
   * Claim Index
   *
   * The index of the claim that contains the issue
   */
  claim_index?: number | null;
  /**
   * The category of the claim that contains the issue
   */
  claim_category?: ClaimCategory | null;
};

/**
 * DocumentReferenceFactors
 *
 * A reference that should be cited or discussed in the article
 */
export type DocumentReferenceFactors = {
  /**
   * Title
   *
   * The title of the reference
   */
  title: string;
  /**
   * Authors
   *
   * Authors of the source
   */
  authors: string;
  /**
   * Publication Year
   *
   * Year of publication
   */
  publication_year: number;
  /**
   * Bibliography Info
   *
   * Full bibliography citation text
   */
  bibliography_info: string;
  /**
   * Link
   *
   * URL or DOI link to the reference
   */
  link?: string | null;
  /**
   * Reference Excerpt
   *
   * Relevant excerpt from the reference that is why we should cite or discuss it
   */
  reference_excerpt: string;
  /**
   * Publication type (e.g., journal, website, book, preprint)
   */
  reference_type: ReferenceType;
  /**
   * Quality of the reference
   */
  quality: QualityLevel;
  /**
   * Type of source: supporting, conflicting, or contextual
   */
  reference_direction: ReferenceDirection;
  /**
   * Political bias of the evidence
   */
  political_bias: PoliticalBias;
  /**
   * Rationale
   *
   * Why this reference should be cited
   */
  rationale: string;
  /**
   * Main Document Excerpt
   *
   * Relevant excerpt from the main document that relates to this reference
   */
  main_document_excerpt: string;
  /**
   * Recommended Action
   *
   * What action to take (add_new_citation, cite_existing_reference_in_new_place, replace_existing_reference, discuss_reference, no_action, other
   */
  recommended_action: string;
  /**
   * Explanation For Recommended Action
   *
   * How to implement the recommended action
   */
  explanation_for_recommended_action: string;
};

/**
 * DocumentSummary
 */
export type DocumentSummary = {
  /**
   * Title
   *
   * The title of the document. Suggest a clear, concise title if the document does not have one.
   */
  title: string;
  /**
   * Authors
   *
   * The authors of the document (if available, otherwise empty string).
   */
  authors: string;
  /**
   * Publication Date
   *
   * The publication date of the document, or 'Unknown' if not available.
   */
  publication_date: string;
  /**
   * Abstract
   *
   * The abstract of the document, or 'Unknown' if not available.
   */
  abstract: string;
  /**
   * Summary
   *
   * A ~1000-word miniature version of the document (roughly 900–1100 words) that focuses on the main argument of the work. It should read like a compressed research report: clearly stating the central question or problem, the main claim/argument, the essential methods or analytical framework, the critical results, and how these results support the argument, while omitting tangential or overly detailed implementation information.
   */
  summary: string;
};

/**
 * DocxComment
 *
 * Represents a comment to be added to a docx file.
 */
export type DocxComment = {
  /**
   * Chunk Index
   */
  chunk_index: number;
  /**
   * Text
   */
  text: string;
  /**
   * Comment Text
   */
  comment_text: string;
  severity?: CommentSeverity | null;
  /**
   * Author
   */
  author?: string | null;
  /**
   * Share Link
   */
  share_link?: string | null;
};

/**
 * DocxGenerationState
 *
 * State for DOCX generation workflow.
 */
export type DocxGenerationState = {
  /**
   * Errors
   *
   * Errors that occurred during the workflow execution.
   */
  errors?: Array<WorkflowError>;
  /**
   * Type
   */
  type?: 'docx_generation';
  config: DocxGenerationWorkflowConfig;
  /**
   * Comments
   */
  comments?: Array<DocxComment> | null;
  /**
   * Chunks
   */
  chunks?: Array<unknown> | null;
  /**
   * Original File Path
   */
  original_file_path?: string | null;
  /**
   * Base File Name
   */
  base_file_name?: string | null;
  /**
   * Generated File Path
   */
  generated_file_path?: string | null;
  /**
   * Filename
   */
  filename?: string | null;
};

/**
 * DocxGenerationWorkflowConfig
 *
 * Config for DOCX generation workflow.
 */
export type DocxGenerationWorkflowConfig = {
  /**
   * Project Id
   *
   * The ID of the project that this workflow run should be associated with
   */
  project_id?: string | null;
  /**
   * Openai Api Key
   *
   * The OpenAI API key to use for this workflow execution
   */
  openai_api_key?: string | null;
  /**
   * Type
   */
  type?: 'docx_generation';
  /**
   * Claim Substantiation Run Id
   *
   * Workflow run ID of the claim substantiation run to generate DOCX from
   */
  claim_substantiation_run_id: string;
  /**
   * Share Token
   *
   * Optional share token to include share links in comments
   */
  share_token?: string | null;
};

/**
 * EvalPackageRequest
 */
export type EvalPackageRequest = {
  results: ClaimSubstantiatorStateInput;
  /**
   * Test Name
   */
  test_name?: string;
  /**
   * Description
   */
  description?: string;
};

/**
 * EvidenceAlignmentLevel
 */
export const EvidenceAlignmentLevel = {
  Unverifiable: 'unverifiable',
  Supported: 'supported',
  PartiallySupported: 'partially_supported',
  Unsupported: 'unsupported',
} as const;

/**
 * EvidenceAlignmentLevel
 */
export type EvidenceAlignmentLevel = (typeof EvidenceAlignmentLevel)[keyof typeof EvidenceAlignmentLevel];

/**
 * EvidenceWeighterRecommendedAction
 */
export const EvidenceWeighterRecommendedAction = {
  UpdateClaim: 'update_claim',
  AddCitation: 'add_citation',
  NoUpdateNeeded: 'no_update_needed',
} as const;

/**
 * EvidenceWeighterRecommendedAction
 */
export type EvidenceWeighterRecommendedAction =
  (typeof EvidenceWeighterRecommendedAction)[keyof typeof EvidenceWeighterRecommendedAction];

/**
 * EvidenceWeighterResponseWithClaimIndex
 */
export type EvidenceWeighterResponseWithClaimIndexInput = {
  /**
   * Newer References
   *
   * Newer references found from the literature review report
   */
  newer_references: Array<ClaimReferenceFactors>;
  /**
   * Evidence alignment of the newer references: unverifiable, supported, partially_supported, or unsupported
   */
  newer_references_alignment: ReferenceAlignmentLevel;
  /**
   * Recommended action for the claim: update_claim, add_citation, or no_change
   */
  claim_update_action: EvidenceWeighterRecommendedAction;
  /**
   * Rationale
   *
   * Explanation of the rationale for the claim update action in a maximum of TWO sentences.
   */
  rationale: string;
  /**
   * Confidence level in the claim update: high, medium, or low
   */
  confidence_level: QualityLevel;
  /**
   * Rewritten Claim
   *
   * The rewritten claim that is more clear and accurate according to the recommended action and taking the newer sources into account.
   */
  rewritten_claim: string;
  /**
   * Chunk Index
   */
  chunk_index: number;
  /**
   * Claim Index
   */
  claim_index: number;
};

/**
 * EvidenceWeighterResponseWithClaimIndex
 */
export type EvidenceWeighterResponseWithClaimIndexOutput = {
  /**
   * Newer References
   *
   * Newer references found from the literature review report
   */
  newer_references: Array<ClaimReferenceFactors>;
  /**
   * Evidence alignment of the newer references: unverifiable, supported, partially_supported, or unsupported
   */
  newer_references_alignment: ReferenceAlignmentLevel;
  /**
   * Recommended action for the claim: update_claim, add_citation, or no_change
   */
  claim_update_action: EvidenceWeighterRecommendedAction;
  /**
   * Rationale
   *
   * Explanation of the rationale for the claim update action in a maximum of TWO sentences.
   */
  rationale: string;
  /**
   * Confidence level in the claim update: high, medium, or low
   */
  confidence_level: QualityLevel;
  /**
   * Rewritten Claim
   *
   * The rewritten claim that is more clear and accurate according to the recommended action and taking the newer sources into account.
   */
  rewritten_claim: string;
  /**
   * Chunk Index
   */
  chunk_index: number;
  /**
   * Claim Index
   */
  claim_index: number;
};

/**
 * FeedbackRequest
 *
 * Generic request model for any entity feedback
 */
export type FeedbackRequest = {
  /**
   * Workflow Run Id
   */
  workflow_run_id: string;
  /**
   * Entity Path
   *
   * JSONB path identifying the entity
   */
  entity_path: {
    [key: string]: unknown;
  };
  /**
   * Feedback Type
   */
  feedback_type: string;
  /**
   * Feedback Text
   *
   * Optional feedback text (typically used with thumbs down)
   */
  feedback_text?: string | null;
};

/**
 * FeedbackResponse
 *
 * Response model for feedback
 */
export type FeedbackResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Workflow Run Id
   */
  workflow_run_id: string;
  /**
   * Entity Path
   */
  entity_path: {
    [key: string]: unknown;
  };
  feedback_type: FeedbackType;
  /**
   * Feedback Text
   */
  feedback_text: string | null;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * FeedbackType
 *
 * Type of feedback provided by users
 */
export const FeedbackType = { ThumbsUp: 'thumbs_up', ThumbsDown: 'thumbs_down' } as const;

/**
 * FeedbackType
 *
 * Type of feedback provided by users
 */
export type FeedbackType = (typeof FeedbackType)[keyof typeof FeedbackType];

/**
 * FieldCategory
 */
export const FieldCategory = {
  Author: 'author',
  Title: 'title',
  Publisher: 'publisher',
  Year: 'year',
} as const;

/**
 * FieldCategory
 */
export type FieldCategory = (typeof FieldCategory)[keyof typeof FieldCategory];

/**
 * FieldProblemType
 */
export const FieldProblemType = {
  Correct: 'correct',
  Missing: 'missing',
  Incorrect: 'incorrect',
  Other: 'other',
} as const;

/**
 * FieldProblemType
 */
export type FieldProblemType = (typeof FieldProblemType)[keyof typeof FieldProblemType];

/**
 * File
 */
export type File = {
  /**
   * Id
   *
   * The unique identifier for the file
   */
  id: string;
  /**
   * Project Id
   *
   * The project this file belongs to
   */
  project_id: string;
  /**
   * File Name
   *
   * The original name of the uploaded file
   */
  file_name: string;
  /**
   * File Path
   *
   * The path to the file in the file system (xxhash-based)
   */
  file_path: string;
  /**
   * File Type
   *
   * The MIME type of the file
   */
  file_type: string;
  /**
   * File Size
   *
   * The size of the file in bytes
   */
  file_size: number;
  /**
   * Content Hash
   *
   * xxhash of file content for deduplication
   */
  content_hash: string;
  /**
   * Original File Path
   *
   * Path to original file if converted (e.g., .docx before PDF conversion)
   */
  original_file_path?: string | null;
  /**
   * The role of the file in the workflow (main, support, etc.)
   */
  role: FileRole;
  /**
   * Uploaded By
   *
   * The user who uploaded the file
   */
  uploaded_by: string;
  /**
   * Description
   *
   * Optional description of the file
   */
  description?: string | null;
  /**
   * Created At
   *
   * The timestamp when the file was uploaded
   */
  created_at: Date;
};

/**
 * FileDocument
 */
export type FileDocumentInput = {
  /**
   * File Name
   *
   * The original name of the uploaded file, as saved in the user file system
   */
  file_name: string;
  /**
   * File Path
   *
   * The path to the uploaded file, as saved in the file system
   */
  file_path: string;
  /**
   * Original File Path
   *
   * Path to the original file if it was converted (e.g., original .docx before PDF conversion)
   */
  original_file_path?: string | null;
  /**
   * File Type
   *
   * The MIME type of the uploaded file
   */
  file_type: string;
  /**
   * Markdown
   *
   * The uploaded file content converted to markdown
   */
  markdown: string;
  /**
   * Markdown Token Count
   *
   * The approximate number of tokens in the markdown content
   */
  markdown_token_count: number;
  /**
   * File Id
   *
   * The UUID of the file record in the database (if available)
   */
  file_id?: string | null;
  /**
   * Full Docling document for internal processing (chunk mapping, etc.)
   */
  docling_document?: DoclingDocument | null;
};

/**
 * FileDocument
 */
export type FileDocumentOutput = {
  /**
   * File Name
   *
   * The original name of the uploaded file, as saved in the user file system
   */
  file_name: string;
  /**
   * File Path
   *
   * The path to the uploaded file, as saved in the file system
   */
  file_path: string;
  /**
   * Original File Path
   *
   * Path to the original file if it was converted (e.g., original .docx before PDF conversion)
   */
  original_file_path?: string | null;
  /**
   * File Type
   *
   * The MIME type of the uploaded file
   */
  file_type: string;
  /**
   * Markdown
   *
   * The uploaded file content converted to markdown
   */
  markdown: string;
  /**
   * Markdown Token Count
   *
   * The approximate number of tokens in the markdown content
   */
  markdown_token_count: number;
  /**
   * File Id
   *
   * The UUID of the file record in the database (if available)
   */
  file_id?: string | null;
  /**
   * Full Docling document for internal processing (chunk mapping, etc.)
   */
  docling_document?: DoclingDocument | null;
  /**
   * Docling Pages
   *
   * Computed from docling_document for API responses
   */
  readonly docling_pages: Array<DoclingPageInfo> | null;
};

/**
 * FileRole
 *
 * Extensible enum for file purposes in workflows
 */
export const FileRole = { Main: 'main', Support: 'support' } as const;

/**
 * FileRole
 *
 * Extensible enum for file purposes in workflows
 */
export type FileRole = (typeof FileRole)[keyof typeof FileRole];

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * InferenceValidationResponseWithClaimIndex
 */
export type InferenceValidationResponseWithClaimIndex = {
  /**
   * Valid
   *
   * Considering the Toulmin elements, whether the inference is valid or not
   */
  valid: boolean;
  /**
   * Rationale
   *
   * The rationale for why you think the inference is valid or not. If the inference is not valid, explain why. If the inference is valid, explain why. In only TWO sentences.
   */
  rationale: string;
  /**
   * Suggested Action
   *
   * A suggested action to take if the inference is not valid. If the inference is valid, return 'No changes needed'. In only TWO sentences.
   */
  suggested_action: string;
  /**
   * Claim Index
   *
   * The index of the claim that is being validated
   */
  claim_index: number;
  /**
   * Chunk Index
   *
   * The index of the chunk that contains the claim
   */
  chunk_index: number;
};

/**
 * LiteratureReviewResponse
 */
export type LiteratureReviewResponseInput = {
  /**
   * Relevant References
   *
   * List of relevant references to cite
   */
  relevant_references?: Array<DocumentReferenceFactors>;
  /**
   * Rationale
   *
   * Overall rationale for the literature review recommendations
   */
  rationale: string;
};

/**
 * LiteratureReviewResponse
 */
export type LiteratureReviewResponseOutput = {
  /**
   * Relevant References
   *
   * List of relevant references to cite
   */
  relevant_references?: Array<DocumentReferenceFactors>;
  /**
   * Rationale
   *
   * Overall rationale for the literature review recommendations
   */
  rationale: string;
};

/**
 * MethodologicalAlignmentState
 *
 * State for the methodological alignment workflow
 */
export type MethodologicalAlignmentState = {
  /**
   * Errors
   *
   * Errors that occurred during the workflow execution.
   */
  errors?: Array<WorkflowError>;
  /**
   * Type
   */
  type?: 'methodological_alignment';
  /**
   * The main source document
   */
  file: FileDocumentOutput;
  /**
   * Methodology alignment analysis result
   */
  methodology_comparison?: MethodologyComparisonResponseOutput | null;
};

/**
 * MethodologicalAlignmentWorkflowConfig
 *
 * Configuration model for the methodological alignment workflow
 */
export type MethodologicalAlignmentWorkflowConfig = {
  /**
   * Project Id
   *
   * The ID of the project that this workflow run should be associated with
   */
  project_id?: string | null;
  /**
   * Openai Api Key
   *
   * The OpenAI API key to use for this workflow execution
   */
  openai_api_key?: string | null;
  /**
   * Type
   */
  type?: 'methodological_alignment';
};

/**
 * MethodologyComparisonResponse
 */
export type MethodologyComparisonResponseInput = {
  /**
   * The class of reproducibility of the methodology.
   */
  reproducibility: ReproducibilityCategoryResponse;
  /**
   * The extracted methodology of the paper.
   */
  extracted_methodology: SummaryAndOutput;
  /**
   * The overview of the field methods.
   */
  field_methods_overview: SummaryAndOutput;
  /**
   * The alignment of the paper's methodology with the field methods.
   */
  alignment_with_field_practice: SummaryAndOutput;
  /**
   * The rigor and risks of the paper's methodology.
   */
  methodological_rigor_and_risks: SummaryAndOutput;
  /**
   * The suggestions for improvements to the paper's methodology.
   */
  suggestions_for_improvements: SummaryAndOutput;
  /**
   * References
   *
   * List of sources cited from web search
   */
  references?: Array<ReferenceMinimal>;
};

/**
 * MethodologyComparisonResponse
 */
export type MethodologyComparisonResponseOutput = {
  /**
   * The class of reproducibility of the methodology.
   */
  reproducibility: ReproducibilityCategoryResponse;
  /**
   * The extracted methodology of the paper.
   */
  extracted_methodology: SummaryAndOutput;
  /**
   * The overview of the field methods.
   */
  field_methods_overview: SummaryAndOutput;
  /**
   * The alignment of the paper's methodology with the field methods.
   */
  alignment_with_field_practice: SummaryAndOutput;
  /**
   * The rigor and risks of the paper's methodology.
   */
  methodological_rigor_and_risks: SummaryAndOutput;
  /**
   * The suggestions for improvements to the paper's methodology.
   */
  suggestions_for_improvements: SummaryAndOutput;
  /**
   * References
   *
   * List of sources cited from web search
   */
  references?: Array<ReferenceMinimal>;
};

/**
 * PoliticalBias
 */
export const PoliticalBias = {
  Conservative: 'conservative',
  Liberal: 'liberal',
  Other: 'other',
} as const;

/**
 * PoliticalBias
 */
export type PoliticalBias = (typeof PoliticalBias)[keyof typeof PoliticalBias];

/**
 * Project
 */
export type Project = {
  /**
   * Id
   *
   * The unique identifier for the project
   */
  id: string;
  /**
   * Title
   *
   * The title of the project
   */
  title: string;
  /**
   * User Id
   *
   * The user who created the project
   */
  user_id?: string;
  /**
   * Created At
   *
   * The timestamp when the project was created
   */
  created_at: Date;
  /**
   * Last Updated At
   *
   * The timestamp when the project was last updated
   */
  last_updated_at: Date;
};

/**
 * ProjectDetailed
 */
export type ProjectDetailed = {
  project: Project;
  /**
   * Workflow Runs
   *
   * The workflow runs for the project
   */
  workflow_runs?: Array<WorkflowRun>;
};

/**
 * ProjectListItem
 */
export type ProjectListItem = {
  /**
   * The project
   */
  project: Project;
  /**
   * Workflow Runs
   *
   * The workflow runs for the project
   */
  workflow_runs?: Array<WorkflowRun>;
};

/**
 * PublicationQuality
 */
export const PublicationQuality = {
  HighImpactPublication: 'high_impact_publication',
  MediumImpactPublication: 'medium_impact_publication',
  LowImpactPublication: 'low_impact_publication',
  NotAPublication: 'not_a_publication',
} as const;

/**
 * PublicationQuality
 */
export type PublicationQuality = (typeof PublicationQuality)[keyof typeof PublicationQuality];

/**
 * QCResult
 *
 * Quality control result for agent outputs.
 */
export type QcResult = {
  /**
   * Valid
   */
  valid: boolean;
  /**
   * Feedback
   */
  feedback: string;
};

/**
 * QualityLevel
 */
export const QualityLevel = {
  High: 'high',
  Medium: 'medium',
  Low: 'low',
} as const;

/**
 * QualityLevel
 */
export type QualityLevel = (typeof QualityLevel)[keyof typeof QualityLevel];

/**
 * RecommendedAction
 */
export const RecommendedAction = {
  AddNewCitation: 'add_new_citation',
  CiteExistingReferenceInNewPlace: 'cite_existing_reference_in_new_place',
  ReplaceExistingReference: 'replace_existing_reference',
  DiscussReference: 'discuss_reference',
  NoAction: 'no_action',
  Other: 'other',
} as const;

/**
 * RecommendedAction
 */
export type RecommendedAction = (typeof RecommendedAction)[keyof typeof RecommendedAction];

/**
 * Reference
 */
export type Reference = {
  /**
   * Title
   *
   * Canonical title for the reference exactly as it should appear in the article's bibliography
   */
  title: string;
  /**
   * Format classification for the reference (webpage, book, article, or other)
   */
  type: ReferenceType;
  /**
   * Link
   *
   * Stable URL or DOI that lets the author retrieve the reference quickly
   */
  link: string;
  /**
   * Bibliography Info
   *
   * Bibliography entry formatted in the article's style; reuse the existing entry when the source is already in the bibliography
   */
  bibliography_info: string;
  /**
   * Is Already Cited Elsewhere
   *
   * A boolean value indicating whether the reference is already cited elsewhere in the document
   */
  is_already_cited_elsewhere: boolean;
  /**
   * Index Of Associated Existing Reference
   *
   * The index of the existing reference that this citation refers to, if any. Indices start at 1. If the citation does not refer to an existing reference in the bibliography, this should be -1.
   */
  index_of_associated_existing_reference: number;
  /**
   * The quality of the publication that carries the suggested reference
   */
  publication_quality: PublicationQuality;
  /**
   * Related Excerpt
   *
   * Exact sentence or excerpt from the full document that should cite or discuss this reference
   */
  related_excerpt: string;
  /**
   * Related Excerpt From Reference
   *
   * Exact sentence or excerpt from the reference that is why we should cite or discuss it
   */
  related_excerpt_from_reference: string;
  /**
   * Rationale
   *
   * Brief explanation of why the reference strengthens, updates, or contextualizes the focused paragraph
   */
  rationale: string;
  /**
   * Action to take for this reference: add_citation, replace_existing_reference, discuss_reference, no_action, or other
   */
  recommended_action: RecommendedAction;
  /**
   * Explanation For Recommended Action
   *
   * Specific guidance for applying the recommended action, including citation placement or text revisions
   */
  explanation_for_recommended_action: string;
  /**
   * The confidence in the recommendation
   */
  confidence_in_recommendation: ConfidenceInRecommendation;
};

/**
 * ReferenceAlignmentLevel
 */
export const ReferenceAlignmentLevel = {
  Unverifiable: 'unverifiable',
  Supported: 'supported',
  PartiallySupported: 'partially_supported',
  Unsupported: 'unsupported',
} as const;

/**
 * ReferenceAlignmentLevel
 */
export type ReferenceAlignmentLevel = (typeof ReferenceAlignmentLevel)[keyof typeof ReferenceAlignmentLevel];

/**
 * ReferenceDirection
 */
export const ReferenceDirection = {
  Supporting: 'supporting',
  Conflicting: 'conflicting',
  Mixed: 'mixed',
  Contextual: 'contextual',
} as const;

/**
 * ReferenceDirection
 */
export type ReferenceDirection = (typeof ReferenceDirection)[keyof typeof ReferenceDirection];

/**
 * ReferenceDownloaderState
 *
 * State for the reference downloader workflow
 */
export type ReferenceDownloaderState = {
  /**
   * Errors
   *
   * Errors that occurred during the workflow execution.
   */
  errors?: Array<WorkflowError>;
  /**
   * Type
   */
  type?: 'reference_downloader';
  /**
   * The configuration for the workflow
   */
  config: ReferenceDownloaderWorkflowConfig;
  /**
   * Fetched References
   *
   * The response from the reference fetcher agent
   */
  fetched_references?: Array<ReferenceFetchItem> | null;
  /**
   * Downloaded References
   *
   * The hashes of the files that were downloaded, or None if the download failed. Indexes match the fetched_references list.
   */
  downloaded_references?: Array<string | null> | null;
};

/**
 * ReferenceDownloaderWorkflowConfig
 *
 * Configuration model for the reference downloader workflow
 */
export type ReferenceDownloaderWorkflowConfig = {
  /**
   * Project Id
   *
   * The ID of the project that this workflow run should be associated with
   */
  project_id?: string | null;
  /**
   * Openai Api Key
   *
   * The OpenAI API key to use for this workflow execution
   */
  openai_api_key?: string | null;
  /**
   * Type
   */
  type?: 'reference_downloader';
  /**
   * References
   *
   * The references to fetch from the internet
   */
  references: Array<string>;
};

/**
 * ReferenceFetchConclusion
 */
export const ReferenceFetchConclusion = {
  SourceFound: 'source_found',
  SourceNotFound: 'source_not_found',
  SourceFoundButNotAccessible: 'source_found_but_not_accessible',
} as const;

/**
 * ReferenceFetchConclusion
 */
export type ReferenceFetchConclusion = (typeof ReferenceFetchConclusion)[keyof typeof ReferenceFetchConclusion];

/**
 * ReferenceFetchItem
 */
export type ReferenceFetchItem = {
  /**
   * Reference Details
   *
   * The original reference as provided (verbatim)
   */
  reference_details: string;
  /**
   * Reasoning
   *
   * Step-by-step reasoning describing parsing approach, search strategies, sources checked, and how the match was verified
   */
  reasoning: string;
  /**
   * Source Url
   *
   * Direct URL to the located source, or null if no match was found
   */
  source_url: string | null;
  /**
   * Download Url
   *
   * Direct URL to the downloadable version of the located source, or null if no match was found
   */
  download_url: string | null;
  final_conclusion: ReferenceFetchConclusion;
};

/**
 * ReferenceMinimal
 */
export type ReferenceMinimal = {
  /**
   * Title
   *
   * Canonical title for the reference exactly as it should appear in the article's bibliography
   */
  title: string;
  /**
   * Format classification for the reference (webpage, book, article, or other)
   */
  type: ReferenceType;
  /**
   * Link
   *
   * Stable URL or DOI that lets the author retrieve the reference quickly
   */
  link: string;
  /**
   * Bibliography Info
   *
   * Bibliography entry formatted in the article's style; reuse the existing entry when the source is already in the bibliography
   */
  bibliography_info: string;
};

/**
 * ReferenceType
 */
export const ReferenceType = {
  PeerReviewedPublication: 'peer_reviewed_publication',
  Preprint: 'preprint',
  Book: 'book',
  GovernmentNgoReport: 'government_ngo_report',
  DataSoftware: 'data_software',
  NewsMedia: 'news_media',
  Reference: 'reference',
  Webpage: 'webpage',
} as const;

/**
 * ReferenceType
 */
export type ReferenceType = (typeof ReferenceType)[keyof typeof ReferenceType];

/**
 * ReportMetadata
 */
export type ReportMetadata = {
  /**
   * The type of update
   */
  update_type: UpdateType;
  /**
   * Title
   *
   * Newspaper-style title summarizing the changes (or lack of changes) suggested by the report
   */
  title: string;
  /**
   * Sentence Summary
   *
   * A single sentence summary of what the authors should update in the report
   */
  sentence_summary: string;
  /**
   * Date Generated
   *
   * The date the report was generated in YYYY-MM-DD format
   */
  date_generated: string;
};

/**
 * ReportOutput
 */
export type ReportOutputInput = {
  /**
   * Report Markdown
   *
   * The markdown formatted report
   */
  report_markdown: string;
  report_metadata: ReportMetadata;
};

/**
 * ReportOutput
 */
export type ReportOutputOutput = {
  /**
   * Report Markdown
   *
   * The markdown formatted report
   */
  report_markdown: string;
  report_metadata: ReportMetadata;
};

/**
 * ReproducibilityCategory
 */
export const ReproducibilityCategory = {
  FullyReproducible: 'fully_reproducible',
  ReproducibleWithWebSearch: 'reproducible_with_web_search',
  ReproducibleWithExternalUploads: 'reproducible_with_external_uploads',
  NotReproducible: 'not_reproducible',
} as const;

/**
 * ReproducibilityCategory
 */
export type ReproducibilityCategory = (typeof ReproducibilityCategory)[keyof typeof ReproducibilityCategory];

/**
 * ReproducibilityCategoryResponse
 */
export type ReproducibilityCategoryResponse = {
  /**
   * The class of reproducibility of the methodology.
   */
  class_value: ReproducibilityCategory;
  /**
   * Rationale
   *
   * The rationale for why you think the methodology is reproducible or not.
   */
  rationale: string;
};

/**
 * RerunAnalysisRequest
 *
 * Request model for re-running the analysis. Can be used to re-run a specific chunk or the entire analysis.
 */
export type RerunAnalysisRequest = {
  /**
   * Project Id
   *
   * The ID of the project to re-run
   */
  project_id: string;
  /**
   * Configuration for the re-run. Should include all the original configuration options, plus any overrides.
   */
  config: SubstantiationWorkflowConfig;
};

/**
 * RetrievedPassageInfo
 *
 * Information about a passage retrieved via RAG.
 */
export type RetrievedPassageInfo = {
  /**
   * Content
   *
   * The text content of the retrieved passage
   */
  content: string;
  /**
   * Source File
   *
   * Name of the source file
   */
  source_file: string;
  /**
   * Cosine Distance
   *
   * Cosine distance (0-1, lower = more similar)
   */
  cosine_distance: number;
  /**
   * Chunk Index
   *
   * Index of the chunk within the source
   */
  chunk_index: number;
};

/**
 * SeverityEnum
 */
export const SeverityEnum = {
  None: 'none',
  Low: 'low',
  Medium: 'medium',
  High: 'high',
} as const;

/**
 * SeverityEnum
 */
export type SeverityEnum = (typeof SeverityEnum)[keyof typeof SeverityEnum];

/**
 * ShareLinkResponse
 *
 * Response model for share link operations.
 */
export type ShareLinkResponse = {
  /**
   * Token
   *
   * The share token
   */
  token: string;
  /**
   * Url
   *
   * The full shareable URL
   */
  url: string;
  /**
   * Is Active
   *
   * Whether the share link is active
   */
  is_active: boolean;
};

/**
 * ShareStatusResponse
 *
 * Response model for share status check.
 */
export type ShareStatusResponse = {
  /**
   * Enabled
   *
   * Whether sharing is enabled
   */
  enabled: boolean;
  /**
   * Share link details if enabled
   */
  share_link?: ShareLinkResponse | null;
};

/**
 * SharedProjectInfo
 *
 * Minimal project info for shared view (no sensitive data).
 */
export type SharedProjectInfo = {
  /**
   * Id
   */
  id: string;
  /**
   * Title
   */
  title: string;
  /**
   * Created At
   */
  created_at: Date;
};

/**
 * SharedProjectResponse
 *
 * Response for a shared project with all necessary data.
 */
export type SharedProjectResponse = {
  project: SharedProjectInfo;
  workflow_run?: SharedWorkflowRun | null;
  state?: ClaimSubstantiatorStateSummary | null;
};

/**
 * SharedWorkflowRun
 *
 * Minimal workflow run info for shared view.
 */
export type SharedWorkflowRun = {
  /**
   * Id
   */
  id: string;
  /**
   * Type
   */
  type: string;
  /**
   * Status
   */
  status: string;
};

/**
 * StartWorkflowResponse
 *
 * Response model for starting a workflow
 */
export type StartWorkflowResponse = {
  /**
   * Project Id
   */
  project_id?: string | null;
  /**
   * Workflow Run Id
   */
  workflow_run_id?: string | null;
  type?: WorkflowRunType | null;
  /**
   * Message
   */
  message: string;
};

/**
 * SubstantiationWorkflowConfig
 *
 * Configuration model for claim substantiation workflow
 */
export type SubstantiationWorkflowConfig = {
  /**
   * Project Id
   *
   * The ID of the project that this workflow run should be associated with
   */
  project_id?: string | null;
  /**
   * Openai Api Key
   *
   * The OpenAI API key to use for this workflow execution
   */
  openai_api_key?: string | null;
  /**
   * Type
   */
  type?: 'claim_substantiation';
  /**
   * Use Toulmin
   *
   * Whether to use Toulmin claim detection approach
   */
  use_toulmin?: boolean;
  /**
   * Run Literature Review
   *
   * Whether to run the literature review
   */
  run_literature_review?: boolean;
  /**
   * Run Suggest Citations
   *
   * Whether to run the citation suggestions
   */
  run_suggest_citations?: boolean;
  /**
   * Use Rag
   *
   * Use RAG for claim verification
   */
  use_rag?: boolean;
  /**
   * Run Live Reports
   *
   * Whether to run the live reports analysis
   */
  run_live_reports?: boolean;
  /**
   * Run Reference Validation
   *
   * Whether to validate references using web search
   */
  run_reference_validation?: boolean;
  /**
   * Document Publication Date
   *
   * Publication date (YYYY-MM-DD) of the document for literature review and live reports
   */
  document_publication_date?: Date | null;
  /**
   * Target Chunk Indices
   *
   * Specific chunk indices to process (None = process all chunks)
   */
  target_chunk_indices?: Array<number> | null;
  /**
   * Agents To Run
   *
   * Specific agents to run (None = run all agents)
   */
  agents_to_run?: Array<string> | null;
  /**
   * Domain
   *
   * Domain context for more accurate analysis
   */
  domain?: string | null;
  /**
   * Target Audience
   *
   * Target audience context for analysis
   */
  target_audience?: string | null;
  /**
   * Session Id
   *
   * Session ID for Langfuse tracing
   */
  session_id?: string | null;
};

/**
 * SummaryAndOutput
 */
export type SummaryAndOutput = {
  /**
   * Summary
   *
   * A one to two sentence summary of the related section.
   */
  summary: string;
  /**
   * Markdown Output
   *
   * Markdown formatted output of the full context of the related section.
   */
  markdown_output: string;
};

/**
 * ToulminClaim
 */
export type ToulminClaim = {
  /**
   * Text
   *
   * The exact excerpt from the chunk that implies the claim
   */
  text: string;
  /**
   * Claim
   *
   * The claim made in the excerpt
   */
  claim: string;
  /**
   * Rationale
   *
   * Why the excerpt implies this claim (brief analytic rationale)
   */
  rationale: string;
  /**
   * Data
   *
   * Data/Grounds: evidence or facts supporting the claim, quoted or paraphrased
   */
  data?: Array<string>;
  /**
   * Warrants
   *
   * Warrants: assumptions that connect the data to the claim (may be cultural, logical, or methodological)
   */
  warrants?: Array<string>;
  /**
   * Warrant Expression
   *
   * Whether the primary warrant is stated explicitly, implied implicitly, or none could be identified
   */
  warrant_expression: 'stated' | 'implied' | 'none';
  /**
   * Qualifiers
   *
   * Qualifiers: words/phrases indicating the strength/scope of the claim (e.g., 'likely', 'some', 'in many cases')
   */
  qualifiers?: Array<string>;
  /**
   * Rebuttals
   *
   * Rebuttals: acknowledged exceptions, counter-arguments, or conditions under which the claim may not hold
   */
  rebuttals?: Array<string>;
  /**
   * Backing
   *
   * Backing: additional support that justifies the warrant (e.g., principles, studies, or theoretical reasons)
   */
  backing?: Array<string>;
};

/**
 * ToulminClaimResponse
 */
export type ToulminClaimResponse = {
  /**
   * Claims
   *
   * List of extracted claims with Toulmin elements when available
   */
  claims: Array<ToulminClaim>;
  /**
   * Rationale
   *
   * Overall rationale for the extractions and how the Toulmin elements were identified
   */
  rationale: string;
};

/**
 * UpdateProjectRequest
 */
export type UpdateProjectRequest = {
  /**
   * Title
   */
  title?: string | null;
};

/**
 * UpdateType
 *
 * Defines the classification and metadata for a report update.
 */
export const UpdateType = {
  NoUpdateNeeded: 'no_update_needed',
  MinorFactualUpdate: 'minor_factual_update',
  ModerateUpdate: 'moderate_update',
  MajorUpdateRequired: 'major_update_required',
  OutdatedOrInvalidated: 'outdated_or_invalidated',
} as const;

/**
 * UpdateType
 *
 * Defines the classification and metadata for a report update.
 */
export type UpdateType = (typeof UpdateType)[keyof typeof UpdateType];

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * WorkflowError
 *
 * Error object for the overall workflow or specific chunks.
 */
export type WorkflowError = {
  /**
   * Chunk Index
   *
   * The index of the chunk that caused the error. This is None if the error occurred before the chunk was processed or in the overall workflow (not chunk-related).
   */
  chunk_index?: number | null;
  /**
   * Task Name
   *
   * The name of the task that caused the error.
   */
  task_name: string;
  /**
   * Error
   *
   * The error message.
   */
  error: string;
};

/**
 * WorkflowRun
 */
export type WorkflowRun = {
  /**
   * Id
   *
   * The unique identifier for the workflow run
   */
  id: string;
  /**
   * Project Id
   *
   * FK for the project that this workflow run belongs to
   */
  project_id: string | null;
  /**
   * The type of the workflow run
   */
  type: WorkflowRunType;
  /**
   * Langgraph Thread Id
   */
  langgraph_thread_id: string;
  /**
   * The status of the workflow run
   */
  status: WorkflowRunStatus;
  /**
   * Created At
   *
   * The timestamp when the workflow run was created
   */
  created_at: Date;
  /**
   * Last Updated At
   *
   * The timestamp when the workflow run was last updated
   */
  last_updated_at: Date;
};

/**
 * WorkflowRunDetail
 */
export type WorkflowRunDetail = {
  run: WorkflowRun;
  /**
   * State
   */
  state: ClaimSubstantiatorStateOutput | MethodologicalAlignmentState | ReferenceDownloaderState | DocxGenerationState;
};

/**
 * WorkflowRunStatus
 */
export const WorkflowRunStatus = {
  Pending: 'pending',
  Running: 'running',
  Completed: 'completed',
} as const;

/**
 * WorkflowRunStatus
 */
export type WorkflowRunStatus = (typeof WorkflowRunStatus)[keyof typeof WorkflowRunStatus];

/**
 * WorkflowRunType
 */
export const WorkflowRunType = {
  ClaimSubstantiation: 'claim_substantiation',
  MethodologicalAlignment: 'methodological_alignment',
  ReferenceDownloader: 'reference_downloader',
  DocxGeneration: 'docx_generation',
} as const;

/**
 * WorkflowRunType
 */
export type WorkflowRunType = (typeof WorkflowRunType)[keyof typeof WorkflowRunType];

/**
 * ClaimSubstantiatorState
 */
export type ClaimSubstantiatorStateOutputWritable = {
  /**
   * Errors
   *
   * Errors that occurred during the workflow execution.
   */
  errors?: Array<WorkflowError>;
  /**
   * Type
   */
  type?: 'claim_substantiation';
  file: FileDocumentOutputWritable;
  /**
   * Supporting Files
   */
  supporting_files?: Array<FileDocumentOutputWritable> | null;
  config: SubstantiationWorkflowConfig;
  /**
   * References
   */
  references?: Array<BibliographyItem>;
  /**
   * References Validated
   */
  references_validated?: Array<BibliographyItemValidationOutput>;
  /**
   * Chunks
   */
  chunks?: Array<DocumentChunkOutput>;
  /**
   * The summary of the main document
   */
  main_document_summary?: DocumentSummary | null;
  /**
   * Supporting Documents Summaries
   *
   * Dictionary mapping supporting file indices to their summaries
   */
  supporting_documents_summaries?: {
    [key: string]: DocumentSummary;
  } | null;
  /**
   * Live Reports Analysis
   *
   * Live reports analysis results by chunk index
   */
  live_reports_analysis?: Array<EvidenceWeighterResponseWithClaimIndexOutput>;
  literature_review?: LiteratureReviewResponseOutput | null;
  /**
   * Methodology comparison result comparing the paper's methodology to field standards
   */
  methodology_comparison?: MethodologyComparisonResponseOutput | null;
  /**
   * Report output from the addendum report generator
   */
  addendum_report?: ReportOutputOutput | null;
  /**
   * Ranked Issues
   *
   * Ranked list of document issues with severity levels
   */
  ranked_issues?: Array<DocumentIssue>;
  /**
   * Mapping from chunk indices to Docling items/regions for rendering
   */
  chunk_to_items?: ChunkToItemsOutput | null;
};

/**
 * ClaimSubstantiatorStateSummary
 *
 * Summary version of ClaimSubstantiatorState with chunk summaries instead of full chunks
 */
export type ClaimSubstantiatorStateSummaryWritable = {
  /**
   * Errors
   */
  errors?: Array<WorkflowError>;
  /**
   * Type
   */
  type?: 'claim_substantiation';
  file: FileDocumentOutputWritable;
  /**
   * Supporting Files
   */
  supporting_files?: Array<FileDocumentOutputWritable> | null;
  config: SubstantiationWorkflowConfig;
  /**
   * References
   */
  references?: Array<BibliographyItem>;
  /**
   * References Validated
   */
  references_validated?: Array<BibliographyItemValidationOutput>;
  /**
   * Chunks
   *
   * Lightweight chunk summaries without detailed analysis
   */
  chunks?: Array<DocumentChunkSummary>;
  main_document_summary?: DocumentSummary | null;
  /**
   * Supporting Documents Summaries
   */
  supporting_documents_summaries?: {
    [key: string]: DocumentSummary;
  } | null;
  /**
   * Live Reports Analysis
   */
  live_reports_analysis?: Array<EvidenceWeighterResponseWithClaimIndexOutput>;
  literature_review?: LiteratureReviewResponseOutput | null;
  methodology_comparison?: MethodologyComparisonResponseOutput | null;
  addendum_report?: ReportOutputOutput | null;
  /**
   * Ranked Issues
   */
  ranked_issues?: Array<DocumentIssue>;
  chunk_to_items?: ChunkToItemsOutput | null;
};

/**
 * DoclingDocument
 *
 * Raw Docling json_content passed through to frontend
 *
 * We don't parse/transform - just pass the structure as-is.
 * Frontend will handle the Docling format directly.
 *
 * All fields from Docling's json_content are stored in __pydantic_extra__
 * and serialized properly.
 */
export type DoclingDocumentWritable = {
  [key: string]: unknown;
};

/**
 * FileDocument
 */
export type FileDocumentOutputWritable = {
  /**
   * File Name
   *
   * The original name of the uploaded file, as saved in the user file system
   */
  file_name: string;
  /**
   * File Path
   *
   * The path to the uploaded file, as saved in the file system
   */
  file_path: string;
  /**
   * Original File Path
   *
   * Path to the original file if it was converted (e.g., original .docx before PDF conversion)
   */
  original_file_path?: string | null;
  /**
   * File Type
   *
   * The MIME type of the uploaded file
   */
  file_type: string;
  /**
   * Markdown
   *
   * The uploaded file content converted to markdown
   */
  markdown: string;
  /**
   * Markdown Token Count
   *
   * The approximate number of tokens in the markdown content
   */
  markdown_token_count: number;
  /**
   * File Id
   *
   * The UUID of the file record in the database (if available)
   */
  file_id?: string | null;
  /**
   * Full Docling document for internal processing (chunk mapping, etc.)
   */
  docling_document?: DoclingDocumentWritable | null;
};

/**
 * MethodologicalAlignmentState
 *
 * State for the methodological alignment workflow
 */
export type MethodologicalAlignmentStateWritable = {
  /**
   * Errors
   *
   * Errors that occurred during the workflow execution.
   */
  errors?: Array<WorkflowError>;
  /**
   * Type
   */
  type?: 'methodological_alignment';
  /**
   * The main source document
   */
  file: FileDocumentOutputWritable;
  /**
   * Methodology alignment analysis result
   */
  methodology_comparison?: MethodologyComparisonResponseOutput | null;
};

/**
 * SharedProjectResponse
 *
 * Response for a shared project with all necessary data.
 */
export type SharedProjectResponseWritable = {
  project: SharedProjectInfo;
  workflow_run?: SharedWorkflowRun | null;
  state?: ClaimSubstantiatorStateSummaryWritable | null;
};

/**
 * WorkflowRunDetail
 */
export type WorkflowRunDetailWritable = {
  run: WorkflowRun;
  /**
   * State
   */
  state:
    | ClaimSubstantiatorStateOutputWritable
    | MethodologicalAlignmentStateWritable
    | ReferenceDownloaderState
    | DocxGenerationState;
};

export type ReadHealthApiHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/health';
};

export type ReadHealthApiHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetSupportedAgentsApiSupportedAgentsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/supported-agents';
};

export type GetSupportedAgentsApiSupportedAgentsGetResponses = {
  /**
   * Response Get Supported Agents Api Supported Agents Get
   *
   * Successful Response
   */
  200: Array<AgentInfo>;
};

export type GetSupportedAgentsApiSupportedAgentsGetResponse =
  GetSupportedAgentsApiSupportedAgentsGetResponses[keyof GetSupportedAgentsApiSupportedAgentsGetResponses];

export type StartAnalysisApiStartAnalysisPostData = {
  body: BodyStartAnalysisApiStartAnalysisPost;
  path?: never;
  query?: never;
  url: '/api/start-analysis';
};

export type StartAnalysisApiStartAnalysisPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type StartAnalysisApiStartAnalysisPostError =
  StartAnalysisApiStartAnalysisPostErrors[keyof StartAnalysisApiStartAnalysisPostErrors];

export type StartAnalysisApiStartAnalysisPostResponses = {
  /**
   * Successful Response
   */
  200: StartWorkflowResponse;
};

export type StartAnalysisApiStartAnalysisPostResponse =
  StartAnalysisApiStartAnalysisPostResponses[keyof StartAnalysisApiStartAnalysisPostResponses];

export type RerunAnalysisEndpointApiRerunAnalysisPostData = {
  body: RerunAnalysisRequest;
  path?: never;
  query?: never;
  url: '/api/rerun-analysis';
};

export type RerunAnalysisEndpointApiRerunAnalysisPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RerunAnalysisEndpointApiRerunAnalysisPostError =
  RerunAnalysisEndpointApiRerunAnalysisPostErrors[keyof RerunAnalysisEndpointApiRerunAnalysisPostErrors];

export type RerunAnalysisEndpointApiRerunAnalysisPostResponses = {
  /**
   * Successful Response
   */
  200: StartWorkflowResponse;
};

export type RerunAnalysisEndpointApiRerunAnalysisPostResponse =
  RerunAnalysisEndpointApiRerunAnalysisPostResponses[keyof RerunAnalysisEndpointApiRerunAnalysisPostResponses];

export type GenerateEvalPackageApiGenerateEvalPackagePostData = {
  body: EvalPackageRequest;
  path?: never;
  query?: never;
  url: '/api/generate-eval-package';
};

export type GenerateEvalPackageApiGenerateEvalPackagePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GenerateEvalPackageApiGenerateEvalPackagePostError =
  GenerateEvalPackageApiGenerateEvalPackagePostErrors[keyof GenerateEvalPackageApiGenerateEvalPackagePostErrors];

export type GenerateEvalPackageApiGenerateEvalPackagePostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GenerateChunkEvalPackageApiGenerateChunkEvalPackagePostData = {
  body: ChunkEvalPackageRequest;
  path?: never;
  query?: never;
  url: '/api/generate-chunk-eval-package';
};

export type GenerateChunkEvalPackageApiGenerateChunkEvalPackagePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GenerateChunkEvalPackageApiGenerateChunkEvalPackagePostError =
  GenerateChunkEvalPackageApiGenerateChunkEvalPackagePostErrors[keyof GenerateChunkEvalPackageApiGenerateChunkEvalPackagePostErrors];

export type GenerateChunkEvalPackageApiGenerateChunkEvalPackagePostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type StartWorkflowApiWorkflowsStartPostData = {
  /**
   * Request
   */
  body: SubstantiationWorkflowConfig | MethodologicalAlignmentWorkflowConfig | ReferenceDownloaderWorkflowConfig;
  path?: never;
  query?: never;
  url: '/api/workflows/start';
};

export type StartWorkflowApiWorkflowsStartPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type StartWorkflowApiWorkflowsStartPostError =
  StartWorkflowApiWorkflowsStartPostErrors[keyof StartWorkflowApiWorkflowsStartPostErrors];

export type StartWorkflowApiWorkflowsStartPostResponses = {
  /**
   * Successful Response
   */
  200: StartWorkflowResponse;
};

export type StartWorkflowApiWorkflowsStartPostResponse =
  StartWorkflowApiWorkflowsStartPostResponses[keyof StartWorkflowApiWorkflowsStartPostResponses];

export type GetWorkflowStateApiWorkflowsWorkflowRunIdGetData = {
  body?: never;
  path: {
    /**
     * Workflow Run Id
     */
    workflow_run_id: string;
  };
  query?: never;
  url: '/api/workflows/{workflow_run_id}';
};

export type GetWorkflowStateApiWorkflowsWorkflowRunIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetWorkflowStateApiWorkflowsWorkflowRunIdGetError =
  GetWorkflowStateApiWorkflowsWorkflowRunIdGetErrors[keyof GetWorkflowStateApiWorkflowsWorkflowRunIdGetErrors];

export type GetWorkflowStateApiWorkflowsWorkflowRunIdGetResponses = {
  /**
   * Successful Response
   */
  200: WorkflowRunDetail;
};

export type GetWorkflowStateApiWorkflowsWorkflowRunIdGetResponse =
  GetWorkflowStateApiWorkflowsWorkflowRunIdGetResponses[keyof GetWorkflowStateApiWorkflowsWorkflowRunIdGetResponses];

export type GetChunkDetailsEndpointApiWorkflowRunWorkflowRunIdChunkChunkIndexGetData = {
  body?: never;
  path: {
    /**
     * Workflow Run Id
     */
    workflow_run_id: string;
    /**
     * Chunk Index
     */
    chunk_index: number;
  };
  query?: never;
  url: '/api/workflow-run/{workflow_run_id}/chunk/{chunk_index}';
};

export type GetChunkDetailsEndpointApiWorkflowRunWorkflowRunIdChunkChunkIndexGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetChunkDetailsEndpointApiWorkflowRunWorkflowRunIdChunkChunkIndexGetError =
  GetChunkDetailsEndpointApiWorkflowRunWorkflowRunIdChunkChunkIndexGetErrors[keyof GetChunkDetailsEndpointApiWorkflowRunWorkflowRunIdChunkChunkIndexGetErrors];

export type GetChunkDetailsEndpointApiWorkflowRunWorkflowRunIdChunkChunkIndexGetResponses = {
  /**
   * Successful Response
   */
  200: DocumentChunkOutput;
};

export type GetChunkDetailsEndpointApiWorkflowRunWorkflowRunIdChunkChunkIndexGetResponse =
  GetChunkDetailsEndpointApiWorkflowRunWorkflowRunIdChunkChunkIndexGetResponses[keyof GetChunkDetailsEndpointApiWorkflowRunWorkflowRunIdChunkChunkIndexGetResponses];

export type GetPageImageApiWorkflowRunsWorkflowRunIdPagesPageNumGetData = {
  body?: never;
  path: {
    /**
     * Workflow Run Id
     */
    workflow_run_id: string;
    /**
     * Page Num
     */
    page_num: number;
  };
  query?: never;
  url: '/api/workflow-runs/{workflow_run_id}/pages/{page_num}';
};

export type GetPageImageApiWorkflowRunsWorkflowRunIdPagesPageNumGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPageImageApiWorkflowRunsWorkflowRunIdPagesPageNumGetError =
  GetPageImageApiWorkflowRunsWorkflowRunIdPagesPageNumGetErrors[keyof GetPageImageApiWorkflowRunsWorkflowRunIdPagesPageNumGetErrors];

export type GetPageImageApiWorkflowRunsWorkflowRunIdPagesPageNumGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DownloadFileApiFilesDownloadFileIdGetData = {
  body?: never;
  path: {
    /**
     * File Id
     */
    file_id: string;
  };
  query?: never;
  url: '/api/files/download/{file_id}';
};

export type DownloadFileApiFilesDownloadFileIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DownloadFileApiFilesDownloadFileIdGetError =
  DownloadFileApiFilesDownloadFileIdGetErrors[keyof DownloadFileApiFilesDownloadFileIdGetErrors];

export type DownloadFileApiFilesDownloadFileIdGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetFeedbackApiFeedbackGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Workflow Run Id
     */
    workflow_run_id: string;
    /**
     * Entity Path
     */
    entity_path: string;
  };
  url: '/api/feedback';
};

export type GetFeedbackApiFeedbackGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetFeedbackApiFeedbackGetError = GetFeedbackApiFeedbackGetErrors[keyof GetFeedbackApiFeedbackGetErrors];

export type GetFeedbackApiFeedbackGetResponses = {
  /**
   * Response Get Feedback Api Feedback Get
   *
   * Successful Response
   */
  200: FeedbackResponse | null;
};

export type GetFeedbackApiFeedbackGetResponse =
  GetFeedbackApiFeedbackGetResponses[keyof GetFeedbackApiFeedbackGetResponses];

export type SubmitFeedbackApiFeedbackPostData = {
  body: FeedbackRequest;
  path?: never;
  query?: never;
  url: '/api/feedback';
};

export type SubmitFeedbackApiFeedbackPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SubmitFeedbackApiFeedbackPostError =
  SubmitFeedbackApiFeedbackPostErrors[keyof SubmitFeedbackApiFeedbackPostErrors];

export type SubmitFeedbackApiFeedbackPostResponses = {
  /**
   * Successful Response
   */
  200: FeedbackResponse;
};

export type SubmitFeedbackApiFeedbackPostResponse =
  SubmitFeedbackApiFeedbackPostResponses[keyof SubmitFeedbackApiFeedbackPostResponses];

export type GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetData = {
  body?: never;
  path: {
    /**
     * Workflow Run Id
     */
    workflow_run_id: string;
  };
  query?: never;
  url: '/api/feedback/workflow/{workflow_run_id}';
};

export type GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetError =
  GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetErrors[keyof GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetErrors];

export type GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetResponses = {
  /**
   * Response Get Workflow Feedback Api Feedback Workflow  Workflow Run Id  Get
   *
   * Successful Response
   */
  200: Array<FeedbackResponse>;
};

export type GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetResponse =
  GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetResponses[keyof GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetResponses];

export type DeleteFeedbackApiFeedbackFeedbackIdDeleteData = {
  body?: never;
  path: {
    /**
     * Feedback Id
     */
    feedback_id: string;
  };
  query?: never;
  url: '/api/feedback/{feedback_id}';
};

export type DeleteFeedbackApiFeedbackFeedbackIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteFeedbackApiFeedbackFeedbackIdDeleteError =
  DeleteFeedbackApiFeedbackFeedbackIdDeleteErrors[keyof DeleteFeedbackApiFeedbackFeedbackIdDeleteErrors];

export type DeleteFeedbackApiFeedbackFeedbackIdDeleteResponses = {
  /**
   * Response Delete Feedback Api Feedback  Feedback Id  Delete
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type DeleteFeedbackApiFeedbackFeedbackIdDeleteResponse =
  DeleteFeedbackApiFeedbackFeedbackIdDeleteResponses[keyof DeleteFeedbackApiFeedbackFeedbackIdDeleteResponses];

export type ListProjectsEndpointApiProjectsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/projects';
};

export type ListProjectsEndpointApiProjectsGetResponses = {
  /**
   * Response List Projects Endpoint Api Projects Get
   *
   * Successful Response
   */
  200: Array<ProjectListItem>;
};

export type ListProjectsEndpointApiProjectsGetResponse =
  ListProjectsEndpointApiProjectsGetResponses[keyof ListProjectsEndpointApiProjectsGetResponses];

export type CreateProjectEndpointApiProjectsPostData = {
  body: BodyCreateProjectEndpointApiProjectsPost;
  path?: never;
  query?: never;
  url: '/api/projects';
};

export type CreateProjectEndpointApiProjectsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateProjectEndpointApiProjectsPostError =
  CreateProjectEndpointApiProjectsPostErrors[keyof CreateProjectEndpointApiProjectsPostErrors];

export type CreateProjectEndpointApiProjectsPostResponses = {
  /**
   * Successful Response
   */
  201: ProjectDetailed;
};

export type CreateProjectEndpointApiProjectsPostResponse =
  CreateProjectEndpointApiProjectsPostResponses[keyof CreateProjectEndpointApiProjectsPostResponses];

export type DeleteProjectEndpointApiProjectProjectIdDeleteData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: '/api/project/{project_id}';
};

export type DeleteProjectEndpointApiProjectProjectIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteProjectEndpointApiProjectProjectIdDeleteError =
  DeleteProjectEndpointApiProjectProjectIdDeleteErrors[keyof DeleteProjectEndpointApiProjectProjectIdDeleteErrors];

export type DeleteProjectEndpointApiProjectProjectIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetProjectEndpointApiProjectProjectIdGetData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: '/api/project/{project_id}';
};

export type GetProjectEndpointApiProjectProjectIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetProjectEndpointApiProjectProjectIdGetError =
  GetProjectEndpointApiProjectProjectIdGetErrors[keyof GetProjectEndpointApiProjectProjectIdGetErrors];

export type GetProjectEndpointApiProjectProjectIdGetResponses = {
  /**
   * Successful Response
   */
  200: ProjectDetailed;
};

export type GetProjectEndpointApiProjectProjectIdGetResponse =
  GetProjectEndpointApiProjectProjectIdGetResponses[keyof GetProjectEndpointApiProjectProjectIdGetResponses];

export type UpdateProjectEndpointApiProjectProjectIdPatchData = {
  body: UpdateProjectRequest;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: '/api/project/{project_id}';
};

export type UpdateProjectEndpointApiProjectProjectIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateProjectEndpointApiProjectProjectIdPatchError =
  UpdateProjectEndpointApiProjectProjectIdPatchErrors[keyof UpdateProjectEndpointApiProjectProjectIdPatchErrors];

export type UpdateProjectEndpointApiProjectProjectIdPatchResponses = {
  /**
   * Successful Response
   */
  200: Project;
};

export type UpdateProjectEndpointApiProjectProjectIdPatchResponse =
  UpdateProjectEndpointApiProjectProjectIdPatchResponses[keyof UpdateProjectEndpointApiProjectProjectIdPatchResponses];

export type DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: {
    /**
     * Share Token
     *
     * Share token to include share links in comments
     */
    share_token?: string | null;
  };
  url: '/api/projects/{project_id}/docx/download';
};

export type DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetError =
  DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetErrors[keyof DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetErrors];

export type DownloadProjectDocxApiProjectsProjectIdDocxDownloadGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListProjectFilesEndpointApiProjectProjectIdFilesGetData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: '/api/project/{project_id}/files';
};

export type ListProjectFilesEndpointApiProjectProjectIdFilesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListProjectFilesEndpointApiProjectProjectIdFilesGetError =
  ListProjectFilesEndpointApiProjectProjectIdFilesGetErrors[keyof ListProjectFilesEndpointApiProjectProjectIdFilesGetErrors];

export type ListProjectFilesEndpointApiProjectProjectIdFilesGetResponses = {
  /**
   * Response List Project Files Endpoint Api Project  Project Id  Files Get
   *
   * Successful Response
   */
  200: Array<File>;
};

export type ListProjectFilesEndpointApiProjectProjectIdFilesGetResponse =
  ListProjectFilesEndpointApiProjectProjectIdFilesGetResponses[keyof ListProjectFilesEndpointApiProjectProjectIdFilesGetResponses];

export type DownloadAllProjectFilesApiProjectProjectIdFilesDownloadAllGetData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: '/api/project/{project_id}/files/download-all';
};

export type DownloadAllProjectFilesApiProjectProjectIdFilesDownloadAllGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DownloadAllProjectFilesApiProjectProjectIdFilesDownloadAllGetError =
  DownloadAllProjectFilesApiProjectProjectIdFilesDownloadAllGetErrors[keyof DownloadAllProjectFilesApiProjectProjectIdFilesDownloadAllGetErrors];

export type DownloadAllProjectFilesApiProjectProjectIdFilesDownloadAllGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetProjectShareStatusApiProjectsProjectIdShareGetData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: '/api/projects/{project_id}/share';
};

export type GetProjectShareStatusApiProjectsProjectIdShareGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetProjectShareStatusApiProjectsProjectIdShareGetError =
  GetProjectShareStatusApiProjectsProjectIdShareGetErrors[keyof GetProjectShareStatusApiProjectsProjectIdShareGetErrors];

export type GetProjectShareStatusApiProjectsProjectIdShareGetResponses = {
  /**
   * Successful Response
   */
  200: ShareStatusResponse;
};

export type GetProjectShareStatusApiProjectsProjectIdShareGetResponse =
  GetProjectShareStatusApiProjectsProjectIdShareGetResponses[keyof GetProjectShareStatusApiProjectsProjectIdShareGetResponses];

export type EnableProjectSharingApiProjectsProjectIdShareEnablePostData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: '/api/projects/{project_id}/share/enable';
};

export type EnableProjectSharingApiProjectsProjectIdShareEnablePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EnableProjectSharingApiProjectsProjectIdShareEnablePostError =
  EnableProjectSharingApiProjectsProjectIdShareEnablePostErrors[keyof EnableProjectSharingApiProjectsProjectIdShareEnablePostErrors];

export type EnableProjectSharingApiProjectsProjectIdShareEnablePostResponses = {
  /**
   * Successful Response
   */
  200: ShareStatusResponse;
};

export type EnableProjectSharingApiProjectsProjectIdShareEnablePostResponse =
  EnableProjectSharingApiProjectsProjectIdShareEnablePostResponses[keyof EnableProjectSharingApiProjectsProjectIdShareEnablePostResponses];

export type DisableProjectSharingApiProjectsProjectIdShareDisablePostData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: '/api/projects/{project_id}/share/disable';
};

export type DisableProjectSharingApiProjectsProjectIdShareDisablePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DisableProjectSharingApiProjectsProjectIdShareDisablePostError =
  DisableProjectSharingApiProjectsProjectIdShareDisablePostErrors[keyof DisableProjectSharingApiProjectsProjectIdShareDisablePostErrors];

export type DisableProjectSharingApiProjectsProjectIdShareDisablePostResponses = {
  /**
   * Successful Response
   */
  200: ShareStatusResponse;
};

export type DisableProjectSharingApiProjectsProjectIdShareDisablePostResponse =
  DisableProjectSharingApiProjectsProjectIdShareDisablePostResponses[keyof DisableProjectSharingApiProjectsProjectIdShareDisablePostResponses];

export type GetSharedResourceApiPublicShareTokenGetData = {
  body?: never;
  path: {
    /**
     * Token
     */
    token: string;
  };
  query?: never;
  url: '/api/public/share/{token}';
};

export type GetSharedResourceApiPublicShareTokenGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSharedResourceApiPublicShareTokenGetError =
  GetSharedResourceApiPublicShareTokenGetErrors[keyof GetSharedResourceApiPublicShareTokenGetErrors];

export type GetSharedResourceApiPublicShareTokenGetResponses = {
  /**
   * Successful Response
   */
  200: SharedProjectResponse;
};

export type GetSharedResourceApiPublicShareTokenGetResponse =
  GetSharedResourceApiPublicShareTokenGetResponses[keyof GetSharedResourceApiPublicShareTokenGetResponses];
