from __future__ import annotations

from enum import Enum
from langchain.chat_models import init_chat_model
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnableConfig

from lib.config.llm_models import gpt_5_model
from lib.models.agent import DEFAULT_LLM_TIMEOUT, AgentProtocol
from pydantic import BaseModel, Field


_addendum_prompt = ChatPromptTemplate.from_template(
    """
You are a professional technical writer formatting claim update reports based on the “Live Reports: Addendum” document style.

Your task is to **select the most salient updates and rewrite and format the raw model output** into a polished, Markdown-formatted report that mirrors the tone, structure, and logic of that template.

## Guidelines for Selecting the Most Salient Updates
- Select the updates that are most central to the argument of the report. (Use summary from the document to help you determine the most salient updates.) For example, if a claim is not associated with the central argument of the document, then updates for that claim should not be included in the report if other claims take precedence. 
- Limit the number of references to 10
- When possible provide url for the reference in the report.


---

## Structure

At the very top of the file, generate a **YAML metadata header** (front matter), followed by the Markdown-formatted body.

Include the following keys (all in lowercase, no extra indentation):

```yaml
report_id: <autogenerated or provided ID>
generated_on: <current date in YYYY-MM-DD format>
model_source: gpt-5
report_type: claim_update
author: "Live Reports AI"
version: 1.0
```

#### Markdown Body

After this YAML block, insert a blank line, then begin the Markdown content. Given the raw model output below, rewrite and structure it into a **Markdown report** that mirrors the tone and layout of the following template.

---- template ----
```markdown
# Addendum: [Title of Report or Claim Update Topic]

## High Level Summary
- Provide a concise paragraph (3–5 sentences) summarizing the key updates, overall direction, or major implications.

## Background Updates
- Describe contextual or theoretical changes that influenced the claims.
- Each paragraph or bullet should start with a strong declarative phrase (e.g., “New analysis indicates…”).

## Methodology Updates
- Describe procedural, experimental, or analytical revisions.
- Keep items 1–3 sentences each.
- Reference supporting materials where relevant (e.g., “see Appendix A”).

## Results Updates
- State outcomes, comparisons, or numerical adjustments.
- Clearly mention any revised values (e.g., “updated from 5.5% to 4.1%”).

## Implications Updates
- Explain practical or strategic consequences of the above updates on the conclusions of report
- Use prescriptive tone (“This requires…”, “This suggests…”).

## References
1. [Author(s)]. (Year). *Title*. [Source or journal].
2. ...
```

--------

#### Requirements:
1. Use **section headers** in this order:
   - `# Addendum: [Report Title or Topic]`
   - `## High Level Summary`
   - `## Background Updates`
   - `## Methodology Updates`
   - `## Results Updates`
   - `## Implications Updates`
   - `## References`

2. Maintain a **formal and evidence-driven tone**, with clear causal or comparative phrasing (e.g., “This adjustment necessitates…”, “This modification ensures…”).

3. Each update paragraph should:
   - Begin with a concrete noun or action (“New analysis shows…”, “The dataset was expanded…”).
   - Reference supporting context or implications.
   - Remain **1–3 sentences** long.

4. Insert **numerical or symbolic citations** in square brackets `[1]`, `[2]`, etc., to mimic reference numbering.

5. End with a numbered reference list in plain-text style, e.g.:

[1] Author(s). (Year). Title. Journal or Source.

6. Output only **Markdown-formatted text** (no extra commentary).


#### Input:
```
{records_json}
```

#### Additional context:
Document context: {domain_context}
Audience Context: {audience_context}
Title: {document_title}
Summary (optional): {document_summary}

#### Output:
(Styled Markdown report with numbered references)
    """
)


class AddendumReportGeneratorAgent(AgentProtocol):
    name: str = "Addendum Report Generator"
    description: str = (
        "Aggregate live reports and produce a markdown formatted addendum report"
    )

    def __init__(self):
        self.llm = init_chat_model(
            gpt_5_model.model_name, temperature=0.2, timeout=DEFAULT_LLM_TIMEOUT
        )

    async def ainvoke(self, prompt_kwargs: dict, config: RunnableConfig = None) -> str:
        messages = _addendum_prompt.format_messages(**prompt_kwargs)
        response = await self.llm.ainvoke(messages, config=config)
        return response.content if hasattr(response, "content") else str(response)


addendum_report_generator_agent = AddendumReportGeneratorAgent()
