/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ClaimFeedbackRequest, FeedbackResponse, HTTPValidationError } from '../models/index';
import {
  ClaimFeedbackRequestFromJSON,
  ClaimFeedbackRequestToJSON,
  FeedbackResponseFromJSON,
  FeedbackResponseToJSON,
  HTTPValidationErrorFromJSON,
  HTTPValidationErrorToJSON,
} from '../models/index';

export interface DeleteFeedbackApiFeedbackFeedbackIdDeleteRequest {
  feedbackId: string;
}

export interface GetClaimFeedbackApiFeedbackClaimGetRequest {
  workflowRunId: string;
  chunkIndex: number;
  claimIndex: number;
}

export interface GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetRequest {
  workflowRunId: string;
}

export interface SubmitClaimFeedbackApiFeedbackClaimPostRequest {
  claimFeedbackRequest: ClaimFeedbackRequest;
}

/**
 *
 */
export class FeedbackApi extends runtime.BaseAPI {
  /**
   * Delete feedback by ID
   * Delete Feedback
   */
  async deleteFeedbackApiFeedbackFeedbackIdDeleteRaw(
    requestParameters: DeleteFeedbackApiFeedbackFeedbackIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: any }>> {
    if (requestParameters['feedbackId'] == null) {
      throw new runtime.RequiredError(
        'feedbackId',
        'Required parameter "feedbackId" was null or undefined when calling deleteFeedbackApiFeedbackFeedbackIdDelete().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/feedback/{feedback_id}`;
    urlPath = urlPath.replace(`{${'feedback_id'}}`, encodeURIComponent(String(requestParameters['feedbackId'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Delete feedback by ID
   * Delete Feedback
   */
  async deleteFeedbackApiFeedbackFeedbackIdDelete(
    requestParameters: DeleteFeedbackApiFeedbackFeedbackIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: any }> {
    const response = await this.deleteFeedbackApiFeedbackFeedbackIdDeleteRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get feedback for a specific claim
   * Get Claim Feedback
   */
  async getClaimFeedbackApiFeedbackClaimGetRaw(
    requestParameters: GetClaimFeedbackApiFeedbackClaimGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<FeedbackResponse>> {
    if (requestParameters['workflowRunId'] == null) {
      throw new runtime.RequiredError(
        'workflowRunId',
        'Required parameter "workflowRunId" was null or undefined when calling getClaimFeedbackApiFeedbackClaimGet().',
      );
    }

    if (requestParameters['chunkIndex'] == null) {
      throw new runtime.RequiredError(
        'chunkIndex',
        'Required parameter "chunkIndex" was null or undefined when calling getClaimFeedbackApiFeedbackClaimGet().',
      );
    }

    if (requestParameters['claimIndex'] == null) {
      throw new runtime.RequiredError(
        'claimIndex',
        'Required parameter "claimIndex" was null or undefined when calling getClaimFeedbackApiFeedbackClaimGet().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['workflowRunId'] != null) {
      queryParameters['workflow_run_id'] = requestParameters['workflowRunId'];
    }

    if (requestParameters['chunkIndex'] != null) {
      queryParameters['chunk_index'] = requestParameters['chunkIndex'];
    }

    if (requestParameters['claimIndex'] != null) {
      queryParameters['claim_index'] = requestParameters['claimIndex'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/feedback/claim`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => FeedbackResponseFromJSON(jsonValue));
  }

  /**
   * Get feedback for a specific claim
   * Get Claim Feedback
   */
  async getClaimFeedbackApiFeedbackClaimGet(
    requestParameters: GetClaimFeedbackApiFeedbackClaimGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<FeedbackResponse> {
    const response = await this.getClaimFeedbackApiFeedbackClaimGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get all feedback for a workflow run
   * Get Workflow Feedback
   */
  async getWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetRaw(
    requestParameters: GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<FeedbackResponse>>> {
    if (requestParameters['workflowRunId'] == null) {
      throw new runtime.RequiredError(
        'workflowRunId',
        'Required parameter "workflowRunId" was null or undefined when calling getWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/feedback/workflow/{workflow_run_id}`;
    urlPath = urlPath.replace(`{${'workflow_run_id'}}`, encodeURIComponent(String(requestParameters['workflowRunId'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FeedbackResponseFromJSON));
  }

  /**
   * Get all feedback for a workflow run
   * Get Workflow Feedback
   */
  async getWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGet(
    requestParameters: GetWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<FeedbackResponse>> {
    const response = await this.getWorkflowFeedbackApiFeedbackWorkflowWorkflowRunIdGetRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Submit or update feedback for a specific claim
   * Submit Claim Feedback
   */
  async submitClaimFeedbackApiFeedbackClaimPostRaw(
    requestParameters: SubmitClaimFeedbackApiFeedbackClaimPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<FeedbackResponse>> {
    if (requestParameters['claimFeedbackRequest'] == null) {
      throw new runtime.RequiredError(
        'claimFeedbackRequest',
        'Required parameter "claimFeedbackRequest" was null or undefined when calling submitClaimFeedbackApiFeedbackClaimPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/api/feedback/claim`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ClaimFeedbackRequestToJSON(requestParameters['claimFeedbackRequest']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => FeedbackResponseFromJSON(jsonValue));
  }

  /**
   * Submit or update feedback for a specific claim
   * Submit Claim Feedback
   */
  async submitClaimFeedbackApiFeedbackClaimPost(
    requestParameters: SubmitClaimFeedbackApiFeedbackClaimPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<FeedbackResponse> {
    const response = await this.submitClaimFeedbackApiFeedbackClaimPostRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
