/* tslint:disable */
/* eslint-disable */
/**
 * AI Analyst API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { HTTPValidationError, ShareStatusResponse } from '../models/index';
import {
  HTTPValidationErrorFromJSON,
  HTTPValidationErrorToJSON,
  ShareStatusResponseFromJSON,
  ShareStatusResponseToJSON,
} from '../models/index';

export interface DisableProjectSharingApiProjectsProjectIdShareDisablePostRequest {
  projectId: string;
}

export interface EnableProjectSharingApiProjectsProjectIdShareEnablePostRequest {
  projectId: string;
}

export interface GetProjectShareStatusApiProjectsProjectIdShareGetRequest {
  projectId: string;
}

/**
 *
 */
export class ShareApi extends runtime.BaseAPI {
  /**
   * Disable sharing for a project (deactivates the share link).
   * Disable Project Sharing
   */
  async disableProjectSharingApiProjectsProjectIdShareDisablePostRaw(
    requestParameters: DisableProjectSharingApiProjectsProjectIdShareDisablePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ShareStatusResponse>> {
    if (requestParameters['projectId'] == null) {
      throw new runtime.RequiredError(
        'projectId',
        'Required parameter "projectId" was null or undefined when calling disableProjectSharingApiProjectsProjectIdShareDisablePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('HTTPBearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/projects/{project_id}/share/disable`;
    urlPath = urlPath.replace(`{${'project_id'}}`, encodeURIComponent(String(requestParameters['projectId'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ShareStatusResponseFromJSON(jsonValue));
  }

  /**
   * Disable sharing for a project (deactivates the share link).
   * Disable Project Sharing
   */
  async disableProjectSharingApiProjectsProjectIdShareDisablePost(
    requestParameters: DisableProjectSharingApiProjectsProjectIdShareDisablePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ShareStatusResponse> {
    const response = await this.disableProjectSharingApiProjectsProjectIdShareDisablePostRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Enable sharing for a project (creates a share link if none exists).
   * Enable Project Sharing
   */
  async enableProjectSharingApiProjectsProjectIdShareEnablePostRaw(
    requestParameters: EnableProjectSharingApiProjectsProjectIdShareEnablePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ShareStatusResponse>> {
    if (requestParameters['projectId'] == null) {
      throw new runtime.RequiredError(
        'projectId',
        'Required parameter "projectId" was null or undefined when calling enableProjectSharingApiProjectsProjectIdShareEnablePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('HTTPBearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/projects/{project_id}/share/enable`;
    urlPath = urlPath.replace(`{${'project_id'}}`, encodeURIComponent(String(requestParameters['projectId'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ShareStatusResponseFromJSON(jsonValue));
  }

  /**
   * Enable sharing for a project (creates a share link if none exists).
   * Enable Project Sharing
   */
  async enableProjectSharingApiProjectsProjectIdShareEnablePost(
    requestParameters: EnableProjectSharingApiProjectsProjectIdShareEnablePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ShareStatusResponse> {
    const response = await this.enableProjectSharingApiProjectsProjectIdShareEnablePostRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get the sharing status for a project.
   * Get Project Share Status
   */
  async getProjectShareStatusApiProjectsProjectIdShareGetRaw(
    requestParameters: GetProjectShareStatusApiProjectsProjectIdShareGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ShareStatusResponse>> {
    if (requestParameters['projectId'] == null) {
      throw new runtime.RequiredError(
        'projectId',
        'Required parameter "projectId" was null or undefined when calling getProjectShareStatusApiProjectsProjectIdShareGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('HTTPBearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/projects/{project_id}/share`;
    urlPath = urlPath.replace(`{${'project_id'}}`, encodeURIComponent(String(requestParameters['projectId'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ShareStatusResponseFromJSON(jsonValue));
  }

  /**
   * Get the sharing status for a project.
   * Get Project Share Status
   */
  async getProjectShareStatusApiProjectsProjectIdShareGet(
    requestParameters: GetProjectShareStatusApiProjectsProjectIdShareGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ShareStatusResponse> {
    const response = await this.getProjectShareStatusApiProjectsProjectIdShareGetRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
